<?php

use Illuminate\Database\Seeder;

class PettyCashAccountHeadAccountTitleTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('petty_cash_account_head_account_title')->truncate();

        DB::table('petty_cash_account_head_account_title')->insert(array(
            array('petty_cash_account_head_id' =>1, 'petty_cash_account_title_id'=> 18),
            array('petty_cash_account_head_id' =>1, 'petty_cash_account_title_id'=> 17),
            array('petty_cash_account_head_id' =>1, 'petty_cash_account_title_id'=> 11),
            array('petty_cash_account_head_id' =>1, 'petty_cash_account_title_id'=> 16),
            array('petty_cash_account_head_id' =>1, 'petty_cash_account_title_id'=> 39),
            array('petty_cash_account_head_id' =>1, 'petty_cash_account_title_id'=> 43),
            array('petty_cash_account_head_id' =>1, 'petty_cash_account_title_id'=> 38),
            array('petty_cash_account_head_id' =>1, 'petty_cash_account_title_id'=> 42),
            array('petty_cash_account_head_id' =>1, 'petty_cash_account_title_id'=> 59),
            array('petty_cash_account_head_id' =>1, 'petty_cash_account_title_id'=> 22),
            array('petty_cash_account_head_id' =>1, 'petty_cash_account_title_id'=> 5),
            array('petty_cash_account_head_id' =>1, 'petty_cash_account_title_id'=> 30),
            array('petty_cash_account_head_id' =>1, 'petty_cash_account_title_id'=> 29),
            array('petty_cash_account_head_id' =>1, 'petty_cash_account_title_id'=> 19),
            array('petty_cash_account_head_id' =>1, 'petty_cash_account_title_id'=> 9),
            array('petty_cash_account_head_id' =>1, 'petty_cash_account_title_id'=> 10),
            array('petty_cash_account_head_id' =>1, 'petty_cash_account_title_id'=> 1),
            array('petty_cash_account_head_id' =>1, 'petty_cash_account_title_id'=> 55),
            array('petty_cash_account_head_id' =>1, 'petty_cash_account_title_id'=> 60),
            array('petty_cash_account_head_id' =>1, 'petty_cash_account_title_id'=> 58),
            array('petty_cash_account_head_id' =>1, 'petty_cash_account_title_id'=> 14),
            array('petty_cash_account_head_id' =>2, 'petty_cash_account_title_id'=> 31),
            array('petty_cash_account_head_id' =>2, 'petty_cash_account_title_id'=> 33),
            array('petty_cash_account_head_id' =>2, 'petty_cash_account_title_id'=> 34),
            array('petty_cash_account_head_id' =>2, 'petty_cash_account_title_id'=> 59),
            array('petty_cash_account_head_id' =>2, 'petty_cash_account_title_id'=> 51),
            array('petty_cash_account_head_id' =>2, 'petty_cash_account_title_id'=> 58),
            array('petty_cash_account_head_id' =>3, 'petty_cash_account_title_id'=> 11),
            array('petty_cash_account_head_id' =>3, 'petty_cash_account_title_id'=> 9),
            array('petty_cash_account_head_id' =>3, 'petty_cash_account_title_id'=> 4),
            array('petty_cash_account_head_id' =>4, 'petty_cash_account_title_id'=> 48),
            array('petty_cash_account_head_id' =>4, 'petty_cash_account_title_id'=> 58),
            array('petty_cash_account_head_id' =>4, 'petty_cash_account_title_id'=> 60),
            array('petty_cash_account_head_id' =>4, 'petty_cash_account_title_id'=> 38),
            array('petty_cash_account_head_id' =>4, 'petty_cash_account_title_id'=> 57),
            array('petty_cash_account_head_id' =>4, 'petty_cash_account_title_id'=> 55),
            array('petty_cash_account_head_id' =>5, 'petty_cash_account_title_id'=> 3),
            array('petty_cash_account_head_id' =>5, 'petty_cash_account_title_id'=> 32),
            array('petty_cash_account_head_id' =>6, 'petty_cash_account_title_id'=> 21),
            array('petty_cash_account_head_id' =>6, 'petty_cash_account_title_id'=> 55),
            array('petty_cash_account_head_id' =>6, 'petty_cash_account_title_id'=> 11),
            array('petty_cash_account_head_id' =>6, 'petty_cash_account_title_id'=> 61),
            array('petty_cash_account_head_id' =>6, 'petty_cash_account_title_id'=> 9),
            array('petty_cash_account_head_id' =>6, 'petty_cash_account_title_id'=> 25),
            array('petty_cash_account_head_id' =>6, 'petty_cash_account_title_id'=> 16),
            array('petty_cash_account_head_id' =>6, 'petty_cash_account_title_id'=> 58),
            array('petty_cash_account_head_id' =>6, 'petty_cash_account_title_id'=> 62),
            array('petty_cash_account_head_id' =>6, 'petty_cash_account_title_id'=> 48),
            array('petty_cash_account_head_id' =>6, 'petty_cash_account_title_id'=> 22),
            array('petty_cash_account_head_id' =>6, 'petty_cash_account_title_id'=> 5),
            array('petty_cash_account_head_id' =>7, 'petty_cash_account_title_id'=> 50),
            array('petty_cash_account_head_id' =>7, 'petty_cash_account_title_id'=> 63),
            array('petty_cash_account_head_id' =>7, 'petty_cash_account_title_id'=> 28),
            array('petty_cash_account_head_id' =>7, 'petty_cash_account_title_id'=> 52),
            array('petty_cash_account_head_id' =>7, 'petty_cash_account_title_id'=> 59),
            array('petty_cash_account_head_id' =>7, 'petty_cash_account_title_id'=> 62),
            array('petty_cash_account_head_id' =>7, 'petty_cash_account_title_id'=> 58),
            array('petty_cash_account_head_id' =>7, 'petty_cash_account_title_id'=> 60),
            array('petty_cash_account_head_id' =>7, 'petty_cash_account_title_id'=> 15),
            array('petty_cash_account_head_id' =>7, 'petty_cash_account_title_id'=> 20),
            array('petty_cash_account_head_id' =>7, 'petty_cash_account_title_id'=> 62),
            array('petty_cash_account_head_id' =>7, 'petty_cash_account_title_id'=> 64),
            array('petty_cash_account_head_id' =>7, 'petty_cash_account_title_id'=> 27),
            array('petty_cash_account_head_id' =>7, 'petty_cash_account_title_id'=> 8),
            array('petty_cash_account_head_id' =>7, 'petty_cash_account_title_id'=> 1),
            array('petty_cash_account_head_id' =>8, 'petty_cash_account_title_id'=> 38),
            array('petty_cash_account_head_id' =>8, 'petty_cash_account_title_id'=> 41),
            array('petty_cash_account_head_id' =>8, 'petty_cash_account_title_id'=> 56),
            array('petty_cash_account_head_id' =>8, 'petty_cash_account_title_id'=> 15),
            array('petty_cash_account_head_id' =>8, 'petty_cash_account_title_id'=> 16),
            array('petty_cash_account_head_id' =>8, 'petty_cash_account_title_id'=> 59),
            array('petty_cash_account_head_id' =>8, 'petty_cash_account_title_id'=> 39),
            array('petty_cash_account_head_id' =>8, 'petty_cash_account_title_id'=> 40),
            array('petty_cash_account_head_id' =>8, 'petty_cash_account_title_id'=> 48),
            array('petty_cash_account_head_id' =>8, 'petty_cash_account_title_id'=> 6),
            array('petty_cash_account_head_id' =>9, 'petty_cash_account_title_id'=> 36),
            array('petty_cash_account_head_id' =>9, 'petty_cash_account_title_id'=> 11),
            array('petty_cash_account_head_id' =>9, 'petty_cash_account_title_id'=> 26),
            array('petty_cash_account_head_id' =>9, 'petty_cash_account_title_id'=> 41),
            array('petty_cash_account_head_id' =>9, 'petty_cash_account_title_id'=> 16),
            array('petty_cash_account_head_id' =>9, 'petty_cash_account_title_id'=> 6),

            array('petty_cash_account_head_id' =>10, 'petty_cash_account_title_id'=> 25),
            array('petty_cash_account_head_id' =>10, 'petty_cash_account_title_id'=> 6),
            array('petty_cash_account_head_id' =>10, 'petty_cash_account_title_id'=> 7),
            array('petty_cash_account_head_id' =>10, 'petty_cash_account_title_id'=> 62),
            array('petty_cash_account_head_id' =>10, 'petty_cash_account_title_id'=> 37),
            array('petty_cash_account_head_id' =>10, 'petty_cash_account_title_id'=> 35),
            array('petty_cash_account_head_id' =>10, 'petty_cash_account_title_id'=> 60),
            array('petty_cash_account_head_id' =>10, 'petty_cash_account_title_id'=> 24),
            array('petty_cash_account_head_id' =>10, 'petty_cash_account_title_id'=> 8),
            array('petty_cash_account_head_id' =>10, 'petty_cash_account_title_id'=> 17),
            array('petty_cash_account_head_id' =>10, 'petty_cash_account_title_id'=> 39),
            array('petty_cash_account_head_id' =>10, 'petty_cash_account_title_id'=> 13),
            array('petty_cash_account_head_id' =>10, 'petty_cash_account_title_id'=> 11),
            array('petty_cash_account_head_id' =>10, 'petty_cash_account_title_id'=> 55),
            array('petty_cash_account_head_id' =>10, 'petty_cash_account_title_id'=> 58),
            array('petty_cash_account_head_id' =>11, 'petty_cash_account_title_id'=> 52),
            array('petty_cash_account_head_id' =>11, 'petty_cash_account_title_id'=> 44),
            array('petty_cash_account_head_id' =>12, 'petty_cash_account_title_id'=> 46),
            array('petty_cash_account_head_id' =>13, 'petty_cash_account_title_id'=> 15),
            array('petty_cash_account_head_id' =>13, 'petty_cash_account_title_id'=> 49),
            array('petty_cash_account_head_id' =>14, 'petty_cash_account_title_id'=> 48),
            array('petty_cash_account_head_id' =>15, 'petty_cash_account_title_id'=> 49),
            array('petty_cash_account_head_id' =>15, 'petty_cash_account_title_id'=> 54),
            array('petty_cash_account_head_id' =>15, 'petty_cash_account_title_id'=> 21),
            array('petty_cash_account_head_id' =>15, 'petty_cash_account_title_id'=> 33),
            array('petty_cash_account_head_id' =>15, 'petty_cash_account_title_id'=> 4),
            array('petty_cash_account_head_id' =>15, 'petty_cash_account_title_id'=> 60),
            array('petty_cash_account_head_id' =>15, 'petty_cash_account_title_id'=> 45),
            array('petty_cash_account_head_id' =>15, 'petty_cash_account_title_id'=> 12),
            array('petty_cash_account_head_id' =>15, 'petty_cash_account_title_id'=> 23),
            array('petty_cash_account_head_id' =>16, 'petty_cash_account_title_id'=> 53),
            array('petty_cash_account_head_id' =>16, 'petty_cash_account_title_id'=> 8),
            array('petty_cash_account_head_id' =>16, 'petty_cash_account_title_id'=> 21),
            array('petty_cash_account_head_id' =>16, 'petty_cash_account_title_id'=> 48),
            array('petty_cash_account_head_id' =>17, 'petty_cash_account_title_id'=> 13),
            array('petty_cash_account_head_id' =>17, 'petty_cash_account_title_id'=> 25),
            array('petty_cash_account_head_id' =>17, 'petty_cash_account_title_id'=> 57),
            array('petty_cash_account_head_id' =>17, 'petty_cash_account_title_id'=> 24),
            array('petty_cash_account_head_id' =>17, 'petty_cash_account_title_id'=> 31),
            array('petty_cash_account_head_id' =>18, 'petty_cash_account_title_id'=> 49),
            array('petty_cash_account_head_id' =>18, 'petty_cash_account_title_id'=> 9),
            array('petty_cash_account_head_id' =>18, 'petty_cash_account_title_id'=> 45),
            
            
        ));
    }
}
