<?php

use Illuminate\Database\Seeder;

class AddActivityTrailActionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('activity_trail_actions')->truncate();
        DB::table('activity_trail_actions')->insert(array(
            array('id' => 1, 'screen_name' => 'Pending Accounts List', 'action'=> 'View'),
            array('id' => 2, 'screen_name' => 'Active Account List', 'action'=> 'View'),
            array('id' => 3, 'screen_name' => 'Retail Accounts', 'action'=> 'View'),
            array('id' => 4, 'screen_name' => 'Leads Management', 'action'=> 'View'),
            array('id' => 5, 'screen_name' => 'Shipment Pieces List', 'action'=> 'View'),
            array('id' => 6, 'screen_name' => 'Pending Pickups', 'action'=> 'View'),
            array('id' => 7, 'screen_name' => 'Rider Pickups', 'action'=> 'View'),
            array('id' => 8, 'screen_name' => 'Rider Pickup Action Logs', 'action'=> 'View'),
            array('id' => 9, 'screen_name' => 'Rider Receiving', 'action'=> 'View'),
            array('id' => 10, 'screen_name' => 'Pickup Routes', 'action'=> 'View'),
            array('id' => 11, 'screen_name' => 'Supply Chain Management', 'action'=> 'View'),
            array('id' => 12, 'screen_name' => 'Bag(s) History', 'action'=> 'View'),
            array('id' => 13, 'screen_name' => 'Master Cargo In Transit', 'action'=> 'View'),
            array('id' => 14, 'screen_name' => 'Pending Bags for Receiving', 'action'=> 'View'),
            array('id' => 15, 'screen_name' => 'Master Cargo Received', 'action'=> 'View'),
            array('id' => 16, 'screen_name' => 'Master Cargo History', 'action'=> 'View'),
            array('id' => 17, 'screen_name' => 'Runners On Route', 'action'=> 'View'),
            array('id' => 18, 'screen_name' => 'Supply Chain Shipment On Hold History', 'action'=> 'View'),
            array('id' => 19, 'screen_name' => 'Pending Deliveries', 'action'=> 'View'),
            array('id' => 20, 'screen_name' => 'Receive Deliveries', 'action'=> 'View'),
            array('id' => 21, 'screen_name' => 'Pending Cash Collection COD', 'action'=> 'View'),
            array('id' => 22, 'screen_name' => 'Pending Cash Collection Retail', 'action'=> 'View'),
            array('id' => 23, 'screen_name' => 'Completed Deliveries COD', 'action'=> 'View'),
            array('id' => 24, 'screen_name' => 'Completed Deliveries Retail', 'action'=> 'View'),
            array('id' => 25, 'screen_name' => 'Station Deposit Notes', 'action'=> 'View'),
            array('id' => 26, 'screen_name' => 'Return Confirmation Pending Shipments', 'action'=> 'View'),
            array('id' => 27, 'screen_name' => 'Return Confirmed Shipments', 'action'=> 'View'),
            array('id' => 28, 'screen_name' => 'Return Deliveries History', 'action'=> 'View'),
            array('id' => 29, 'screen_name' => 'Make Payments', 'action'=> 'View'),
            array('id' => 30, 'screen_name' => 'Done Payments', 'action'=> 'View'),
            array('id' => 31, 'screen_name' => 'Make Payments Pickup Wise', 'action'=> 'View'),
            array('id' => 32, 'screen_name' => 'Retail Make Payments', 'action'=> 'View'),
            array('id' => 33, 'screen_name' => 'Retail Done Payments', 'action'=> 'View'),
            array('id' => 34, 'screen_name' => 'Pending Invoices', 'action'=> 'View'),
            array('id' => 35, 'screen_name' => 'Received Invoices', 'action'=> 'View'),
            array('id' => 36, 'screen_name' => 'Outstanding SDN', 'action'=> 'View'),
            array('id' => 37, 'screen_name' => 'Outstanding Shipments', 'action'=> 'View'),
            array('id' => 38, 'screen_name' => 'Outstanding Walk-In Shipments', 'action'=> 'View'),
            array('id' => 39, 'screen_name' => 'Petty Cash Statements', 'action'=> 'View'),
            array('id' => 40, 'screen_name' => 'Approved Petty Cash Statements', 'action'=> 'View'),
            array('id' => 41, 'screen_name' => 'Rejected Petty Cash Statements', 'action'=> 'View'),
            array('id' => 42, 'screen_name' => 'Launched/Re-Open Requests', 'action'=> 'View'),
            array('id' => 43, 'screen_name' => 'Consignee Info Requests', 'action'=> 'View'),
            array('id' => 44, 'screen_name' => 'Order Management', 'action'=> 'View'),
            array('id' => 45, 'screen_name' => 'Month Closing-Pending', 'action'=> 'View'),
            array('id' => 46, 'screen_name' => 'Month Closing-Resolved', 'action'=> 'View'),
            array('id' => 47, 'screen_name' => 'Misrouted History', 'action'=> 'View'),
            array('id' => 48, 'screen_name' => 'Lost Shipments', 'action'=> 'View'),
            array('id' => 49, 'screen_name' => 'Intercept Rebook History', 'action'=> 'View'),
            array('id' => 50, 'screen_name' => 'Sales Person Targets', 'action'=> 'View'),
            array('id' => 51, 'screen_name' => 'Sales Person Targets History', 'action'=> 'View'),
            array('id' => 52, 'screen_name' => 'Trax Directory', 'action'=> 'View'),
            array('id' => 53, 'screen_name' => 'International Tracking Upload', 'action'=> 'View'),
            array('id' => 54, 'screen_name' => 'Active Employees List', 'action'=> 'View'),
            array('id' => 55, 'screen_name' => 'Overall Commission Dashboard', 'action'=> 'View'),
            array('id' => 56, 'screen_name' => 'Employee Attendance', 'action'=> 'View'),
            array('id' => 57, 'screen_name' => 'Employee Directory', 'action'=> 'View'),
            array('id' => 58, 'screen_name' => 'Permanent Riders', 'action'=> 'View'),
            array('id' => 59, 'screen_name' => 'Incentive Riders', 'action'=> 'View'),
            array('id' => 60, 'screen_name' => 'Riders Pending Request', 'action'=> 'View'),
            array('id' => 61, 'screen_name' => 'Pending Accounts List', 'action'=> 'Excel Download'),
            array('id' => 62, 'screen_name' => 'Active Account List', 'action'=> 'Excel Download'),
            array('id' => 63, 'screen_name' => 'Retail Accounts', 'action'=> 'Excel Download'),
            array('id' => 64, 'screen_name' => 'Leads Management', 'action'=> 'Excel Download'),
            array('id' => 65, 'screen_name' => 'Shipment Pieces List', 'action'=> 'Excel Download'),
            array('id' => 66, 'screen_name' => 'Pending Pickups', 'action'=> 'Excel Download'),
            array('id' => 67, 'screen_name' => 'Rider Pickups', 'action'=> 'Excel Download'),
            array('id' => 68, 'screen_name' => 'Rider Pickup Action Logs', 'action'=> 'Excel Download'),
            array('id' => 69, 'screen_name' => 'Rider Receiving', 'action'=> 'Excel Download'),
            array('id' => 70, 'screen_name' => 'Pickup Routes', 'action'=> 'Excel Download'),
            array('id' => 71, 'screen_name' => 'Supply Chain Management', 'action'=> 'Excel Download'),
            array('id' => 72, 'screen_name' => 'Bag(s) History', 'action'=> 'Excel Download'),
            array('id' => 73, 'screen_name' => 'Master Cargo In Transit', 'action'=> 'Excel Download'),
            array('id' => 74, 'screen_name' => 'Pending Bags for Receiving', 'action'=> 'Excel Download'),
            array('id' => 75, 'screen_name' => 'Master Cargo Received', 'action'=> 'Excel Download'),
            array('id' => 76, 'screen_name' => 'Master Cargo History', 'action'=> 'Excel Download'),
            array('id' => 77, 'screen_name' => 'Runners On Route', 'action'=> 'Excel Download'),
            array('id' => 78, 'screen_name' => 'Supply Chain Shipment On Hold History', 'action'=> 'Excel Download'),
            array('id' => 79, 'screen_name' => 'Pending Deliveries', 'action'=> 'Excel Download'),
            array('id' => 80, 'screen_name' => 'Receive Deliveries', 'action'=> 'Excel Download'),
            array('id' => 81, 'screen_name' => 'Pending Cash Collection COD', 'action'=> 'Excel Download'),
            array('id' => 82, 'screen_name' => 'Pending Cash Collection Retail', 'action'=> 'Excel Download'),
            array('id' => 83, 'screen_name' => 'Completed Deliveries COD', 'action'=> 'Excel Download'),
            array('id' => 84, 'screen_name' => 'Completed Deliveries Retail', 'action'=> 'Excel Download'),
            array('id' => 85, 'screen_name' => 'Station Deposit Notes', 'action'=> 'Excel Download'),
            array('id' => 86, 'screen_name' => 'Return Confirmation Pending Shipments', 'action'=> 'Excel Download'),
            array('id' => 87, 'screen_name' => 'Return Confirmed Shipments', 'action'=> 'Excel Download'),
            array('id' => 88, 'screen_name' => 'Return Deliveries History', 'action'=> 'Excel Download'),
            array('id' => 89, 'screen_name' => 'Make Payments', 'action'=> 'Excel Download'),
            array('id' => 90, 'screen_name' => 'Done Payments', 'action'=> 'Excel Download'),
            array('id' => 91, 'screen_name' => 'Make Payments Pickup Wise', 'action'=> 'Excel Download'),
            array('id' => 92, 'screen_name' => 'Retail Make Payments', 'action'=> 'Excel Download'),
            array('id' => 93, 'screen_name' => 'Retail Done Payments', 'action'=> 'Excel Download'),
            array('id' => 94, 'screen_name' => 'Pending Invoices', 'action'=> 'Excel Download'),
            array('id' => 95, 'screen_name' => 'Received Invoices', 'action'=> 'Excel Download'),
            array('id' => 96, 'screen_name' => 'Outstanding SDN', 'action'=> 'Excel Download'),
            array('id' => 97, 'screen_name' => 'Outstanding Shipments', 'action'=> 'Excel Download'),
            array('id' => 98, 'screen_name' => 'Outstanding Walk-In Shipments', 'action'=> 'Excel Download'),
            array('id' => 99, 'screen_name' => 'Petty Cash Statements', 'action'=> 'Excel Download'),
            array('id' => 100, 'screen_name' => 'Approved Petty Cash Statements', 'action'=> 'Excel Download'),
            array('id' => 101, 'screen_name' => 'Rejected Petty Cash Statements', 'action'=> 'Excel Download'),
            array('id' => 102, 'screen_name' => 'Launched/Re-Open Requests', 'action'=> 'Excel Download'),
            array('id' => 103, 'screen_name' => 'Consignee Info Requests', 'action'=> 'Excel Download'),
            array('id' => 104, 'screen_name' => 'Order Management', 'action'=> 'Excel Download'),
            array('id' => 105, 'screen_name' => 'Month Closing-Pending', 'action'=> 'Excel Download'),
            array('id' => 106, 'screen_name' => 'Month Closing-Resolved', 'action'=> 'Excel Download'),
            array('id' => 107, 'screen_name' => 'Misrouted History', 'action'=> 'Excel Download'),
            array('id' => 108, 'screen_name' => 'Lost Shipments', 'action'=> 'Excel Download'),
            array('id' => 109, 'screen_name' => 'Intercept Rebook History', 'action'=> 'Excel Download'),
            array('id' => 110, 'screen_name' => 'Sales Person Targets', 'action'=> 'Excel Download'),
            array('id' => 111, 'screen_name' => 'Sales Person Targets History', 'action'=> 'Excel Download'),
            array('id' => 112, 'screen_name' => 'Trax Directory', 'action'=> 'Excel Download'),
            array('id' => 113, 'screen_name' => 'International Tracking Upload', 'action'=> 'Excel Download'),
            array('id' => 114, 'screen_name' => 'Active Employees List', 'action'=> 'Excel Download'),
            array('id' => 115, 'screen_name' => 'Overall Commission Dashboard', 'action'=> 'Excel Download'),
            array('id' => 116, 'screen_name' => 'Employee Attendance', 'action'=> 'Excel Download'),
            array('id' => 117, 'screen_name' => 'Employee Directory', 'action'=> 'Excel Download'),
            array('id' => 118, 'screen_name' => 'Permanent Riders', 'action'=> 'Excel Download'),
            array('id' => 119, 'screen_name' => 'Incentive Riders', 'action'=> 'Excel Download'),
            array('id' => 120, 'screen_name' => 'Riders Pending Request', 'action'=> 'Excel Download'),


            array('id' => 121, 'screen_name' => 'Booked VS Received VS Delivered VS Returned', 'action'=> 'View'),
            array('id' => 122, 'screen_name' => 'Booked VS Received VS Delivered VS Returned', 'action'=> 'Excel Download'),
            array('id' => 123, 'screen_name' => 'Pickup Notes Report', 'action'=> 'View'),
            array('id' => 124, 'screen_name' => 'Pickup Notes Report', 'action'=> 'Excel Download'),
            array('id' => 125, 'screen_name' => 'Multiple IBAN Number Change Report', 'action'=> 'View'),
            array('id' => 126, 'screen_name' => 'Multiple IBAN Number Change Report', 'action'=> 'Excel Download'),
            array('id' => 127, 'screen_name' => 'Cargo Received Report', 'action'=> 'View'),
            array('id' => 128, 'screen_name' => 'Cargo Received Report', 'action'=> 'Excel Download'),
            array('id' => 129, 'screen_name' => 'Completed Delivery Notes Report', 'action'=> 'View'),
            array('id' => 130, 'screen_name' => 'Completed Delivery Notes Report', 'action'=> 'Excel Download'),
            array('id' => 131, 'screen_name' => 'Return Notes Report', 'action'=> 'View'),
            array('id' => 132, 'screen_name' => 'Return Notes Report', 'action'=> 'Excel Download'),
            array('id' => 133, 'screen_name' => 'Outstanding Shipments Report', 'action'=> 'View'),
            array('id' => 134, 'screen_name' => 'Outstanding Shipments Report', 'action'=> 'Excel Download'),
            array('id' => 135, 'screen_name' => 'Lead Time Report', 'action'=> 'View'),
            array('id' => 136, 'screen_name' => 'Lead Time Report', 'action'=> 'Excel Download'),
            array('id' => 137, 'screen_name' => 'Quality of Service Report', 'action'=> 'View'),
            array('id' => 138, 'screen_name' => 'Quality of Service Report', 'action'=> 'Excel Download'),
            array('id' => 139, 'screen_name' => 'Quality Assurance Report', 'action'=> 'View'),
            array('id' => 140, 'screen_name' => 'Quality Assurance Report', 'action'=> 'Excel Download'),
            array('id' => 141, 'screen_name' => 'Weight QC', 'action'=> 'View'),
            array('id' => 142, 'screen_name' => 'Weight QC', 'action'=> 'Excel Download'),
            array('id' => 143, 'screen_name' => 'Customer Retention Report', 'action'=> 'View'),
            array('id' => 144, 'screen_name' => 'Customer Retention Report', 'action'=> 'Excel Download'),
            array('id' => 145, 'screen_name' => 'Daily Pickup & Sales Report', 'action'=> 'View'),
            array('id' => 146, 'screen_name' => 'Daily Pickup & Sales Report', 'action'=> 'Excel Download'),
            array('id' => 147, 'screen_name' => 'Monthwise Customer Sales Report', 'action'=> 'View'),
            array('id' => 148, 'screen_name' => 'Monthwise Customer Sales Report', 'action'=> 'Excel Download'),
            array('id' => 149, 'screen_name' => 'Overall Sales Report', 'action'=> 'View'),
            array('id' => 150, 'screen_name' => 'Overall Sales Report', 'action'=> 'Excel Download'),
            array('id' => 151, 'screen_name' => 'Sales Person Performance Report', 'action'=> 'View'),
            array('id' => 152, 'screen_name' => 'Sales Person Performance Report', 'action'=> 'Excel Download'),
            array('id' => 153, 'screen_name' => 'Negative Balance Customers Report', 'action'=> 'View'),
            array('id' => 154, 'screen_name' => 'Negative Balance Customers Report', 'action'=> 'Excel Download'),
            array('id' => 155, 'screen_name' => 'Petty Cash Statements Report', 'action'=> 'View'),
            array('id' => 156, 'screen_name' => 'Petty Cash Statements Report', 'action'=> 'Excel Download'),
            array('id' => 157, 'screen_name' => 'Call Verification Report', 'action'=> 'View'),
            array('id' => 158, 'screen_name' => 'Call Verification Report', 'action'=> 'Excel Download'),
            array('id' => 159, 'screen_name' => 'Fake Statuses Report', 'action'=> 'View'),
            array('id' => 160, 'screen_name' => 'Fake Statuses Report', 'action'=> 'Excel Download'),
            array('id' => 161, 'screen_name' => 'Debriefing Report', 'action'=> 'View'),
            array('id' => 162, 'screen_name' => 'Debriefing Report', 'action'=> 'Excel Download'),
            array('id' => 163, 'screen_name' => 'Cargo Returns Shipment Report', 'action'=> 'View'),
            array('id' => 164, 'screen_name' => 'Cargo Returns Shipment Report', 'action'=> 'Excel Download'),
            array('id' => 165, 'screen_name' => 'Return To Re-Attempt Ratio Report', 'action'=> 'View'),
            array('id' => 166, 'screen_name' => 'Return To Re-Attempt Ratio Report', 'action'=> 'Excel Download'),
            array('id' => 167, 'screen_name' => 'Multiple Payments Report', 'action'=> 'View'),
            array('id' => 168, 'screen_name' => 'Multiple Payments Report', 'action'=> 'Excel Download'),
            array('id' => 169, 'screen_name' => 'Revenue Report', 'action'=> 'View'),
            array('id' => 170, 'screen_name' => 'Revenue Report', 'action'=> 'Excel Download'),
            array('id' => 171, 'screen_name' => 'GST Report', 'action'=> 'View'),
            array('id' => 172, 'screen_name' => 'GST Report', 'action'=> 'Excel Download'),
            array('id' => 173, 'screen_name' => 'CRM Report', 'action'=> 'View'),
            array('id' => 174, 'screen_name' => 'CRM Report', 'action'=> 'Excel Download'),
            array('id' => 175, 'screen_name' => 'Summary Report', 'action'=> 'View'),
            array('id' => 176, 'screen_name' => 'Summary Report', 'action'=> 'Excel Download'),
            array('id' => 177, 'screen_name' => 'Account Activation Report', 'action'=> 'View'),
            array('id' => 178, 'screen_name' => 'Account Activation Report', 'action'=> 'Excel Download'),
            array('id' => 179, 'screen_name' => 'Adjustments Report', 'action'=> 'View'),
            array('id' => 180, 'screen_name' => 'Adjustments Report', 'action'=> 'Excel Download'),
            array('id' => 181, 'screen_name' => 'Station Deposit Notes Report', 'action'=> 'View'),
            array('id' => 182, 'screen_name' => 'Station Deposit Notes Report', 'action'=> 'Excel Download'),
            array('id' => 183, 'screen_name' => 'Rates Edit Report', 'action'=> 'View'),
            array('id' => 184, 'screen_name' => 'Rates Edit Report', 'action'=> 'Excel Download'),
            array('id' => 185, 'screen_name' => 'Shipper Bank History Report', 'action'=> 'View'),
            array('id' => 186, 'screen_name' => 'Shipper Bank History Report', 'action'=> 'Excel Download'),
            array('id' => 187, 'screen_name' => 'Consignee Details History Report', 'action'=> 'View'),
            array('id' => 188, 'screen_name' => 'Consignee Details History Report', 'action'=> 'Excel Download'),
            array('id' => 189, 'screen_name' => 'Booked And Cancelled Shipments Report', 'action'=> 'View'),
            array('id' => 190, 'screen_name' => 'Booked And Cancelled Shipments Report', 'action'=> 'Excel Download'),
            array('id' => 191, 'screen_name' => 'Fake Statuses Shipments Report', 'action'=> 'View'),
            array('id' => 192, 'screen_name' => 'Fake Statuses Shipments Report', 'action'=> 'Excel Download'),
            array('id' => 193, 'screen_name' => 'Daily Visit Report', 'action'=> 'View'),
            array('id' => 194, 'screen_name' => 'Daily Visit Report', 'action'=> 'Excel Download'),
            array('id' => 195, 'screen_name' => 'Delivered Shipment Report (Rider Wise)', 'action'=> 'View'),
            array('id' => 196, 'screen_name' => 'Delivered Shipment Report (Rider Wise)', 'action'=> 'Excel Download'),
            array('id' => 197, 'screen_name' => 'Route Distribution Summary Report', 'action'=> 'View'),
            array('id' => 198, 'screen_name' => 'Route Distribution Summary Report', 'action'=> 'Excel Download'),
            array('id' => 199, 'screen_name' => 'Arrived At Destination VS Out For Delivery VS Receive Report', 'action'=> 'View'),
            array('id' => 200, 'screen_name' => 'Arrived At Destination VS Out For Delivery VS Receive Report', 'action'=> 'Excel Download'),
            array('id' => 201, 'screen_name' => 'Account Reconciliation Report', 'action'=> 'View'),
            array('id' => 202, 'screen_name' => 'Account Reconciliation Report', 'action'=> 'Excel Download'),
            array('id' => 203, 'screen_name' => 'Cargo Short Received Shipments', 'action'=> 'View'),
            array('id' => 204, 'screen_name' => 'Cargo Short Received Shipments', 'action'=> 'Excel Download'),
            array('id' => 205, 'screen_name' => 'Last Mile Status Report', 'action'=> 'View'),
            array('id' => 206, 'screen_name' => 'Last Mile Status Report', 'action'=> 'Excel Download'),
            array('id' => 207, 'screen_name' => 'Pickup Report', 'action'=> 'View'),
            array('id' => 208, 'screen_name' => 'Pickup Report', 'action'=> 'Excel Download'),
            array('id' => 209, 'screen_name' => 'Completed Aging Report', 'action'=> 'View'),
            array('id' => 210, 'screen_name' => 'Completed Aging Report', 'action'=> 'Excel Download'),
            array('id' => 211, 'screen_name' => 'Pending Cash Collection Report', 'action'=> 'View'),
            array('id' => 212, 'screen_name' => 'Pending Cash Collection Report', 'action'=> 'Excel Download'),
            array('id' => 213, 'screen_name' => 'Station Recovery Report', 'action'=> 'View'),
            array('id' => 214, 'screen_name' => 'Station Recovery Report', 'action'=> 'Excel Download'),
            array('id' => 215, 'screen_name' => 'Not Attempted Aging Report', 'action'=> 'View'),
            array('id' => 216, 'screen_name' => 'Not Attempted Aging Report', 'action'=> 'Excel Download'),
            array('id' => 217, 'screen_name' => 'Daily and Monthly Adjustments Report', 'action'=> 'View'),
            array('id' => 218, 'screen_name' => 'Daily and Monthly Adjustments Report', 'action'=> 'Excel Download'),
            array('id' => 219, 'screen_name' => 'Petty Cash Expense Summary Report', 'action'=> 'View'),
            array('id' => 220, 'screen_name' => 'Petty Cash Expense Summary Report', 'action'=> 'Excel Download'),
            array('id' => 221, 'screen_name' => 'App Efficiency Report', 'action'=> 'View'),
            array('id' => 222, 'screen_name' => 'App Efficiency Report', 'action'=> 'Excel Download'),
            array('id' => 223, 'screen_name' => 'Month Closing Report-Individual', 'action'=> 'View'),
            array('id' => 224, 'screen_name' => 'Month Closing Report-Individual', 'action'=> 'Excel Download'),
            array('id' => 225, 'screen_name' => 'Month Closing Report-Pivot', 'action'=> 'View'),
            array('id' => 226, 'screen_name' => 'Month Closing Report-Pivot', 'action'=> 'Excel Download'),
            array('id' => 227, 'screen_name' => 'Last Mile App Report', 'action'=> 'View'),
            array('id' => 228, 'screen_name' => 'Last Mile App Report', 'action'=> 'Excel Download'),
            array('id' => 229, 'screen_name' => 'Update Role', 'action'=> 'View'),
            array('id' => 230, 'screen_name' => 'Update Role', 'action'=> 'Permission Updated'),
            array('id' => 231, 'screen_name' => 'Update User', 'action'=> 'View'),
            array('id' => 232, 'screen_name' => 'Update User', 'action'=> 'Role Updated'),
            array('id' => 394, 'screen_name' => 'Incidence Monitoring', 'action'=> 'View'),
            array('id' => 395, 'screen_name' => 'Incidence Monitoring-View Details', 'action'=> 'View'),
            array('id' => 412, 'screen_name' => 'CCD Booking', 'action'=> 'View'),

        ));
    }
}
