<?php

use Illuminate\Database\Seeder;

class AddActivityTrailActionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('activity_trail_actions')->truncate();
        DB::table('activity_trail_actions')->insert(array(
            array('id' => 1, 'screen_name' => 'Pending Accounts List', 'action'=> 'View'),
            
            array('id' => 2, 'screen_name' => 'Active Account List', 'action'=> 'View'),
            array('id' => 3, 'screen_name' => 'Retail Accounts', 'action'=> 'View'),
            array('id' => 4, 'screen_name' => 'Leads Management', 'action'=> 'View'),
            array('id' => 5, 'screen_name' => 'Shipment Pieces List', 'action'=> 'View'),
            array('id' => 6, 'screen_name' => 'Pending Pickups', 'action'=> 'View'),
            array('id' => 7, 'screen_name' => 'Rider Pickups', 'action'=> 'View'),
            array('id' => 8, 'screen_name' => 'Rider Pickup Action Logs', 'action'=> 'View'),
            array('id' => 9, 'screen_name' => 'Rider Receiving', 'action'=> 'View'),
            array('id' => 10, 'screen_name' => 'Pickup Routes', 'action'=> 'View'),
            array('id' => 11, 'screen_name' => 'Supply Chain Management', 'action'=> 'View'),
            array('id' => 12, 'screen_name' => 'Bag(s) History', 'action'=> 'View'),
            array('id' => 13, 'screen_name' => 'Master Cargo In Transit', 'action'=> 'View'),
            array('id' => 14, 'screen_name' => 'Pending Bags for Receiving', 'action'=> 'View'),
            array('id' => 15, 'screen_name' => 'Master Cargo Received', 'action'=> 'View'),
            array('id' => 16, 'screen_name' => 'Master Cargo History', 'action'=> 'View'),
            array('id' => 17, 'screen_name' => 'Runners On Route', 'action'=> 'View'),
            array('id' => 18, 'screen_name' => 'Supply Chain Shipment On Hold History', 'action'=> 'View'),
            array('id' => 19, 'screen_name' => 'Pending Deliveries', 'action'=> 'View'),
            array('id' => 20, 'screen_name' => 'Receive Deliveries', 'action'=> 'View'),
            array('id' => 21, 'screen_name' => 'Pending Cash Collection COD', 'action'=> 'View'),
            array('id' => 22, 'screen_name' => 'Pending Cash Collection Retail', 'action'=> 'View'),
            array('id' => 23, 'screen_name' => 'Completed Deliveries COD', 'action'=> 'View'),
            array('id' => 24, 'screen_name' => 'Completed Deliveries Retail', 'action'=> 'View'),
            array('id' => 25, 'screen_name' => 'Station Deposit Notes', 'action'=> 'View'),
            array('id' => 26, 'screen_name' => 'Return Confirmation Pending Shipments', 'action'=> 'View'),
            array('id' => 27, 'screen_name' => 'Return Confirmed Shipments', 'action'=> 'View'),
            array('id' => 28, 'screen_name' => 'Return Deliveries History', 'action'=> 'View'),
            array('id' => 29, 'screen_name' => 'Make Payments', 'action'=> 'View'),
            array('id' => 30, 'screen_name' => 'Done Payments', 'action'=> 'View'),
            array('id' => 31, 'screen_name' => 'Make Payments Pickup Wise', 'action'=> 'View'),
            array('id' => 32, 'screen_name' => 'Retail Make Payments', 'action'=> 'View'),
            array('id' => 33, 'screen_name' => 'Retail Done Payments', 'action'=> 'View'),
            array('id' => 34, 'screen_name' => 'Pending Invoices', 'action'=> 'View'),
            array('id' => 35, 'screen_name' => 'Received Invoices', 'action'=> 'View'),
            array('id' => 36, 'screen_name' => 'Outstanding SDN', 'action'=> 'View'),
            array('id' => 37, 'screen_name' => 'Outstanding Shipments', 'action'=> 'View'),
            array('id' => 38, 'screen_name' => 'Outstanding Walk-In Shipments', 'action'=> 'View'),
            array('id' => 39, 'screen_name' => 'Petty Cash Statements', 'action'=> 'View'),
            array('id' => 40, 'screen_name' => 'Approved Petty Cash Statements', 'action'=> 'View'),
            array('id' => 41, 'screen_name' => 'Rejected Petty Cash Statements', 'action'=> 'View'),
            array('id' => 42, 'screen_name' => 'Launched/Re-Open Requests', 'action'=> 'View'),
            array('id' => 43, 'screen_name' => 'Consignee Info Requests', 'action'=> 'View'),
            array('id' => 44, 'screen_name' => 'Order Management', 'action'=> 'View'),
            array('id' => 45, 'screen_name' => 'Month Closing-Pending', 'action'=> 'View'),
            array('id' => 46, 'screen_name' => 'Month Closing-Resolved', 'action'=> 'View'),
            array('id' => 47, 'screen_name' => 'Misrouted History', 'action'=> 'View'),
            array('id' => 48, 'screen_name' => 'Lost Shipments', 'action'=> 'View'),
            array('id' => 49, 'screen_name' => 'Intercept Rebook History', 'action'=> 'View'),
            array('id' => 50, 'screen_name' => 'Sales Person Targets', 'action'=> 'View'),
            array('id' => 51, 'screen_name' => 'Sales Person Targets History', 'action'=> 'View'),
            array('id' => 52, 'screen_name' => 'Trax Directory', 'action'=> 'View'),
            array('id' => 53, 'screen_name' => 'International Tracking Upload', 'action'=> 'View'),
            array('id' => 54, 'screen_name' => 'Active Employees List', 'action'=> 'View'),
            array('id' => 55, 'screen_name' => 'Overall Commission Dashboard', 'action'=> 'View'),
            array('id' => 56, 'screen_name' => 'Employee Attendance', 'action'=> 'View'),
            array('id' => 57, 'screen_name' => 'Employee Directory', 'action'=> 'View'),
            array('id' => 58, 'screen_name' => 'Permanent Riders', 'action'=> 'View'),
            array('id' => 59, 'screen_name' => 'Incentive Riders', 'action'=> 'View'),
            array('id' => 60, 'screen_name' => 'Riders Pending Request', 'action'=> 'View'),
            array('id' => 61, 'screen_name' => 'Pending Accounts List', 'action'=> 'Excel Download'),
            array('id' => 62, 'screen_name' => 'Active Account List', 'action'=> 'Excel Download'),
            array('id' => 63, 'screen_name' => 'Retail Accounts', 'action'=> 'Excel Download'),
            array('id' => 64, 'screen_name' => 'Leads Management', 'action'=> 'Excel Download'),
            array('id' => 65, 'screen_name' => 'Shipment Pieces List', 'action'=> 'Excel Download'),
            array('id' => 66, 'screen_name' => 'Pending Pickups', 'action'=> 'Excel Download'),
            array('id' => 67, 'screen_name' => 'Rider Pickups', 'action'=> 'Excel Download'),
            array('id' => 68, 'screen_name' => 'Rider Pickup Action Logs', 'action'=> 'Excel Download'),
            array('id' => 69, 'screen_name' => 'Rider Receiving', 'action'=> 'Excel Download'),
            array('id' => 70, 'screen_name' => 'Pickup Routes', 'action'=> 'Excel Download'),
            array('id' => 71, 'screen_name' => 'Supply Chain Management', 'action'=> 'Excel Download'),
            array('id' => 72, 'screen_name' => 'Bag(s) History', 'action'=> 'Excel Download'),
            array('id' => 73, 'screen_name' => 'Master Cargo In Transit', 'action'=> 'Excel Download'),
            array('id' => 74, 'screen_name' => 'Pending Bags for Receiving', 'action'=> 'Excel Download'),
            array('id' => 75, 'screen_name' => 'Master Cargo Received', 'action'=> 'Excel Download'),
            array('id' => 76, 'screen_name' => 'Master Cargo History', 'action'=> 'Excel Download'),
            array('id' => 77, 'screen_name' => 'Runners On Route', 'action'=> 'Excel Download'),
            array('id' => 78, 'screen_name' => 'Supply Chain Shipment On Hold History', 'action'=> 'Excel Download'),
            array('id' => 79, 'screen_name' => 'Pending Deliveries', 'action'=> 'Excel Download'),
            array('id' => 80, 'screen_name' => 'Receive Deliveries', 'action'=> 'Excel Download'),
            array('id' => 81, 'screen_name' => 'Pending Cash Collection COD', 'action'=> 'Excel Download'),
            array('id' => 82, 'screen_name' => 'Pending Cash Collection Retail', 'action'=> 'Excel Download'),
            array('id' => 83, 'screen_name' => 'Completed Deliveries COD', 'action'=> 'Excel Download'),
            array('id' => 84, 'screen_name' => 'Completed Deliveries Retail', 'action'=> 'Excel Download'),
            array('id' => 85, 'screen_name' => 'Station Deposit Notes', 'action'=> 'Excel Download'),
            array('id' => 86, 'screen_name' => 'Return Confirmation Pending Shipments', 'action'=> 'Excel Download'),
            array('id' => 87, 'screen_name' => 'Return Confirmed Shipments', 'action'=> 'Excel Download'),
            array('id' => 88, 'screen_name' => 'Return Deliveries History', 'action'=> 'Excel Download'),
            array('id' => 89, 'screen_name' => 'Make Payments', 'action'=> 'Excel Download'),
            array('id' => 90, 'screen_name' => 'Done Payments', 'action'=> 'Excel Download'),
            array('id' => 91, 'screen_name' => 'Make Payments Pickup Wise', 'action'=> 'Excel Download'),
            array('id' => 92, 'screen_name' => 'Retail Make Payments', 'action'=> 'Excel Download'),
            array('id' => 93, 'screen_name' => 'Retail Done Payments', 'action'=> 'Excel Download'),
            array('id' => 94, 'screen_name' => 'Pending Invoices', 'action'=> 'Excel Download'),
            array('id' => 95, 'screen_name' => 'Received Invoices', 'action'=> 'Excel Download'),
            array('id' => 96, 'screen_name' => 'Outstanding SDN', 'action'=> 'Excel Download'),
            array('id' => 97, 'screen_name' => 'Outstanding Shipments', 'action'=> 'Excel Download'),
            array('id' => 98, 'screen_name' => 'Outstanding Walk-In Shipments', 'action'=> 'Excel Download'),
            array('id' => 99, 'screen_name' => 'Petty Cash Statements', 'action'=> 'Excel Download'),
            array('id' => 100, 'screen_name' => 'Approved Petty Cash Statements', 'action'=> 'Excel Download'),
            array('id' => 101, 'screen_name' => 'Rejected Petty Cash Statements', 'action'=> 'Excel Download'),
            array('id' => 102, 'screen_name' => 'Launched/Re-Open Requests', 'action'=> 'Excel Download'),
            array('id' => 103, 'screen_name' => 'Consignee Info Requests', 'action'=> 'Excel Download'),
            array('id' => 104, 'screen_name' => 'Order Management', 'action'=> 'Excel Download'),
            array('id' => 105, 'screen_name' => 'Month Closing-Pending', 'action'=> 'Excel Download'),
            array('id' => 106, 'screen_name' => 'Month Closing-Resolved', 'action'=> 'Excel Download'),
            array('id' => 107, 'screen_name' => 'Misrouted History', 'action'=> 'Excel Download'),
            array('id' => 108, 'screen_name' => 'Lost Shipments', 'action'=> 'Excel Download'),
            array('id' => 109, 'screen_name' => 'Intercept Rebook History', 'action'=> 'Excel Download'),
            array('id' => 110, 'screen_name' => 'Sales Person Targets', 'action'=> 'Excel Download'),
            array('id' => 111, 'screen_name' => 'Sales Person Targets History', 'action'=> 'Excel Download'),
            array('id' => 112, 'screen_name' => 'Trax Directory', 'action'=> 'Excel Download'),
            array('id' => 113, 'screen_name' => 'International Tracking Upload', 'action'=> 'Excel Download'),
            array('id' => 114, 'screen_name' => 'Active Employees List', 'action'=> 'Excel Download'),
            array('id' => 115, 'screen_name' => 'Overall Commission Dashboard', 'action'=> 'Excel Download'),
            array('id' => 116, 'screen_name' => 'Employee Attendance', 'action'=> 'Excel Download'),
            array('id' => 117, 'screen_name' => 'Employee Directory', 'action'=> 'Excel Download'),
            array('id' => 118, 'screen_name' => 'Permanent Riders', 'action'=> 'Excel Download'),
            array('id' => 119, 'screen_name' => 'Incentive Riders', 'action'=> 'Excel Download'),
            array('id' => 120, 'screen_name' => 'Riders Pending Request', 'action'=> 'Excel Download'),
        ));
    }
}
