<?php

use Illuminate\Database\Seeder;

class AdminSearchSonicSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $timestamp = \Carbon\Carbon::now()->format('Y-m-d H:i:s');
        DB::table('admins_screen_list')->insert(array(
            array('id' => 1, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Disputes', 'url'=>'admin.dispute.index', 'permission_id' => 1),
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Daily Visit Form', 'url'=>'admin.daily_visit.index', 'permission_id' => 265),
            array('id' => 3, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Pending Pickups', 'url'=>'admin.pickups.index', 'permission_id' => 17),
            array('id' => 4, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Receive Pickups', 'url'=>'admin.receive.index', 'permission_id' => 23),
            array('id' => 5, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Merged Accounts', 'url'=>'admin.accounts.sister_accounts.merged_accounts.index', 'permission_id' => 241),
            array('id' => 6, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Edit Sister Accounts', 'url'=>'admin.accounts.sister_accounts.edit', 'permission_id' => 242),
            array('id' => 7, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Receiving Sheet History', 'url'=>'admin.shipment.receiving_sheet.index', 'permission_id' => 364),
            array('id' => 8, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Receive Pickups', 'url'=>'admin.pickups.receive.index', 'permission_id' => 23),
            array('id' => 9, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Receive Pickups', 'url'=>'admin.pickups.receive.index', 'permission_id' => 24),
            array('id' => 10, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Booked VS Received VS Delivered VS Returned', 'url'=>'admin.pickups.bookedvsreceived.index', 'permission_id' => 113),
            array('id' => 11, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Pickups History', 'url'=>'admin.pickups.history.index', 'permission_id' => 123),
            array('id' => 12, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Pending Pickups', 'url'=>'admin.v2_pickups.pending', 'permission_id' => 17),
            array('id' => 13, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Individual Arrival of Shipments', 'url'=>'admin.v2_pickups.arrival_individual_weight', 'permission_id' => 24),
            array('id' => 14, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Bulk Arrival (Without Weight)', 'url'=>'admin.v2_pickups.arrival_single_weight', 'permission_id' => 24),
            array('id' => 15, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Rider Pickups', 'url'=>'admin.v2_pickups.rider_pickups', 'permission_id' => 271),
            array('id' => 16, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Rider Pickup Action Logs', 'url'=>'admin.v2_pickups.action_log.index', 'permission_id' => 272),
            array('id' => 17, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Rider Receiving', 'url'=>'admin.v2_pickups.receiving_sheet', 'permission_id' => 366),
            array('id' => 18, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Pending Shipments for Cargo', 'url'=>'admin.cargo.pending', 'permission_id' => 25),
            array('id' => 19, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Draft Cargo', 'url'=>'admin.cargo.draft', 'permission_id' => 26),
            array('id' => 20, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Create Cargo', 'url'=>'admin.cargo.create', 'permission_id' => 26),
            array('id' => 21, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Cargo in Transit', 'url'=>'admin.cargo.in_transit', 'permission_id' => 27),
            array('id' => 22, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Cargo Received Report', 'url'=>'admin.cargo.receive', 'permission_id' => 31),
            array('id' => 23, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Cargo History', 'url'=>'admin.cargo.history', 'permission_id' => 124),
            array('id' => 24, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Mapping', 'url'=>'admin.cargo.mapping', 'permission_id' => 198),
            array('id' => 25, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Quick Receive Cargo', 'url'=>'admin.cargo.quick_receive', 'permission_id' => 31),
            array('id' => 26, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Quick Receive List', 'url'=>'admin.cargo.quick_receive_index', 'permission_id' => 31),
            array('id' => 27, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Supply Chain Management', 'url'=>'admin.supply_chain.index', 'permission_id' => 376),
            array('id' => 28, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Pending Shipments for Bag', 'url'=>'admin.master_cargo.bag.pending', 'permission_id' => 25),
            array('id' => 29, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Create Bag', 'url'=>'admin.master_cargo.bag.create', 'permission_id' => 26),
            array('id' => 30, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Master Cargo In Transit', 'url'=>'admin.master_cargo.in_transit', 'permission_id' => 27),
            array('id' => 31, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Receive Master Cargo', 'url'=>'admin.master_cargo.receive', 'permission_id' => 31),
            array('id' => 32, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Master Cargo History', 'url'=>'admin.master_cargo.history', 'permission_id' => 124),
            array('id' => 33, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Master Cargo Received', 'url'=>'admin.master_cargo.received', 'permission_id' => 124),
            array('id' => 34, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Quick Receive Master Cargo', 'url'=>'admin.master_cargo.quick_receive', 'permission_id' => 31),
             array('id' => 35, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Quick Receive Master Cargo List', 'url'=>'admin.master_cargo.quick_receive_index', 'permission_id' => 31),
             array('id' => 36, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Same-Day Delivery', 'url'=>'admin.sameday.index', 'permission_id' => 32),
             array('id' => 37, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Pending Deliveries', 'url'=>'admin.delivery.pending.index', 'permission_id' => 33),
             array('id' => 38, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Create Delivery Note', 'url'=>'admin.delivery.note.index', 'permission_id' => 35),
             array('id' => 39, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Receive Deliveries', 'url'=>'admin.delivery.receive.index', 'permission_id' => 36),
             array('id' => 40, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Completed Deliveries', 'url'=>'admin.delivery.complete.index', 'permission_id' => 40),
             array('id' => 41, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Station Deposit Notes', 'url'=>'admin.delivery.sdn.index', 'permission_id' => 42),
             array('id' => 42, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Pending Cash Collection', 'url'=>'admin.delivery.complete.pending_cash_collection', 'permission_id' => 105),
             array('id' => 43, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Misrouted Shipments', 'url'=>'admin.delivery.misroute.index', 'permission_id' => 107),
             array('id' => 44, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Update Misrouted', 'url'=>'admin.delivery.misroute.update', 'permission_id' => 108),
             array('id' => 45, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Misrouted History', 'url'=>'admin.delivery.misroute.history', 'permission_id' => 119),
             array('id' => 46, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Delivery Note History
', 'url'=>'admin.delivery.history.index', 'permission_id' => 125),
             array('id' => 47, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Lost Shipments', 'url'=>'admin.lost.index', 'permission_id' => 127),
             array('id' => 48, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Add Lost Shipments', 'url'=>'admin.lost.add_shipments', 'permission_id' => 130),
             array('id' => 49, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Intercept Requests', 'url'=>'admin.delivery.intercept.index', 'permission_id' => 193),
             array('id' => 50, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Intercept Rebook History', 'url'=>'admin.delivery.intercept.history', 'permission_id' => 196),
             array('id' => 51, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Remove Fake Status', 'url'=>'admin.delivery.fake_status.index', 'permission_id' => 203),
             array('id' => 52, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Replacement Not Collected', 'url'=>'admin.delivery.replacement.not_collected', 'permission_id' => 206),
             array('id' => 53, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Replacement Collected', 'url'=>'admin.delivery.replacement.collected', 'permission_id' => 207),
             array('id' => 54, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Replacement To Regular Log', 'url'=>'admin.delivery.replacement.replacement_to_regular_logs', 'permission_id' => 208),
             array('id' => 55, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Log Fake Statuses', 'url'=>'admin.fake_statuses.index', 'permission_id' => 262),
             array('id' => 56, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Return Confirmation Pending Shipments', 'url'=>'admin.return.index', 'permission_id' => 44),
             array('id' => 57, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Create Return Note', 'url'=>'admin.return.create', 'permission_id' => 48),
             array('id' => 58, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Receive Return Deliveries', 'url'=>'admin.return.receive', 'permission_id' => 49),
             array('id' => 59, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Return Deliveries History', 'url'=>'admin.return.history', 'permission_id' => 126),
             array('id' => 60, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Return For CX & Sales', 'url'=>'admin.return.cx_sales', 'permission_id' => 266),
             array('id' => 61, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Outstanding SDN', 'url'=>'admin.finance.outstanding_sdn', 'permission_id' => 52),
             array('id' => 62, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Outstanding Shipments', 'url'=>'admin.finance.outstanding_shipments', 'permission_id' => 54),
             array('id' => 63, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Change Shipment Amount', 'url'=>'admin.finance.change_shipment_amount', 'permission_id' => 57),
             array('id' => 64, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Change Shipment Weight', 'url'=>'admin.finance.change_shipment_weight', 'permission_id' => 134),
             array('id' => 65, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Add Shipment Adjustment', 'url'=>'admin.finance.add_shipment_adjustment', 'permission_id' => 136),
             array('id' => 66, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Make Payments', 'url'=>'admin.finance.make_payments', 'permission_id' => 59),
             array('id' => 67, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Done Payments', 'url'=>'admin.finance.done_payments', 'permission_id' => 61),
             array('id' => 68, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Pending Invoices', 'url'=>'admin.finance.invoices', 'permission_id' => 120),
             array('id' => 69, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Outstanding Walk-In Shipments', 'url'=>'admin.finance.outstanding_walk_in_shipments', 'permission_id' => 167),
             array('id' => 70, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Make Payments Pickup Wise', 'url'=>'admin.finance.make_payments_pickup_wise', 'permission_id' => 396),
             array('id' => 71, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Make Petty Cash Statement', 'url'=>'admin.petty_cash.make', 'permission_id' => 145),
             array('id' => 72, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Petty Cash Statements', 'url'=>'admin.petty_cash.statements', 'permission_id' => 146),
             array('id' => 73, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Approved Petty Cash Statements', 'url'=>'admin.petty_cash.approved', 'permission_id' => 147),
             array('id' => 74, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Rejected Petty Cash Statements', 'url'=>'admin.petty_cash.rejected', 'permission_id' => 243),
             array('id' => 75, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Month Closing Shipments', 'url'=>'admin.month_closing.index', 'permission_id' => 141),
             array('id' => 76, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Pickup Notes Report', 'url'=>'admin.reports.pickup_notes_report', 'permission_id' => 64),
             array('id' => 77, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Cargo Received Report', 'url'=>'admin.reports.cargo_received_report', 'permission_id' => 65),
             array('id' => 78, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Completed Delivery Notes Report', 'url'=>'admin.reports.completed_delivery_notes_report', 'permission_id' => 66),
             array('id' => 79, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Return Notes Report', 'url'=>'admin.reports.return_notes_report', 'permission_id' => 67),
             array('id' => 80, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Outstanding Shipments Report', 'url'=>'admin.reports.outstanding_shipments_report', 'permission_id' => 68),
             array('id' => 81, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Lead Time Report', 'url'=>'admin.reports.lead_time_report', 'permission_id' => 69),
             array('id' => 82, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Quality of Service Report', 'url'=>'admin.reports.qsr_report', 'permission_id' => 70),
             array('id' => 83, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Quality Assurance Report', 'url'=>'admin.reports.qa_report', 'permission_id' => 71),
             array('id' => 84, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Daily Pickup & Sales Report', 'url'=>'admin.reports.daily_pickup_sales_report', 'permission_id' => 73),
             array('id' => 85, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Monthwise Customer Sales Report', 'url'=>'admin.reports.customer_sales_report', 'permission_id' => 74),
             array('id' => 86, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Overall Sales Report', 'url'=>'admin.reports.overall_sales', 'permission_id' => 75),
             array('id' => 87, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Sales Person Performance Report', 'url'=>'admin.reports.sales_person_performance_report', 'permission_id' => 138),
             array('id' => 88, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Negative Balance Customers Report', 'url'=>'admin.reports.invoice_for_negative_balance_customers', 'permission_id' => 148),
             array('id' => 89, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Call Verification Report', 'url'=>'admin.reports.call_verification_report', 'permission_id' => 153),
             array('id' => 90, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Petty Cash Statements Report', 'url'=>'admin.reports.petty_cash_statement', 'permission_id' => 156),
             array('id' => 91, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Fake Statuses Report
', 'url'=>'admin.reports.fake_statuses_report', 'permission_id' => 169),
        array('id' => 92, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Debriefing Report', 'url'=>'admin.reports.debriefing_report', 'permission_id' => 170),
        array('id' => 93, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Cargo Returns Shipment Report', 'url'=>'admin.reports.cargo_returns_shipment_report', 'permission_id' => 172),
        array('id' => 94, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Return To Re-Attempt Ratio Report', 'url'=>'admin.reports.return_reattempt_ratio', 'permission_id' => 174),
        array('id' => 95, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Revenue Report', 'url'=>'admin.reports.revenue', 'permission_id' => 176),
        array('id' => 96, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Revenue Report', 'url'=>'admin.reports.revenue', 'permission_id' => 177),
        array('id' => 97, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'CRM Report', 'url'=>'admin.reports.crm_report', 'permission_id' => 200),
        array('id' => 98, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'GST Report', 'url'=>'admin.reports.gst_report', 'permission_id' => 199),
        array('id' => 99, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Summary Report', 'url'=>'admin.reports.summary', 'permission_id' => 210),
        array('id' => 100, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Account Activation Report', 'url'=>'admin.reports.account_activation', 'permission_id' => 246),
        array('id' => 101, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Adjustments Report', 'url'=>'admin.reports.adjustments', 'permission_id' => 248),
        array('id' => 102, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Rates Edit Report', 'url'=>'admin.reports.account_edit', 'permission_id' => 255),
        array('id' => 103, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'SDN View', 'url'=>'admin.delivery.completed.index', 'permission_id' => 252),
        array('id' => 104, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Shipper Bank History Report', 'url'=>'admin.reports.shipper_bank_history', 'permission_id' => 257),
        array('id' => 105, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Consignee Details History Report', 'url'=>'admin.reports.consignee_details_history', 'permission_id' => 258),
        array('id' => 106, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Booked And Cancelled Shipments Report', 'url'=>'admin.reports.booked_and_cancelled_shipments_report', 'permission_id' => 259),
        array('id' => 107, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Fake Statuses Shipments Report', 'url'=>'admin.reports.fake_statuses_shipments_report', 'permission_id' => 263),
        array('id' => 108, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Daily Visit Report', 'url'=>'admin.reports.daily_visit_report', 'permission_id' => 264),
        array('id' => 109, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Delivered Shipment Report (Rider Wise)', 'url'=>'admin.reports.delivered_shipment_report', 'permission_id' => 275),
        array('id' => 110, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Route Distribution Summary Report', 'url'=>'admin.reports.route_distribution_summary_report', 'permission_id' => 300),
        array('id' => 111, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Arrived At Destination VS Out For Delivery VS Receive Report', 'url'=>'admin.reports.arrived_at_destination_out_for_delivery_and_received_report', 'permission_id' => 300),
        array('id' => 112, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Account Reconciliation Report', 'url'=>'admin.reports.account_reconciliation', 'permission_id' => 312),
        array('id' => 113, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Cargo Short Received Shipments', 'url'=>'admin.reports.cargo_short_received_shipments', 'permission_id' => 319),
        array('id' => 114, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Multiple IBAN Number Change Report', 'url'=>'admin.reports.multiple_IBAN_no_change', 'permission_id' => 328),
        array('id' => 115, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Pickup Report', 'url'=>'admin.reports.pickup_report', 'permission_id' => 337),
        array('id' => 116, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Not Attempted Aging Report', 'url'=>'admin.reports.not_attempted_aging_report', 'permission_id' => 360),
        array('id' => 117, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Daily and Monthly Adjustments Report', 'url'=>'admin.reports.daily_monthly_adjustment', 'permission_id' => 373),
        array('id' => 118, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Petty Cash Expense Summary Report', 'url'=>'admin.petty_cash_expense.index', 'permission_id' => 395),
        array('id' => 119, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'App Efficiency Report', 'url'=>'admin.reports.app_efficiency', 'permission_id' => 401),
        array('id' => 120, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Packaging Material Requests', 'url'=>'client.packaging.flyers.index', 'permission_id' => 76),
        array('id' => 121, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Packaging Material Requests', 'url'=>'admin.materials.requests.index', 'permission_id' => 79),
        array('id' => 122, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Packaging Material Types', 'url'=>'admin.materials.types.index', 'permission_id' => 214),
        array('id' => 123, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Warehouse List', 'url'=>'admin.materials.warehouses.index', 'permission_id' => 217),
        array('id' => 124, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Packaging Stock Inventory', 'url'=>'admin.materials.inventory.index', 'permission_id' => 221),
        array('id' => 125, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Users', 'url'=>'admin.user_management.user.index', 'permission_id' => 81),
        array('id' => 126, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Add User', 'url'=>'admin.user_management.user.add.index', 'permission_id' => 82),
        array('id' => 127, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Update User', 'url'=>'admin.user_management.user.update.index', 'permission_id' => 83),
        array('id' => 128, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Roles', 'url'=>'admin.user_management.role.index', 'permission_id' => 85),
        array('id' => 129, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Add Role', 'url'=>'admin.user_management.role.add.index', 'permission_id' => 86),
        array('id' => 130, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Update Role', 'url'=>'admin.user_management.role.update.index', 'permission_id' => 87),
        array('id' => 131, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'User Request', 'url'=>'admin.user_management.user_request.index', 'permission_id' => 394),
        array('id' => 132, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Zonal Management', 'url'=>'admin.management.zonal.index', 'permission_id' => 131),
        array('id' => 133, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Add Zone', 'url'=>'admin.management.zonal.add.index', 'permission_id' => 132),
        array('id' => 134, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Update Zone', 'url'=>'admin.management.zonal.update.index', 'permission_id' => 133),
        array('id' => 135, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'City Management', 'url'=>'admin.management.city_management', 'permission_id' => 144),
        array('id' => 136, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Route Management', 'url'=>'admin.management.route_management', 'permission_id' => 92),
        array('id' => 137, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Rider Management', 'url'=>'admin.management.rider_management', 'permission_id' => 96),
        array('id' => 138, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Permanent Riders', 'url'=>'admin.management.riders.permanent_index', 'permission_id' => 377),
        array('id' => 139, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Incentive Riders', 'url'=>'admin.management.riders.incentive_index', 'permission_id' => 378),
        array('id' => 140, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Blacklisted Riders', 'url'=>'admin.management.riders.blacklisted', 'permission_id' => 379),
        array('id' => 141, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'SMS History', 'url'=>'admin.management.riders.sms_history', 'permission_id' => 380),
        array('id' => 142, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Notifications', 'url'=>'admin.notifications.index', 'permission_id' => 100),
        array('id' => 143, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Update CRM Permission', 'url'=>'admin.crm.update.index', 'permission_id' => 188),
        array('id' => 144, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Launched/Re-Open Requests', 'url'=>'admin.crm.launched_re_open', 'permission_id' => 233),
        array('id' => 145, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'In-Process Requests', 'url'=>'admin.crm.in_process', 'permission_id' => 234),
        array('id' => 146, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Resolved Requests', 'url'=>'admin.crm.resolved', 'permission_id' => 235),
        array('id' => 147, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Closed Requests', 'url'=>'admin.crm.closed', 'permission_id' => 236),
        array('id' => 148, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Consignee Info Requests', 'url'=>'admin.crm.consignee_info', 'permission_id' => 363),
        array('id' => 149, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Pickup Weight Threshold', 'url'=>'admin.settings.pickup', 'permission_id' => 104),
        array('id' => 150, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Shipment Cancellation Cut-Off Days', 'url'=>'admin.settings.shipment_cancellation_cut_off_days', 'permission_id' => 116),
        array('id' => 151, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Non Service Area', 'url'=>'admin.settings.non_service_area', 'permission_id' => 150),
        array('id' => 152, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Daily Pickup & Sales Cron Time', 'url'=>'admin.settings.daily_pickup_sales_cron_time', 'permission_id' => 151),
        array('id' => 153, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Ticker', 'url'=>'admin.settings.ticker', 'permission_id' => 152),
        array('id' => 154, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Petty Cash Heads', 'url'=>'admin.settings.petty_cash.account_head', 'permission_id' => 157),
        array('id' => 155, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Petty Cash Titles', 'url'=>'admin.settings.petty_cash.account_title', 'permission_id' => 158),
        array('id' => 156, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Auto-Invoice Generation & Due Date Length', 'url'=>'admin.settings.auto_invoice_generation_and_due_date_index', 'permission_id' => 171),
        array('id' => 157, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Debriefing Report Cut-Off Time', 'url'=>'admin.settings.debriefing_report_cut_off_time', 'permission_id' => 175),
        array('id' => 158, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Return Note Restriction Bypass', 'url'=>'admin.settings.return_note_restriction_bypass', 'permission_id' => 192),
        array('id' => 159, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'COD CAP For Zone Classes', 'url'=>'admin.settings.cod_cap_zone', 'permission_id' => 197),
        array('id' => 160, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Stock Movement', 'url'=>'admin.settings.stock_movement', 'permission_id' => 228),
        array('id' => 161, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Delivery Call Verification Ratio', 'url'=>'admin.settings.delivery_call_verification_ratio', 'permission_id' => 231),
        array('id' => 162, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'CRM TAT Cut-Off Time & Holidays', 'url'=>'admin.settings.crm_cut_off_time_and_holidays', 'permission_id' => 237),
        array('id' => 163, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Maximum Consolidation Shipments', 'url'=>'admin.settings.max_consolidation_shipments', 'permission_id' => 256),
        array('id' => 164, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'CRM Case Nature Types', 'url'=>'admin.settings.add_case_nature_types', 'permission_id' => 260),
        array('id' => 165, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Return Confirmation Pending Shipment Selection Time', 'url'=>'admin.settings.return_confirmation_pending_shipment_selection_time', 'permission_id' => 253),
        array('id' => 166, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Return Delivered To Shipper Email Cut-Off Time', 'url'=>'admin.settings.return_delivered_to_shipper_cut_off_time', 'permission_id' => 269),
        array('id' => 167, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Shipper CRM Re-Open Request', 'url'=>'admin.settings.crm_reopen', 'permission_id' => 274),
        array('id' => 168, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Auto Comment', 'url'=>'admin.settings.crm_comment', 'permission_id' => 325),
        array('id' => 169, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Multiple Sale Person Tagging', 'url'=>'admin.settings.multiple_sale_person', 'permission_id' => 279),
        array('id' => 170, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'FOC Account', 'url'=>'admin.settings.foc_account', 'permission_id' => 302),
        array('id' => 171, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Minimum Chargeable Weight', 'url'=>'admin.settings.minimum_chargeable_weight', 'permission_id' => 303),
        array('id' => 172, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Projection Percentage', 'url'=>'admin.settings.sales.percentage', 'permission_id' => 313),
        array('id' => 173, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Business Projection Reasons', 'url'=>'admin.settings.sales.reasons', 'permission_id' => 314),
        array('id' => 174, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Projected Shipments', 'url'=>'admin.settings.sales.shipments', 'permission_id' => 318),
        array('id' => 175, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Blacklist Settings', 'url'=>'admin.settings.blacklist.index', 'permission_id' => 329),
        array('id' => 176, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Search Consignee', 'url'=>'admin.settings.blacklist.search', 'permission_id' => 330),
        array('id' => 177, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Return Reasons', 'url'=>'admin.settings.return.reasons', 'permission_id' => 335),
        array('id' => 178, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Sales Tier', 'url'=>'admin.settings.commission.index', 'permission_id' => 331),
        array('id' => 179, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Commission Percentage', 'url'=>'admin.settings.commission.commission_percentage', 'permission_id' => 332),
        array('id' => 180, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'CRM Launched', 'url'=>'admin.settings.CRM.escalation.launched.index', 'permission_id' => 347),
        array('id' => 181, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'CRM Add', 'url'=>'admin.settings.CRM.escalation.launched.add', 'permission_id' => 347),
        array('id' => 182, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'CRM Edit', 'url'=>'admin.settings.CRM.escalation.launched.edit', 'permission_id' => 347),
        array('id' => 183, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'In Process CRM', 'url'=>'admin.settings.CRM.escalation.in_process.index', 'permission_id' => 348),
        array('id' => 184, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'In Process Add CRM', 'url'=>'admin.settings.CRM.escalation.in_process.add', 'permission_id' => 348),
        array('id' => 185, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'In Process Edit CRM', 'url'=>'admin.settings.CRM.escalation.in_process.edit', 'permission_id' => 348),
        array('id' => 186, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'CRM Level', 'url'=>'admin.settings.CRM.escalation.level', 'permission_id' => 349),
        array('id' => 187, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'CRM Tagging', 'url'=>'admin.settings.CRM.escalation.tagging.index', 'permission_id' => 350),
        array('id' => 188, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'CRM Add Tagging', 'url'=>'admin.settings.CRM.escalation.tagging.add', 'permission_id' => 350),
        array('id' => 189, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'CRM Edit Tagging', 'url'=>'admin.settings.CRM.escalation.tagging.edit', 'permission_id' => 350),
        array('id' => 190, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'CRM Default Agent', 'url'=>'admin.settings.CRM.default_agent', 'permission_id' => 351),
        array('id' => 191, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Holidays', 'url'=>'admin.settings.holidays', 'permission_id' => 358),
        array('id' => 192, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Not Attempted Report Cron Time', 'url'=>'admin.settings.not_attempted_report_cron_time', 'permission_id' => 359),
        array('id' => 193, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'NSA Accounts', 'url'=>'admin.settings.nsa_account', 'permission_id' => 367),
        array('id' => 194, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Restriction of Cities for Overland Shipments', 'url'=>'admin.settings.restrict_cities_intercept', 'permission_id' => 375),
        array('id' => 195, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Short Receive Report Hub Wise Time', 'url'=>'admin.settings.short_received_report_hub_wise_time', 'permission_id' => 387),
        array('id' => 196, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Return Parcels after Attempt', 'url'=>'admin.settings.retrun_parcels_after_attempts', 'permission_id' => 384),
        array('id' => 197, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Runners', 'url'=>'admin.settings.runner.index', 'permission_id' => 385),
        array('id' => 198, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Arrived At Origin Sms For Consignee', 'url'=>'admin.settings.arrived_at_origin_sms_for_shipper', 'permission_id' => 388),
        array('id' => 199, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Pickup Address Wise Payment Accounts', 'url'=>'admin.settings.pickup_address_wise_payment_accounts', 'permission_id' => 391),
        array('id' => 200, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Cancelled Shipments', 'url'=>'admin.cancelled_shipments.index', 'permission_id' => 117),
        array('id' => 201, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Walk-In Booking History', 'url'=>'admin.shipment.history.walk_in_history', 'permission_id' => 254),
        array('id' => 202, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Intercept/Re-Book to New Destination', 'url'=>'admin.intercept.index', 'permission_id' => 245),
        array('id' => 203, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Scanning History', 'url'=>'admin.scanning_history.index', 'permission_id' => 306),
        array('id' => 204, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Sales Dashboard', 'url'=>'admin.sales.dashboard.index', 'permission_id' => 315),
        array('id' => 205, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Add Coordinates', 'url'=>'admin.coordinates.add', 'permission_id' => 324),
        array('id' => 206, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Create Handover Note', 'url'=>'admin.handover.index', 'permission_id' => 339),
        array('id' => 207, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Receive Handover Note', 'url'=>'admin.handover.receive', 'permission_id' => 341),
        array('id' => 208, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Handover List', 'url'=>'admin.handover.list', 'permission_id' => 342),
        array('id' => 209, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Responsibles', 'url'=>'admin.handover.responsibles', 'permission_id' => 340),
        array('id' => 210, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Multiple Piece Shipment(s)', 'url'=>'admin.shipment_pieces.add', 'permission_id' => 368),
        array('id' => 211, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Shipment Pieces List', 'url'=>'admin.shipment_pieces.list', 'permission_id' => 369),
        array('id' => 212, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Runners On Route', 'url'=>'admin.runner.index', 'permission_id' => 386),
        array('id' => 213, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Open Parcel History', 'url'=>'admin.parcel_history.index', 'permission_id' => 392),
        array('id' => 214, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'International Tracking Upload', 'url'=>'admin.international.tracking_upload', 'permission_id' => 398),
        array('id' => 215, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Telenor Bulk Delivery', 'url'=>'admin.telenor.delivery', 'permission_id' => 399),
        array('id' => 216, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Telenor Return Update', 'url'=>'admin.telenor.return', 'permission_id' => 400),
        array('id' => 217, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Telenor Calls', 'url'=>'admin.telenor.call_response', 'permission_id' => 402)

        ));
    }
}
