<?php

use Illuminate\Database\Seeder;

class AdminSearchSonicSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('admins_screen_list')->truncate();
        $timestamp = \Carbon\Carbon::now()->format('Y-m-d H:i:s');
        DB::table('admins_screen_list')->insert(array(
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Shippers  >  Receiving Sheet History', 'url'=>'admin.shipment.receiving_sheet.index', 'permission_id' => 364),
            array( 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Shippers  >  Accounts > Pending Accounts List', 'url'=>'admin.accounts.pending', 'permission_id' => 5),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Shippers  >  Accounts > Active Accounts List', 'url'=>'admin.accounts.active', 'permission_id' => 11),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Shippers  >  Accounts  > Blocked Accounts List', 'url'=>'admin.accounts.block', 'permission_id' => 15),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Shippers  >  Accounts > Merged Accounts', 'url'=>'admin.accounts.merged_account.index', 'permission_id' => 241),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Shippers  >  Packaging  >  Requests > Packaging Material Stock Requests', 'url'=>'admin.packaging.index', 'permission_id' => 76),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Shippers  >  Packaging  >  Requests > Packaging Material Requests', 'url'=>'admin.packaging.requests.index', 'permission_id' => 79),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Shippers  >  Packaging > Warehouse List', 'url'=>'admin.packaging.warehouse.index', 'permission_id' => 217),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Shippers  >  Daily Visit Form', 'url'=>'admin.daily_visit.index', 'permission_id' => 265),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Shippers  >  Projection > Sales Dashboard', 'url'=>'admin.dashboard.sales.index', 'permission_id' => 315),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Shippers  >  POC and KAM Tagged Accounts', 'url'=>'admin.shipment.poc_kam_tagged_accounts.index', 'permission_id' => 315),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Bookings  >  Walk-In > Book a Shipment (Walk-In)', 'url'=>'admin.shipment.book.walk_in', 'permission_id' => 155),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Bookings  >  Walk-In > Book a International Shipment (Walk-In)', 'url'=>'admin.shipment.book.international_walk_in', 'permission_id' => 155),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Bookings  >  Walk-In > Walk-In Booking History', 'url'=>'admin.shipment.history.walk_in_history', 'permission_id' => 209),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Bookings  >  Cancelled Shipments', 'url'=>'admin.cancelled_shipments.index', 'permission_id' => 117),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Bookings  >  Consolidated Shipments', 'url'=>'admin.shipment.consolidation.history.index', 'permission_id' => 254),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'First Mile  >  Multiple Pieces  >  Multiple Piece Shipment(s)', 'url'=>'admin.multiple_pieces.add.index', 'permission_id' => 368),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'First Mile  >  Multiple Pieces  >  Shipment Pieces List', 'url'=>'admin.multiple_pieces.hold.index', 'permission_id' => 369),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'First Mile  >  Multiple Pieces  >  Shipment Pieces Resolved', 'url'=>'admin.multiple_pieces.resolved.index', 'permission_id' => 370),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'First Mile  >  Pickups  >  Pending Pickups', 'url'=>'admin.pickups.pending.index', 'permission_id' => 17),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'First Mile  >  Pickups  >  Assigned Pickups', 'url'=>'admin.pickups.assigned.index', 'permission_id' => 20),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'First Mile  >  Pickups  >  Receive Pickups', 'url'=>'admin.pickups.receive.index', 'permission_id' => 23),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'First Mile  >  Pickups  >  Pickups History', 'url'=>'admin.pickups.history.index', 'permission_id' => 123),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'First Mile  >  Pickups  >  Rider Pickups', 'url'=>'admin.pickups.rider.index', 'permission_id' => 271),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'First Mile  >  Rider Tracking', 'url'=>'admin.v2_pickups.rider_tracking.index', 'permission_id' => 446),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'First Mile  >  Pickups  >  Rider Pickup Action Logs', 'url'=>'admin.pickups.rider.action_log.index', 'permission_id' => 272),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'First Mile  >  V2 Pickups  >  Pending Pickups', 'url'=>'admin.v2_pickups.pending.index', 'permission_id' => 17),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'First Mile  >  V2 Pickups  >  Arrival Service Center', 'url'=>'admin.v2_pickups.arrival_service.service.index', 'permission_id' => 24),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'First Mile  >  V2 Pickups  >  Individual Arrival of Shipments', 'url'=>'admin.v2_pickups.arrival.individual.index', 'permission_id' => 24),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'First Mile  >  V2 Pickups  >  Bulk Arrival (Without Weight)', 'url'=>'admin.v2_pickups.arrival.bulk.index', 'permission_id' => 24),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'First Mile  >  V2 Pickups  >  Rider Pickups', 'url'=>'admin.v2_pickups.rider.index', 'permission_id' => 271),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'First Mile  >  V2 Pickups  >  Rider Pickup Action Logs', 'url'=>'admin.v2_pickups.action_log.index', 'permission_id' => 272),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'First Mile  >  V2 Pickups  >  Rider Receiving', 'url'=>'admin.v2_pickups.rider_receiving.index', 'permission_id' => 366),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Supply Chain  >  Order Management  >  Supply Chain Management', 'url'=>'admin.cargo.supply_chain.supply_chain_index', 'permission_id' => 376),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Supply Chain  >  Cargo  >  Pending Shipments for Cargo', 'url'=>'admin.cargo.pending.index', 'permission_id' => 25),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Supply Chain  >  Cargo  >  Create Cargo', 'url'=>'admin.cargo.create.index', 'permission_id' => 26),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Supply Chain  >  Cargo  >  Draft Cargo', 'url'=>'admin.cargo.draft.index', 'permission_id' => 26),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Supply Chain  >  Cargo  >  Cargo in Transit', 'url'=>'admin.cargo.in_transit.index', 'permission_id' => 27),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Supply Chain  >  Cargo  >  Cargo History', 'url'=>'admin.cargo.history.index', 'permission_id' => 124),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Supply Chain  >  Cargo  >  Quick Receive Cargo', 'url'=>'admin.cargo.receive.quick.index', 'permission_id' => 31),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Supply Chain  >  Cargo  >  Quick Receive List', 'url'=>'admin.cargo.receive.quick.list.index', 'permission_id' => 31),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Supply Chain  >  Master Cargo  >  Bag > Pending Shipments for Bag', 'url'=>'admin.master_cargo.pending.index', 'permission_id' => 25),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Supply Chain  >  Master Cargo  >  Master Cargo History', 'url'=>'admin.master_cargo.history.index', 'permission_id' => 124),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Supply Chain  >  Master Cargo  >  Pending for Master Cargo', 'url'=>'admin.master_cargo.pending.index', 'permission_id' => 25),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Supply Chain  >  Master Cargo  >  Master Cargo In Transit', 'url'=>'admin.master_cargo.in_transit.index', 'permission_id' => 27),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Supply Chain  >  Master Cargo  >  Pending Bags for Receiving', 'url'=>'admin.master_cargo.bag.in_transit.index', 'permission_id' => 27),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Supply Chain  >  Master Cargo  >  Receive Master Cargo', 'url'=>'admin.master_cargo.receive.index', 'permission_id' => 31),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Supply Chain  >  Master Cargo  >  Runners', 'url'=>'admin.settings.runner.index', 'permission_id' => 385),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Supply Chain  >  Master Cargo  >  Shipment On Hold  >  Supply Chain Shipment On Hold', 'url'=>'admin.cargo.supply_chain.shipment_on_hold.index', 'permission_id' => 404),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Supply Chain  >  Master Cargo  >  Shipment On Hold  >  Supply Chain Shipment On Hold History', 'url'=>'admin.cargo.supply_chain.shipment_on_hold.history.index', 'permission_id' => 405),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Last Mile  >  Delivery  >  Pending Deliveries', 'url'=>'admin.delivery.pending.index', 'permission_id' => 33),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Last Mile > Delivery  >  Create Delivery Note', 'url'=>'admin.delivery.note.index', 'permission_id' => 35),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Last Mile > Delivery  >  Receive Deliveries', 'url'=>'admin.delivery.receive.index', 'permission_id' => 36),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Last Mile > Delivery  >  Pending Cash Collection', 'url'=>'admin.delivery.cash_collection.pending.index', 'permission_id' => 105),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Last Mile > Delivery  >  Completed Deliveries', 'url'=>'admin.delivery.completed.index', 'permission_id' => 40),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Last Mile > Delivery  >  Station Deposit Notes', 'url'=>'admin.delivery.sdn.index', 'permission_id' => 42),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Last Mile > Delivery  >  Remove Fake Status', 'url'=>'admin.delivery.fake_status.index', 'permission_id' => 203),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Last Mile > Delivery  >  Delivery Note History', 'url'=>'admin.delivery.history.index', 'permission_id' => 125),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Last Mile > Delivery  >  SameDay Delivery', 'url'=>'admin.sameday.index', 'permission_id' => 32),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Last Mile > Delivery  >  Log Fake Statuses', 'url'=>'admin.delivery.fake_status.log.index', 'permission_id' => 262),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Last Mile > Return  >  Return Confirmation Pending Shipments', 'url'=>'admin.return.index', 'permission_id' => 44),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Last Mile > Return  >  Create Return Note', 'url'=>'admin.return.create.index', 'permission_id' => 48),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Last Mile > Return  >  Receive Return Deliveries', 'url'=>'admin.return.receive.index', 'permission_id' => 49),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Last Mile > Return  >  Return For CX & Sales', 'url'=>'admin.return.cx_sales.index', 'permission_id' => 266),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Last Mile > Return  >  Return Deliveries History', 'url'=>'admin.return.history.index', 'permission_id' => 126),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Financials  >  Add Shipment Adjustment', 'url'=>'admin.finance.add_shipment_adjustment.index', 'permission_id' => 136),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Financials  >  Payments  >  Make Payments', 'url'=>'admin.finance.make_payments.index', 'permission_id' => 59),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Financials  >  Payments  >  Done Payments', 'url'=>'admin.finance.done_payments.index', 'permission_id' => 61),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Financials  >  Payments  >  Invoices', 'url'=>'admin.finance.invoice_for_reimbursement.index', 'permission_id' => 396),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Financials  >  Invoices  >  Pending Invoices', 'url'=>'admin.finance.invoices.index', 'permission_id' => 120),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Financials  >  Invoices  >  Received Invoices', 'url'=>'admin.finance.invoices.received_index', 'permission_id' => 120),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Financials  >  Recovery  >  Outstanding SDN', 'url'=>'admin.finance.outstanding_sdn.index', 'permission_id' => 52),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Financials  >  Recovery  >  Outstanding Shipments', 'url'=>'admin.finance.outstanding_shipments.index', 'permission_id' => 54),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Financials  >  Recovery  >  Outstanding WalkIn Shipments', 'url'=>'admin.finance.outstanding_shipments.walk_in_index', 'permission_id' => 167),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Financials  >  Petty Cash  >  Make Petty Cash Statement', 'url'=>'admin.petty_cash.make.index', 'permission_id' => 145),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Financials  >  Petty Cash  >  Petty Cash Statement Drafts', 'url'=>'admin.petty_cash.draft.index', 'permission_id' => 146),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Financials  >  Petty Cash  >  Petty Cash Statements', 'url'=>'admin.petty_cash.statements.index', 'permission_id' => 146),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Financials  >  Petty Cash  >  Approved Petty Cash Statements', 'url'=>'admin.petty_cash.approved.index', 'permission_id' => 147),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Financials  >  Petty Cash  >  Rejected Petty Cash Statements', 'url'=>'admin.petty_cash.rejected.index', 'permission_id' => 243),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'CRM > Requests  >  Launched/ReOpen Requests', 'url'=>'admin.crm.launched_re_open.index', 'permission_id' => 233),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'CRM > Requests  >  InProcess Requests', 'url'=>'admin.crm.in_process.index', 'permission_id' => 234),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'CRM > Requests  >  Resolved Requests', 'url'=>'admin.crm.resolved.index', 'permission_id' => 235),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'CRM > Requests  >  Closed Requests', 'url'=>'admin.crm.closed.index', 'permission_id' => 236),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'CRM > Consignee Info  >  Consignee Info Requests', 'url'=>'admin.crm.consignee_info.index', 'permission_id' => 263),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Support  >  Order Management', 'url'=>'admin.orders.index', 'permission_id' => 139),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Support  >  Self Collection Shipments', 'url'=>'admin.orders.self_collection.index', 'permission_id' => 105),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Support  >  Quick Tracking', 'url'=>'admin.quick_tracking.index', 'permission_id' => 37),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Support  >  CX Quick Tracking', 'url'=>'admin.cx_quick_tracking.cx_index', 'permission_id' => 37),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Support  >  Disputes', 'url'=>'admin.dispute.index', 'permission_id' => 1),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Support  >  Telenor  >  Telenor Bulk Delivery', 'url'=>'admin.telenor.delivery.index', 'permission_id' => 399),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Support  >  Telenor  >  Telenor Return Update', 'url'=>'admin.telenor.return.index', 'permission_id' => 400),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Support  >  Month Closing Shipments', 'url'=>'admin.month_closing.index', 'permission_id' => 141),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Support  >  Misroute  >  Misrouted Shipments', 'url'=>'admin.delivery.misroute.index', 'permission_id' => 107),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Support  >  Misroute  >  Update Misrouted', 'url'=>'admin.delivery.misroute.update.index', 'permission_id' => 108),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Support  >  Misroute  >  Misrouted History', 'url'=>'admin.delivery.misroute.history.index', 'permission_id' => 119),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Support  >  Lost  >  Lost Shipments', 'url'=>'admin.delivery.lost.index', 'permission_id' => 127),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Support  >  Lost  >  Add Lost Shipments', 'url'=>'admin.delivery.lost.add.index', 'permission_id' => 130),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Support  >  Intercept  >  Intercept Requests', 'url'=>'admin.delivery.intercept.index', 'permission_id' => 193),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Support  >  Intercept  >  Intercept Rebook History', 'url'=>'admin.delivery.intercept.history.index', 'permission_id' => 196),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Support  >  Replacement To Regular  >  Replacement Not Collected', 'url'=>'admin.delivery.replacement.not_collected.index', 'permission_id' => 206),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Support  >  Replacement To Regular  >  Replacement Collected', 'url'=>'admin.delivery.replacement.collected.index', 'permission_id' => 207),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Support  >  Replacement To Regular  >  Replacement To Regular Log', 'url'=>'admin.delivery.replacement.logs.index', 'permission_id' => 208),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Support  >  Change Shipment Amount', 'url'=>'admin.finance.change_shipment_amount.index', 'permission_id' => 57),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Support  >  Change Shipment Weight', 'url'=>'admin.finance.change_shipment_weight.index', 'permission_id' => 134),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Support  >  Add Coordinates', 'url'=>'admin.coordinates.add.index', 'permission_id' => 134),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Support  >  Scanning History', 'url'=>'admin.scanning_history.index', 'permission_id' => 306),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Support  >  Sales  >  Sales Person Targets', 'url'=>'admin.settings.sales.targets.index', 'permission_id' => 279),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Support  >  Sales  >  Sales Person Targets History', 'url'=>'admin.settings.sales.history.index', 'permission_id' => 279),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Support  >  Sales Dashboard', 'url'=>'admin.dashboard.index', 'permission_id' => 331),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Support  >  Open Parcel History', 'url'=>'admin.open_parcel_history.index', 'permission_id' => 392),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Support  >  Trax Directory', 'url'=>'admin.trax_directory.index', 'permission_id' => 392),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Support  >  International Tracking Upload', 'url'=>'admin.international.tracking_upload.index', 'permission_id' => 398),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Reports  >  Booked VS Received VS Delivered VS Returned', 'url'=>'admin.pickups.bookedvsreceived.index', 'permission_id' => 113),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Reports  >  Pickup Notes Report', 'url'=>'admin.reports.pickup_note.index', 'permission_id' => 64),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Reports  >  Multiple IBAN Number Change Report', 'url'=>'admin.reports.multiple_iban.index', 'permission_id' => 328),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Reports  >  Cargo Received Report', 'url'=>'admin.reports.cargo_received.index', 'permission_id' => 65),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Reports  >  Completed Delivery Notes Report', 'url'=>'admin.reports.completed_delivery_notes.index', 'permission_id' => 66),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Reports  >  Return Notes Report', 'url'=>'admin.reports.return_note.index', 'permission_id' => 67),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Reports  >  Outstanding Shipments Report', 'url'=>'admin.reports.outstanding_shipments.index', 'permission_id' => 68),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Reports  >  Lead Time Report', 'url'=>'admin.reports.lead_time.index', 'permission_id' => 69),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Reports  >  Quality of Service Report', 'url'=>'admin.reports.qsr.index', 'permission_id' => 70),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Reports  >  Quality Assurance Report', 'url'=>'admin.reports.qa.index', 'permission_id' => 71),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Reports  >  Customer Retention Report', 'url'=>'admin.reports.customer_retention.index', 'permission_id' => 70),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Reports  >  Daily Pickup & Sales Report', 'url'=>'admin.reports.daily_pickup_sales.index', 'permission_id' => 73),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Reports  >  Monthwise Customer Sales Report', 'url'=>'admin.reports.customer_sales.index', 'permission_id' => 74),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Reports  >  Overall Sales Report', 'url'=>'admin.reports.overall_sales.index', 'permission_id' => 75),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Reports  >  Sales Person Performance Report', 'url'=>'admin.reports.sales_person_performance.index', 'permission_id' => 138),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Reports  >  Negative Balance Customers Report', 'url'=>'admin.reports.negative_balance_customers.index', 'permission_id' => 148),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Reports  >  Petty Cash Statements Report', 'url'=>'admin.reports.petty_cash.index', 'permission_id' => 156),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Reports  >  Call Verification Report', 'url'=>'admin.reports.call_verification.index', 'permission_id' => 153),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Reports  >  Fake Statuses Report', 'url'=>'admin.reports.fake_status.index', 'permission_id' => 169),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Reports  >  Debriefing Report', 'url'=>'admin.reports.debriefing.index', 'permission_id' => 170),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Reports  >  Cargo Returns Shipment Report', 'url'=>'admin.reports.cargo_returns_shipment.index', 'permission_id' => 172),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Reports  >  Return To ReAttempt Ratio Report', 'url'=>'admin.reports.return_reattempt_ratio.index', 'permission_id' => 174),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Reports  >  Multiple Payments Report', 'url'=>'admin.reports.multiple_payment_report.index', 'permission_id' => 176),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Reports  >  Revenue Report', 'url'=>'admin.reports.revenue.index', 'permission_id' => 176),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Reports  >  GST Report', 'url'=>'admin.reports.gst.index', 'permission_id' => 199),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Reports  >  CRM Report', 'url'=>'admin.reports.crm.index', 'permission_id' => 200),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Reports  >  Summary Report', 'url'=>'admin.reports.summary.index', 'permission_id' => 210),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Reports  >  Account Activation Report', 'url'=>'admin.reports.account_activation.index', 'permission_id' => 246),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Reports  >  Adjustments Report', 'url'=>'admin.reports.adjustments.index', 'permission_id' => 248),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Reports  >  Station Deposit Notes Report', 'url'=>'admin.reports.sdn.index', 'permission_id' => 252),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Reports  >  ates Edit Report', 'url'=>'admin.reports.account_edit.index', 'permission_id' => 255),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Reports  >  Shipper Bank History Report', 'url'=>'admin.reports.bank_history.index', 'permission_id' => 257),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Reports  >  Consignee Details History Report', 'url'=>'admin.reports.consignee_details.index', 'permission_id' => 258),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Reports  >  Booked And Cancelled Shipments Report', 'url'=>'admin.reports.booked_and_cancelled.index', 'permission_id' => 259),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Reports  >  Fake Statuses Shipments Report', 'url'=>'admin.reports.fake_status_shipments.index', 'permission_id' => 263),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Reports  >  Daily Visit Report', 'url'=>'admin.reports.daily_visit.index', 'permission_id' => 264),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Reports  >  Delivered Shipment Report (Rider Wise)', 'url'=>'admin.reports.delivered_shipment.index', 'permission_id' => 275),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Reports  >  Route Distribution Summary Report', 'url'=>'admin.reports.route_distribution.index', 'permission_id' => 300),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Reports  >  Arrived At Destination VS Out For Delivery VS Receive Report', 'url'=>'admin.reports.destination_delivery_received.index', 'permission_id' => 300),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Reports  >  Account Reconciliation Report', 'url'=>'admin.reports.account_reconciliation.index', 'permission_id' => 312),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Reports  >  Cargo Short Received Shipments', 'url'=>'admin.reports.cargo_short_received_shipments.index', 'permission_id' => 319),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Reports  >  Last Mile Status Report', 'url'=>'admin.reports.last_mile_status.index', 'permission_id' => 319),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Reports  >  Pickup Report', 'url'=>'admin.reports.pickup_report.index', 'permission_id' => 337),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Reports  >  Completed Aging Report', 'url'=>'admin.reports.completed_aging.index', 'permission_id' => 337),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Reports  >  Pending Cash Collection Report', 'url'=>'admin.reports.pending_cash_collection.index', 'permission_id' => 337),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Reports  >  Station Recovery Report', 'url'=>'admin.reports.station_recovery.index', 'permission_id' => 337),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Reports  >  Not Attempted Aging Report', 'url'=>'admin.reports.not_attempted_aging.index', 'permission_id' => 360),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Reports  >  Daily and Monthly Adjustments Report', 'url'=>'admin.reports.daily_monthly_adjustment.index', 'permission_id' => 373),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Reports  >  App Efficiency Report', 'url'=>'admin.reports.app_efficiency.index', 'permission_id' => 401),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Settings  >  Shippers  >  Auto Account Disabled Days', 'url'=>'admin.settings.auto_account_disabled_days.auto_index', 'permission_id' => 149),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Settings  >  Shippers  >  Stock Movement', 'url'=>'admin.settings.stock_movement.index', 'permission_id' => 401),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Settings  >  Shippers  >  Packaging Material Types', 'url'=>'admin.packaging.types.index', 'permission_id' => 401),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Settings  >  Shippers  >  FOC Account', 'url'=>'admin.settings.foc_account.index', 'permission_id' => 401),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Settings  >  Shippers  >  Minimum Chargeable Weight', 'url'=>'admin.settings.minimum_chargeable_weight.index', 'permission_id' => 401),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Settings  >  Shippers  >  Projection Percentage', 'url'=>'admin.settings.sales.projection.percentage.index', 'permission_id' => 401),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Settings  >  Shippers  >  Business Projection Reasons', 'url'=>'admin.settings.sales.projection.reasons.index', 'permission_id' => 401),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Settings  >  Shippers  >  Projected Shipments', 'url'=>'admin.settings.sales.projection.shipments.index', 'permission_id' => 401),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Settings  >  Shippers  >  NSA Accounts', 'url'=>'admin.settings.nsa_account.index', 'permission_id' => 401),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Settings  >  Shippers  >  Arrived At Origin Sms For Consignee', 'url'=>'admin.settings.sms_shipper_wise.index', 'permission_id' => 401),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Settings  >  Bookings  >  Shipment Cancellation CutOff Days', 'url'=>'admin.settings.shipment_cancellation_cut_off_days.index', 'permission_id' => 401),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Settings  >  Bookings  >  Non Service Area', 'url'=>'admin.settings.non_service_area.index', 'permission_id' => 401),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Settings  >  Bookings  >  WalkIn  >  Domestic WalkIn', 'url'=>'admin.settings.walk_in.index', 'permission_id' => 401),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Settings  >  Bookings  >  WalkIn  >  International WalkIn', 'url'=>'admin.settings.international_walk_in.index', 'permission_id' => 401),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Settings  >  Bookings  >  COD CAP For Zone Classes', 'url'=>'admin.settings.cod_cap_zones.index', 'permission_id' => 401),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Settings  >  Bookings  >  Maximum Consolidation Shipments', 'url'=>'admin.settings.consolidation.max.index', 'permission_id' => 401),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Settings  >  Bookings  >  Restriction of Cities for Overland Shipments', 'url'=>'admin.settings.restrict_cities_intercept.index', 'permission_id' => 401),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Settings  >  First Mile  >  Pickup Weight Threshold', 'url'=>'admin.settings.pickup.index', 'permission_id' => 401),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Settings  > First Mile  >   Pickup CutOff Settings', 'url'=>'admin.settings.pickup.pickup_settings', 'permission_id' => 401),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Settings  >  Supply Chain  >  Mapping', 'url'=>'admin.cargo.mapping.index', 'permission_id' => 401),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Settings  >  Supply Chain  >  Short Receive Report Hub Wise Time', 'url'=>'admin.settings.short_received_hub_wise_cron.index', 'permission_id' => 401),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Settings  >  Supply Chain  >  Runners', 'url'=>'admin.settings.runner.index', 'permission_id' => 401),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Settings  >  Last Mile  >  Return Note Restriction Bypass', 'url'=>'admin.settings.return_note_restriction_bypass.index', 'permission_id' => 401),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Settings  >  Last Mile  >  Delivery Call Verification Ratio', 'url'=>'admin.settings.delivery_call_verification_ratio.index', 'permission_id' => 401),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Settings  >  Last Mile  >  Network Management  >  Zonal Management', 'url'=>'admin.management.zonal.index', 'permission_id' => 401),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Settings  >  Last Mile  >  Network Management  >  City Management', 'url'=>'admin.management.city.index', 'permission_id' => 401),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Settings  >  Last Mile > Network Management  >  Route Management', 'url'=>'admin.management.route.index', 'permission_id' => 401),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Settings  >  Last Mile  >  Route Management', 'url'=>'admin.settings.return_confirmation_pending_shipment_selection_time.index', 'permission_id' => 401),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Settings  >  Last Mile  >  Return Reasons', 'url'=>'admin.settings.return.reason.index', 'permission_id' => 401),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Settings  >  Last Mile  >  Station Recovery Report Cron Time', 'url'=>'admin.settings.station_recovery_cron.index', 'permission_id' => 401),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Settings  >  Last Mile  >  Return Parcels after Attempt', 'url'=>'admin.settings.restrict_parcels_attempt.index', 'permission_id' => 401),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Settings  >  Financials  >  Petty Cash  >  Petty Cash Heads', 'url'=>'admin.settings.petty_cash.heads.index', 'permission_id' => 401),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Settings  >  Financials  >  Petty Cash  >  Petty Cash Titles', 'url'=>'admin.settings.petty_cash.titles.index', 'permission_id' => 401),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Settings  >  Financials  >  AutoInvoice Generation & Due Date Length', 'url'=>'admin.settings.auto_invoice_generation_and_due_date.index', 'permission_id' => 401),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Settings  >  Financials  >  Fuel Factor', 'url'=>'admin.settings.fuel_factor.index', 'permission_id' => 401),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Settings  >  Financials  >  Weight Charges Factor', 'url'=>'admin.settings.weight_factor.index', 'permission_id' => 401),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Settings  >  Financials  >  IBFT Charges', 'url'=>'admin.settings.ibft_charges.index', 'permission_id' => 401),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Settings  >  Financials  >  Over Payment Limit', 'url'=>'admin.settings.over_payment_limit.index', 'permission_id' => 401),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Settings  >  Financials  >  Pickup Address Wise Payment Accounts', 'url'=>'admin.settings.pickup_address_wise_payment_accounts.index', 'permission_id' => 401),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Settings  >  CRM  >  CRM Permissions', 'url'=>'admin.crm.permissions', 'permission_id' => 401),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Settings  >  CRM  >  CRM TAT CutOff Time & Holidays', 'url'=>'admin.settings.crm_cut_off_time_and_holidays.index', 'permission_id' => 401),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Settings  >  CRM  >  CRM Case Nature Types', 'url'=>'admin.settings.crm_case_nature_types.index', 'permission_id' => 401),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Settings  >  CRM  >  Shipper CRM ReOpen Request', 'url'=>'admin.settings.crm_reopen.index', 'permission_id' => 401),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Settings  >  CRM  >  Delay In Delivery Message', 'url'=>'admin.settings.delay_in_delivery_massage.index', 'permission_id' => 401),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Settings  >  CRM  >  CRM Comments', 'url'=>'admin.settings.crm_comment.index', 'permission_id' => 401),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Settings  >  CRM  >  Crm Default Agent', 'url'=>'admin.settings.default_agent.index', 'permission_id' => 401),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Settings  >  CRM  >  Escalations > Crm Escalation Launched Setting', 'url'=>'admin.settings.escalation.launched.index', 'permission_id' => 401),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Settings  >  CRM  >  Escalations > Crm Escalation InProcess Setting', 'url'=>'admin.settings.escalation.in_process.index', 'permission_id' => 401),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Settings  >  CRM  >  Escalations > Escalation Level(s)', 'url'=>'admin.settings.escalation.levels.index', 'permission_id' => 401),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Settings  >  CRM  >  Escalations  >  Crm Escalation Tagging Setting', 'url'=>'admin.settings.escalation.tagging.index', 'permission_id' => 401),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Settings  >  Support >  Ticker', 'url'=>'admin.settings.ticker.index', 'permission_id' => 401),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Settings  >  Support  >  User Management  >  Users', 'url'=>'admin.user_management.users.index', 'permission_id' => 401),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Settings  >  Support  >  User Management  >  Roles', 'url'=>'admin.user_management.roles.index', 'permission_id' => 401),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Settings  >  Support  >  User Management  >  Multiple Sale Person Tagging', 'url'=>'admin.settings.multiple_sale_tagging.index', 'permission_id' => 401),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Settings  >  Support  >  User Management  >  User Request', 'url'=>'admin.user_management.user_requests.index', 'permission_id' => 401),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Settings  >  Support  >  Notifications', 'url'=>'admin.notifications.index', 'permission_id' => 401),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Settings  >  Support  >  Holidays', 'url'=>'admin.settings.holidays.index', 'permission_id' => 401),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Settings  >  Reports  >  Daily Pickup & Sales Cron Time', 'url'=>'admin.settings.daily_pickup_sales_cron.index', 'permission_id' => 401),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Settings  >  Reports   > Debriefing Report CutOff Time', 'url'=>'admin.settings.debriefing_report_cut_off_time.index', 'permission_id' => 401),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Settings  >  Reports  >  Return Delivered To Shipper Email CutOff Time', 'url'=>'admin.settings.return_delivered_to_shipper_email_cut_off_time.index', 'permission_id' => 401),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Settings  >  Reports  >  Overnight Overland Cargo Report', 'url'=>'admin.settings.overnight_overland_cargo_report.index', 'permission_id' => 401),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Settings  >  Reports  >  Pending Cash Collection & Completed Aging Reports Setting', 'url'=>'admin.settings.aging_report.index', 'permission_id' => 401),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Settings  >  Reports  >  Zero Charges Report Setting', 'url'=>'admin.settings.zero_charges.index', 'permission_id' => 401),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Settings  >  Reports  >  Not Attempted Report Cron Time', 'url'=>'admin.settings.not_attempted_cron.index', 'permission_id' => 401),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Settings  >  Blacklist  >  Blacklist Settings', 'url'=>'admin.settings.blacklist.index', 'permission_id' => 401),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Settings  >  Blacklist  >  Search Consignee', 'url'=>'admin.settings.blacklist.search.index', 'permission_id' => 401),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Settings  >  Commission  >  Sales Tier', 'url'=>'admin.settings.commission.index', 'permission_id' => 401),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Settings  >  Commission  >  Commission Percentage', 'url'=>'admin.settings.commission.percentage.index', 'permission_id' => 401),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Shipment Handover  >  Create Handover Note', 'url'=>'admin.handover.create.index', 'permission_id' => 339),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Shipment Handover  >  Receive Handover Note', 'url'=>'admin.handover.receive.index', 'permission_id' => 341),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Shipment Handover  >  Handover List', 'url'=>'admin.handover.list.index', 'permission_id' => 342),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Shipment Handover  >  Responsibles', 'url'=>'admin.handover.responsibles.index', 'permission_id' => 340),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Power BI Dashboard  >  Report  Sales Dashboard', 'url'=>'admin.power_bi.sales', 'permission_id' => 342),
            array('created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Power BI Dashboard  >  Operation Dashboard', 'url'=>'admin.power_bi.operation', 'permission_id' => 342)
        ));
    }
}
