<?php

use Illuminate\Database\Seeder;

class AdminSearchSonicSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $timestamp = \Carbon\Carbon::now()->format('Y-m-d H:i:s');
        DB::table('admins_screen_list')->insert(array(
            array('id' => 1, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Disputes', 'url'=>'admin.dispute.index', 'permission_id' => 1),
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Daily Visit Form', 'url'=>'admin.daily_visit.index', 'permission_id' => 265),
            array('id' => 3, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Pending Pickups', 'url'=>'admin.pickups.index', 'permission_id' => 17),
            array('id' => 4, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Receive Pickups', 'url'=>'admin.receive.index', 'permission_id' => 23),
            array('id' => 5, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Merged Accounts', 'url'=>'admin.accounts.sister_accounts.merged_accounts.index', 'permission_id' => 241),
            array('id' => 6, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Edit Sister Accounts', 'url'=>'admin.accounts.sister_accounts.edit', 'permission_id' => 242),
            array('id' => 7, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Receiving Sheet History', 'url'=>'admin.shipment.receiving_sheet.index', 'permission_id' => 364),
            array('id' => 8, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Receive Pickups', 'url'=>'admin.pickups.receive.index', 'permission_id' => 23),
            array('id' => 9, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Receive Pickups', 'url'=>'admin.pickups.receive.index', 'permission_id' => 24),
            array('id' => 10, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Booked VS Received VS Delivered VS Returned', 'url'=>'admin.pickups.bookedvsreceived.index', 'permission_id' => 113),
            array('id' => 11, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Pickups History', 'url'=>'admin.pickups.history.index', 'permission_id' => 123),
            array('id' => 12, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Pending Pickups', 'url'=>'admin.v2_pickups.pending', 'permission_id' => 17),
            array('id' => 13, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Individual Arrival of Shipments', 'url'=>'admin.v2_pickups.arrival_individual_weight', 'permission_id' => 24),
            array('id' => 14, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Bulk Arrival (Without Weight)', 'url'=>'admin.v2_pickups.arrival_single_weight', 'permission_id' => 24),
            array('id' => 15, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Rider Pickups', 'url'=>'admin.v2_pickups.rider_pickups', 'permission_id' => 271),
            array('id' => 16, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Rider Pickup Action Logs', 'url'=>'admin.v2_pickups.action_log.index', 'permission_id' => 272),
            array('id' => 17, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Rider Receiving', 'url'=>'admin.v2_pickups.receiving_sheet', 'permission_id' => 366),
            array('id' => 18, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Pending Shipments for Cargo', 'url'=>'admin.cargo.pending', 'permission_id' => 25),
            array('id' => 19, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Draft Cargo', 'url'=>'admin.cargo.draft', 'permission_id' => 26),
            array('id' => 20, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Create Cargo', 'url'=>'admin.cargo.create', 'permission_id' => 26),
            array('id' => 21, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Cargo in Transit', 'url'=>'admin.cargo.in_transit', 'permission_id' => 27),
            array('id' => 22, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Cargo Received Report', 'url'=>'admin.cargo.receive', 'permission_id' => 31),
            array('id' => 23, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Cargo History', 'url'=>'admin.cargo.history', 'permission_id' => 124),
            array('id' => 24, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Mapping', 'url'=>'admin.cargo.mapping', 'permission_id' => 198),
            array('id' => 25, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Quick Receive Cargo', 'url'=>'admin.cargo.quick_receive', 'permission_id' => 31),
            array('id' => 26, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Quick Receive List', 'url'=>'admin.cargo.quick_receive_index', 'permission_id' => 31),
            array('id' => 27, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Supply Chain Management', 'url'=>'admin.supply_chain.index', 'permission_id' => 376),
            array('id' => 28, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Pending Shipments for Bag', 'url'=>'admin.master_cargo.bag.pending', 'permission_id' => 25),
            array('id' => 29, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Create Bag', 'url'=>'admin.master_cargo.bag.create', 'permission_id' => 26),
            array('id' => 30, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Master Cargo In Transit', 'url'=>'admin.master_cargo.in_transit', 'permission_id' => 27),
            array('id' => 31, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Receive Master Cargo', 'url'=>'admin.master_cargo.receive', 'permission_id' => 31),
            array('id' => 32, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Master Cargo History', 'url'=>'admin.master_cargo.history', 'permission_id' => 124),
            array('id' => 33, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Master Cargo Received', 'url'=>'admin.master_cargo.received', 'permission_id' => 124),
            array('id' => 34, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Quick Receive Master Cargo', 'url'=>'admin.master_cargo.quick_receive', 'permission_id' => 31),
             array('id' => 35, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Quick Receive Master Cargo List', 'url'=>'admin.master_cargo.quick_receive_index', 'permission_id' => 31),
             array('id' => 36, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Same-Day Delivery', 'url'=>'admin.sameday.index', 'permission_id' => 32),
             array('id' => 37, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Pending Deliveries', 'url'=>'admin.delivery.pending.index', 'permission_id' => 33),
             array('id' => 38, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Create Delivery Note', 'url'=>'admin.delivery.note.index', 'permission_id' => 35),
             array('id' => 39, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Receive Deliveries', 'url'=>'admin.delivery.receive.index', 'permission_id' => 36),
             array('id' => 40, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Completed Deliveries', 'url'=>'admin.delivery.complete.index', 'permission_id' => 40),
             array('id' => 41, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Station Deposit Notes', 'url'=>'admin.delivery.sdn.index', 'permission_id' => 42),
             array('id' => 42, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Pending Cash Collection', 'url'=>'admin.delivery.complete.pending_cash_collection', 'permission_id' => 105),
             array('id' => 43, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Misrouted Shipments', 'url'=>'admin.delivery.misroute.index', 'permission_id' => 107),
             array('id' => 44, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Update Misrouted', 'url'=>'admin.delivery.misroute.update', 'permission_id' => 108),
             array('id' => 45, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Misrouted History', 'url'=>'admin.delivery.misroute.history', 'permission_id' => 119),
             array('id' => 46, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Delivery Note History
', 'url'=>'admin.delivery.history.index', 'permission_id' => 125),
             array('id' => 47, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Lost Shipments', 'url'=>'admin.lost.index', 'permission_id' => 127),
             array('id' => 48, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Add Lost Shipments', 'url'=>'admin.lost.add_shipments', 'permission_id' => 130),
             array('id' => 49, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Intercept Requests', 'url'=>'admin.delivery.intercept.index', 'permission_id' => 193),
             array('id' => 50, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Intercept Rebook History', 'url'=>'admin.delivery.intercept.history', 'permission_id' => 196),
             array('id' => 51, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Remove Fake Status', 'url'=>'admin.delivery.fake_status.index', 'permission_id' => 203),
             array('id' => 52, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Replacement Not Collected', 'url'=>'admin.delivery.replacement.not_collected', 'permission_id' => 206),
             array('id' => 53, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Replacement Collected', 'url'=>'admin.delivery.replacement.collected', 'permission_id' => 207),
             array('id' => 54, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Replacement To Regular Log', 'url'=>'admin.delivery.replacement.replacement_to_regular_logs', 'permission_id' => 208),
             array('id' => 55, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Log Fake Statuses', 'url'=>'admin.fake_statuses.index', 'permission_id' => 262),
             array('id' => 56, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Return Confirmation Pending Shipments', 'url'=>'admin.return.index', 'permission_id' => 44),
             array('id' => 57, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Create Return Note', 'url'=>'admin.return.create', 'permission_id' => 48),
             array('id' => 58, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Receive Return Deliveries', 'url'=>'admin.return.receive', 'permission_id' => 49),
             array('id' => 59, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Return Deliveries History', 'url'=>'admin.return.history', 'permission_id' => 126),
             array('id' => 60, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Return For CX & Sales', 'url'=>'admin.return.cx_sales', 'permission_id' => 266),
             array('id' => 61, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Outstanding SDN', 'url'=>'admin.finance.outstanding_sdn', 'permission_id' => 52),
             array('id' => 62, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Outstanding Shipments', 'url'=>'admin.finance.outstanding_shipments', 'permission_id' => 54),
             array('id' => 63, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Change Shipment Amount', 'url'=>'admin.finance.change_shipment_amount', 'permission_id' => 57),
             array('id' => 64, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Change Shipment Weight', 'url'=>'admin.finance.change_shipment_weight', 'permission_id' => 134),
             array('id' => 65, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Add Shipment Adjustment', 'url'=>'admin.finance.add_shipment_adjustment', 'permission_id' => 136),
             array('id' => 66, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Make Payments', 'url'=>'admin.finance.make_payments', 'permission_id' => 59),
             array('id' => 67, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Done Payments', 'url'=>'admin.finance.done_payments', 'permission_id' => 61),
             array('id' => 68, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Pending Invoices', 'url'=>'admin.finance.invoices', 'permission_id' => 120),
             array('id' => 69, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Outstanding Walk-In Shipments', 'url'=>'admin.finance.outstanding_walk_in_shipments', 'permission_id' => 167),
             array('id' => 70, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Make Payments Pickup Wise', 'url'=>'admin.finance.make_payments_pickup_wise', 'permission_id' => 396),
             array('id' => 71, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Make Petty Cash Statement', 'url'=>'admin.petty_cash.make', 'permission_id' => 145),
             array('id' => 72, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Petty Cash Statements', 'url'=>'admin.petty_cash.statements', 'permission_id' => 146),
             array('id' => 73, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Approved Petty Cash Statements', 'url'=>'admin.petty_cash.approved', 'permission_id' => 147),
             array('id' => 74, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Rejected Petty Cash Statements', 'url'=>'admin.petty_cash.rejected', 'permission_id' => 243),
             array('id' => 75, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Month Closing Shipments', 'url'=>'admin.month_closing.index', 'permission_id' => 141),
             array('id' => 76, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Pickup Notes Report', 'url'=>'admin.reports.pickup_notes_report', 'permission_id' => 64),
             array('id' => 77, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Cargo Received Report', 'url'=>'admin.reports.cargo_received_report', 'permission_id' => 65),
             array('id' => 78, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Completed Delivery Notes Report', 'url'=>'admin.reports.completed_delivery_notes_report', 'permission_id' => 66),
             array('id' => 79, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Return Notes Report', 'url'=>'admin.reports.return_notes_report', 'permission_id' => 67),
             array('id' => 80, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Outstanding Shipments Report', 'url'=>'admin.reports.outstanding_shipments_report', 'permission_id' => 68),
             array('id' => 81, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Lead Time Report', 'url'=>'admin.reports.lead_time_report', 'permission_id' => 69),
             array('id' => 82, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Quality of Service Report', 'url'=>'admin.reports.qsr_report', 'permission_id' => 70),
             array('id' => 83, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Quality Assurance Report', 'url'=>'admin.reports.qa_report', 'permission_id' => 71),
             array('id' => 84, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Daily Pickup & Sales Report', 'url'=>'admin.reports.daily_pickup_sales_report', 'permission_id' => 73),
             array('id' => 85, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Monthwise Customer Sales Report', 'url'=>'admin.reports.customer_sales_report', 'permission_id' => 74),
             array('id' => 86, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Overall Sales Report', 'url'=>'admin.reports.overall_sales', 'permission_id' => 75),
             array('id' => 87, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Sales Person Performance Report', 'url'=>'admin.reports.sales_person_performance_report', 'permission_id' => 138),
             array('id' => 88, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Negative Balance Customers Report', 'url'=>'admin.reports.invoice_for_negative_balance_customers', 'permission_id' => 148),
             array('id' => 89, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Call Verification Report', 'url'=>'admin.reports.call_verification_report', 'permission_id' => 153),
             array('id' => 90, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Petty Cash Statements Report', 'url'=>'admin.reports.petty_cash_statement', 'permission_id' => 156),
             array('id' => 91, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Fake Statuses Report
', 'url'=>'admin.reports.fake_statuses_report', 'permission_id' => 169),
        array('id' => 100, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Debriefing Report', 'url'=>'admin.reports.debriefing_report', 'permission_id' => 170),
        array('id' => 101, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Cargo Returns Shipment Report', 'url'=>'admin.reports.cargo_returns_shipment_report', 'permission_id' => 172),
        array('id' => 102, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Return To Re-Attempt Ratio Report', 'url'=>'admin.reports.return_reattempt_ratio', 'permission_id' => 174),
        array('id' => 103, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Debriefing Report', 'url'=>'admin.reports.debriefing_report', 'permission_id' => 170),
        array('id' => 100, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Debriefing Report', 'url'=>'admin.reports.debriefing_report', 'permission_id' => 170),
        array('id' => 100, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Debriefing Report', 'url'=>'admin.reports.debriefing_report', 'permission_id' => 170),
        array('id' => 100, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Debriefing Report', 'url'=>'admin.reports.debriefing_report', 'permission_id' => 170),
        array('id' => 100, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Debriefing Report', 'url'=>'admin.reports.debriefing_report', 'permission_id' => 170),
        array('id' => 100, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Debriefing Report', 'url'=>'admin.reports.debriefing_report', 'permission_id' => 170),
        array('id' => 100, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Debriefing Report', 'url'=>'admin.reports.debriefing_report', 'permission_id' => 170),
        array('id' => 100, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Debriefing Report', 'url'=>'admin.reports.debriefing_report', 'permission_id' => 170),
        array('id' => 100, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Debriefing Report', 'url'=>'admin.reports.debriefing_report', 'permission_id' => 170),
        array('id' => 100, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Debriefing Report', 'url'=>'admin.reports.debriefing_report', 'permission_id' => 170),
        array('id' => 100, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Debriefing Report', 'url'=>'admin.reports.debriefing_report', 'permission_id' => 170),
        array('id' => 100, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Debriefing Report', 'url'=>'admin.reports.debriefing_report', 'permission_id' => 170),
        array('id' => 100, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Debriefing Report', 'url'=>'admin.reports.debriefing_report', 'permission_id' => 170),
        array('id' => 100, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Debriefing Report', 'url'=>'admin.reports.debriefing_report', 'permission_id' => 170),
        array('id' => 100, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Debriefing Report', 'url'=>'admin.reports.debriefing_report', 'permission_id' => 170),
        array('id' => 100, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Debriefing Report', 'url'=>'admin.reports.debriefing_report', 'permission_id' => 170),
        array('id' => 100, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Debriefing Report', 'url'=>'admin.reports.debriefing_report', 'permission_id' => 170),
        array('id' => 100, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Debriefing Report', 'url'=>'admin.reports.debriefing_report', 'permission_id' => 170),
        array('id' => 100, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Debriefing Report', 'url'=>'admin.reports.debriefing_report', 'permission_id' => 170),
        array('id' => 100, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Debriefing Report', 'url'=>'admin.reports.debriefing_report', 'permission_id' => 170),
        array('id' => 100, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Debriefing Report', 'url'=>'admin.reports.debriefing_report', 'permission_id' => 170),
        array('id' => 100, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Debriefing Report', 'url'=>'admin.reports.debriefing_report', 'permission_id' => 170),
        array('id' => 100, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Debriefing Report', 'url'=>'admin.reports.debriefing_report', 'permission_id' => 170),
        array('id' => 100, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Debriefing Report', 'url'=>'admin.reports.debriefing_report', 'permission_id' => 170),
        array('id' => 100, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Debriefing Report', 'url'=>'admin.reports.debriefing_report', 'permission_id' => 170),
        array('id' => 100, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Debriefing Report', 'url'=>'admin.reports.debriefing_report', 'permission_id' => 170),
        array('id' => 100, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Debriefing Report', 'url'=>'admin.reports.debriefing_report', 'permission_id' => 170),
        array('id' => 100, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Debriefing Report', 'url'=>'admin.reports.debriefing_report', 'permission_id' => 170),
        array('id' => 100, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Debriefing Report', 'url'=>'admin.reports.debriefing_report', 'permission_id' => 170),
        array('id' => 100, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Debriefing Report', 'url'=>'admin.reports.debriefing_report', 'permission_id' => 170)

        ));
    }
}
