<?php

use Illuminate\Database\Seeder;

class AdminSearchSonicSeed extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $timestamp = \Carbon\Carbon::now()->format('Y-m-d H:i:s');
        DB::table('admins_screen_list')->insert(array(
            array('id' => 1, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Receiving Sheet History', 'url'=>'admin.shipment.receiving_sheet.index', 'permission_id' => 364),
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Pending Accounts List', 'url'=>'admin.accounts.pending_accounts_list', 'permission_id' => 5),
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Active Accounts List', 'url'=>'admin.accounts.active_accounts_list', 'permission_id' => 11)
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Blocked Accounts List', 'url'=>'admin.accounts.block_accounts_list', 'permission_id' => 15)
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Merged Accounts', 'url'=>'admin.accounts.sister_accounts.merged_accounts.index', 'permission_id' => 241)
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Packaging Material Stock Requests', 'url'=>'admin.materials.flyers.index', 'permission_id' => 76))
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Packaging Material Requests', 'url'=>'admin.materials.requests.index', 'permission_id' => 79))
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Warehouse List', 'url'=>'admin.materials.warehouses.index', 'permission_id' => 217))
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Daily Visit Form', 'url'=>'admin.daily_visit.index', 'permission_id' => 265))
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Sales Dashboard', 'url'=>'admin.sales.dashboard.index', 'permission_id' => 315))
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'POC and KAM Tagged Accounts', 'url'=>'admin.tagged_accounts.index', 'permission_id' => 315))
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Book a Shipment (Walk-In)', 'url'=>'admin.shipment.book.walk_in', 'permission_id' => 155))
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Walk-In Booking History', 'url'=>'admin.shipment.history.walk_in_history', 'permission_id' => 209))
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Cancelled Shipments', 'url'=>'admin.cancelled_shipments.index', 'permission_id' => 117))
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Consolidated Shipments', 'url'=>'admin.shipment.consolidated.history', 'permission_id' => 254))
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Multiple Piece Shipment(s)', 'url'=>'admin.shipment_pieces.add', 'permission_id' => 368))
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Shipment Pieces List', 'url'=>'admin.shipment_pieces.list', 'permission_id' => 369))
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Shipment Pieces Resolved', 'url'=>'admin.shipment_pieces.resolved_index', 'permission_id' => 370))
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Pending Pickups', 'url'=>'admin.pickups.pending.index', 'permission_id' => 17))
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Assigned Pickups', 'url'=>'admin.pickups.assigned.index', 'permission_id' => 20))
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Receive Pickups', 'url'=>'admin.pickups.receive.index', 'permission_id' => 23))
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Pickups History', 'url'=>'admin.pickups.history.index', 'permission_id' => 123))
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Rider Pickups', 'url'=>'admin.pickups.rider.index', 'permission_id' => 271))
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Rider Pickup Action Logs', 'url'=>'admin.pickups.rider.action_log.index', 'permission_id' => 272))
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Pending Pickups', 'url'=>'admin.v2_pickups.pending', 'permission_id' => 17))
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Arrival Service Center', 'url'=>'admin.v2_pickups.arrival_service_center.arrival_service', 'permission_id' => 24))
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Individual Arrival of Shipments', 'url'=>'admin.v2_pickups.arrival_individual_weight', 'permission_id' => 24))
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Bulk Arrival (Without Weight)', 'url'=>'admin.v2_pickups.arrival_single_weight', 'permission_id' => 24))
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Rider Pickups', 'url'=>'admin.v2_pickups.rider_pickups', 'permission_id' => 271))
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Rider Pickup Action Logs', 'url'=>'admin.v2_pickups.action_log.index', 'permission_id' => 272))
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Rider Receiving', 'url'=>'admin.v2_pickups.receiving_sheet', 'permission_id' => 366))
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Supply Chain Management', 'url'=>'admin.supply_chain.index', 'permission_id' => 376))
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Pending Shipments for Cargo', 'url'=>'admin.cargo.pending', 'permission_id' => 25))
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Create Cargo', 'url'=>'admin.cargo.create', 'permission_id' => 26))
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Draft Cargo', 'url'=>'admin.cargo.draft', 'permission_id' => 26))
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Cargo in Transit', 'url'=>'admin.cargo.in_transit', 'permission_id' => 27))
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Cargo History', 'url'=>'admin.cargo.history', 'permission_id' => 124))
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Quick Receive Cargo', 'url'=>'admin.cargo.quick_receive', 'permission_id' => 31))
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Quick Receive List', 'url'=>'admin.cargo.quick_receive_index', 'permission_id' => 31))
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Pending Shipments for Bag', 'url'=>'admin.master_cargo.bag.pending', 'permission_id' => 25))
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Create Bag', 'url'=>'admin.master_cargo.bag.create', 'permission_id' => 26))
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Master Cargo History', 'url'=>'admin.master_cargo.history', 'permission_id' => 124))
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Pending for Master Cargo', 'url'=>'admin.master_cargo.pending', 'permission_id' => 25))
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Master Cargo In Transit', 'url'=>'admin.master_cargo.in_transit', 'permission_id' => 27))
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Pending Bags for Receiving', 'url'=>'admin.master_cargo.bag.in_transit', 'permission_id' => 27))
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Receive Master Cargo', 'url'=>'admin.master_cargo.receive', 'permission_id' => 31))
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Master Cargo History', 'url'=>'admin.master_cargo.history', 'permission_id' => 124))
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Runners', 'url'=>'admin.settings.runner.index', 'permission_id' => 385))
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Supply Chain Shipment On Hold', 'url'=>'admin.supply_chain.shipment_on_hold', 'permission_id' => 404))
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Supply Chain Shipment On Hold History', 'url'=>'admin.supply_chain.shipment_on_hold_history', 'permission_id' => 405))
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Pending Deliveries', 'url'=>'admin.delivery.pending.index', 'permission_id' => 33))
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Create Delivery Note', 'url'=>'admin.delivery.note.index', 'permission_id' => 35))
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Receive Deliveries', 'url'=>'admin.delivery.receive.index', 'permission_id' => 36))
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Pending Cash Collection', 'url'=>'admin.delivery.complete.pending_cash_collection', 'permission_id' => 105))
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'admin.delivery.complete.index', 'url'=>'admin.delivery.complete.index', 'permission_id' => 40))
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Station Deposit Notes', 'url'=>'admin.delivery.sdn.index', 'permission_id' => 42))
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'admin.delivery.fake_status.index', 'url'=>'admin.delivery.fake_status.index', 'permission_id' => 203))
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Delivery Note History', 'url'=>'admin.delivery.history.index', 'permission_id' => 125))
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Same-Day Delivery', 'url'=>'admin.sameday.index', 'permission_id' => 32))
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Log Fake Statuses', 'url'=>'admin.fake_statuses.index', 'permission_id' => 262))
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Return Confirmation Pending Shipments', 'url'=>'admin.return.index', 'permission_id' => 44))
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Create Return Note', 'url'=>'admin.return.create', 'permission_id' => 48))
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Receive Return Deliveries', 'url'=>'admin.return.receive', 'permission_id' => 49))
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Return For CX & Sales', 'url'=>'admin.return.cx_sales', 'permission_id' => 266))
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Return Deliveries History', 'url'=>'admin.return.history', 'permission_id' => 126))
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Add Shipment Adjustment', 'url'=>'admin.finance.add_shipment_adjustment', 'permission_id' => 136))
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Make Payments', 'url'=>'admin.finance.make_payments', 'permission_id' => 59))
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Done Payments', 'url'=>'admin.finance.done_payments', 'permission_id' => 61))
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Invoices', 'url'=>'admin.finance.invoice_for_reimbursement', 'permission_id' => 396))
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Pending Invoices', 'url'=>'admin.finance.invoices', 'permission_id' => 120))
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Received Invoices', 'url'=>'admin.finance.received_invoice', 'permission_id' => 120))
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Outstanding SDN', 'url'=>'admin.finance.outstanding_sdn', 'permission_id' => 52))
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Outstanding Shipments', 'url'=>'admin.finance.outstanding_shipments', 'permission_id' => 54))
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Outstanding Walk-In Shipments', 'url'=>'admin.finance.outstanding_walk_in_shipments', 'permission_id' => 167))
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Make Petty Cash Statement', 'url'=>'admin.petty_cash.make', 'permission_id' => 145))
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Petty Cash Statement Drafts', 'url'=>'admin.petty_cash.draft.index', 'permission_id' => 146))
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Petty Cash Statements', 'url'=>'admin.petty_cash.statements', 'permission_id' => 146))
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Approved Petty Cash Statements', 'url'=>'admin.petty_cash.approved', 'permission_id' => 147))
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Rejected Petty Cash Statements', 'url'=>'admin.petty_cash.rejected', 'permission_id' => 243))
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Launched/Re-Open Requests', 'url'=>'admin.crm.launched_re_open', 'permission_id' => 233))
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'In-Process Requests', 'url'=>'admin.crm.in_process', 'permission_id' => 234))
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Resolved Requests', 'url'=>'admin.crm.resolved', 'permission_id' => 235))
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Closed Requests', 'url'=>'admin.crm.closed', 'permission_id' => 236))
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Consignee Info Requests', 'url'=>'admin.crm.consignee_info', 'permission_id' => 263))
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Order Management', 'url'=>'admin.order_management.index', 'permission_id' => 139))
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Self Collection Shipments', 'url'=>'admin.self_collection.index', 'permission_id' => 105))
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Quick Tracking', 'url'=>'admin.tracking.quick_tracking', 'permission_id' => 37))
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'CX Quick Tracking', 'url'=>'admin.tracking.cx_quick_tracking', 'permission_id' => 37))
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Disputes', 'url'=>'admin.dispute.index', 'permission_id' => 1))
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Telenor Bulk Delivery', 'url'=>'admin.telenor.delivery', 'permission_id' => 399))
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Telenor Return Update', 'url'=>'admin.telenor.return', 'permission_id' => 400))
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Month Closing Shipments', 'url'=>'admin.month_closing.index', 'permission_id' => 141))
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Misrouted Shipments', 'url'=>'admin.delivery.misroute.index', 'permission_id' => 107))
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Update Misrouted', 'url'=>'admin.delivery.misroute.update', 'permission_id' => 108))
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Misrouted History', 'url'=>'admin.delivery.misroute.history', 'permission_id' => 119))
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Lost Shipments', 'url'=>'admin.lost.index', 'permission_id' => 127))
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Add Lost Shipments', 'url'=>'admin.lost.add_shipments', 'permission_id' => 130))
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Intercept Requests', 'url'=>'admin.delivery.intercept.index', 'permission_id' => 193))
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Intercept Rebook History', 'url'=>'admin.delivery.intercept.history', 'permission_id' => 196))
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Replacement Not Collected', 'url'=>'admin.delivery.replacement.not_collected', 'permission_id' => 206))
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Replacement Collected', 'url'=>'admin.delivery.replacement.collected', 'permission_id' => 207))
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Replacement To Regular Log', 'url'=>'admin.delivery.replacement.replacement_to_regular_logs', 'permission_id' => 208))
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Change Shipment Amount', 'url'=>'admin.finance.change_shipment_amount', 'permission_id' => 57))
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Change Shipment Weight', 'url'=>'admin.finance.change_shipment_weight', 'permission_id' => 134))
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Add Coordinates', 'url'=>'admin.coordinates.add', 'permission_id' => 324))
    }
}
