<?php

use Illuminate\Database\Seeder;
use App\Http\Models\HR\EmployeeDesignation;

class EmployeeDirectory3710Seeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        if(DB::table('module_permissions')->where('id',591)->doesntExist()) {
            DB::table('module_permissions')->insert(array(
                array('id' => 591, 'name' => 'Staff Management - Enable/Disable', 'module_id' => 12),
            ));
        }

        DB::table('employee_designations')->truncate();

        $designations = array(
            array('name' => 'Team Lead- Data Entry', 'department_id'=> 1, 'role_id' => 80),
            array('name' => 'Assistant Development Manager', 'department_id'=> 1, 'role_id' => 1),
            array('name' => 'Business Intelligence Analyst', 'department_id'=> 1, 'role_id' => 1),
            array('name' => 'Software Engineer', 'department_id'=> 1, 'role_id' => 1),
            array('name' => 'Support Lead', 'department_id'=> 1, 'role_id' => 80),
            array('name' => 'Assistant Product Manager', 'department_id'=> 1, 'role_id' => 1),
            array('name' => 'Support Engineer', 'department_id'=> 1, 'role_id' => 80),
            array('name' => 'SQA Engineer', 'department_id'=> 1, 'role_id' => 1),
            array('name' => 'Business Analyst', 'department_id'=> 1, 'role_id' => 1),
            array('name' => 'Data Entry Operator', 'department_id'=> 1, 'role_id' => 80),
            array('name' => 'Head of Information Technology', 'department_id'=> 1, 'role_id' => 1),
            array('name' => 'Manager Support & Surveillance', 'department_id'=> 1, 'role_id' => 80),
            array('name' => 'Jr. IT Support', 'department_id'=> 1, 'role_id' => 80),
            array('name' => 'Manager BI', 'department_id'=> 1, 'role_id' => 1),
            array('name' => 'Network Engineer', 'department_id'=> 1, 'role_id' => 80),
            array('name' => 'IT Support Technician', 'department_id'=> 1, 'role_id' => 80),
            array('name' => 'Admin Officer', 'department_id'=> 2, 'role_id' => 24),
            array('name' => 'Office Support Assistant', 'department_id'=> 2, 'role_id' => 24),
            array('name' => 'Office Boy', 'department_id'=> 2, 'role_id' => 79),
            array('name' => 'HR & Admin Executive', 'department_id'=> 2, 'role_id' => 24),
            array('name' => 'Helper', 'department_id'=> 2, 'role_id' => 79),
            array('name' => 'Technician', 'department_id'=> 2, 'role_id' => 79),
            array('name' => 'Sweeper', 'department_id'=> 2, 'role_id' => 79),
            array('name' => 'Assistant Manager Surveillance', 'department_id'=> 2, 'role_id' => 24),
            array('name' => 'Security Officer', 'department_id'=> 2, 'role_id' => 24),
            array('name' => 'CCTV Operator', 'department_id'=> 2, 'role_id' => 79),
            array('name' => 'AM Administration', 'department_id'=> 2, 'role_id' => 24),
            array('name' => 'Head of Admin & Security', 'department_id'=> 2, 'role_id' => 5),
            array('name' => 'Manager Admin & Security', 'department_id'=> 2, 'role_id' => 24),
            array('name' => 'Admin Associate', 'department_id'=> 2, 'role_id' => 24),
            array('name' => 'Vigilance Officer', 'department_id'=> 2, 'role_id' => 79),
            array('name' => 'Admin Executive', 'department_id'=> 2, 'role_id' => 24),
            array('name' => 'CCTV Technician', 'department_id'=> 2, 'role_id' => 79),
            array('name' => 'Front Desk Officer', 'department_id'=> 2, 'role_id' => 79),
            array('name' => 'Assistant Manager CX', 'department_id'=> 3, 'role_id' => 32),
            array('name' => 'Team Lead', 'department_id'=> 3, 'role_id' => 15),
            array('name' => 'Inbound Call Agent', 'department_id'=> 3, 'role_id' => 13),
            array('name' => 'Complaint Management Officer', 'department_id'=> 3, 'role_id' => 28),
            array('name' => 'Operation Intelligence Officer', 'department_id'=> 3, 'role_id' => 15),
            array('name' => 'Return Confirmation Officer', 'department_id'=> 3, 'role_id' => 21),
            array('name' => 'Customer Service Representative', 'department_id'=> 3, 'role_id' => 13),
            array('name' => 'QA Lead', 'department_id'=> 3, 'role_id' => 51),
            array('name' => 'Quality Assurance Officer', 'department_id'=> 3, 'role_id' => 53),
            array('name' => 'Inbound Agent', 'department_id'=> 3, 'role_id' => 13),
            array('name' => 'Complaint Resolution Officer', 'department_id'=> 3, 'role_id' => 28),
            array('name' => 'Incoming Officer', 'department_id'=> 3, 'role_id' => 13),
            array('name' => 'Customer Services Executive', 'department_id'=> 3, 'role_id' => 13),
            array('name' => 'Manager Customer Experience', 'department_id'=> 3, 'role_id' => 6),
            array('name' => 'Return Confirmation Executive', 'department_id'=> 3, 'role_id' => 21),
            array('name' => 'Incoming Agent', 'department_id'=> 3, 'role_id' => 13),
            array('name' => 'Complaint Manager Officer', 'department_id'=> 3, 'role_id' => 37),
            array('name' => 'Communication Officer', 'department_id'=> 3, 'role_id' => 50),
            array('name' => 'Assistant Manager Finance', 'department_id'=> 4, 'role_id' => 7),
            array('name' => 'Accounts Executive', 'department_id'=> 4, 'role_id' => 14),
            array('name' => 'Zonal Accountant', 'department_id'=> 4, 'role_id' => 14),
            array('name' => 'Finance Executive', 'department_id'=> 4, 'role_id' => 14),
            array('name' => 'Team Lead-Receivable', 'department_id'=> 4, 'role_id' => 7),
            array('name' => 'Cashier', 'department_id'=> 4, 'role_id' => 17),
            array('name' => 'Senior Finance Executive', 'department_id'=> 4, 'role_id' => 7),
            array('name' => 'Finance Associate', 'department_id'=> 4, 'role_id' => 14),
            array('name' => 'Team Lead Finance', 'department_id'=> 4, 'role_id' => 7),
            array('name' => 'Manager Finance', 'department_id'=> 4, 'role_id' => 2),
            array('name' => 'Rider', 'department_id'=> 4, 'role_id' => 17),
            array('name' => 'Manager Treasury', 'department_id'=> 4, 'role_id' => 7),
            array('name' => 'Sr. Finance Executive', 'department_id'=> 4, 'role_id' => 7),
            array('name' => 'Functional Consultant', 'department_id'=> 4, 'role_id' => 14),
            array('name' => 'Assistant Manager-Corporate Affairs', 'department_id'=> 5, 'role_id' => 81),
            array('name' => 'CEO', 'department_id'=> 5, 'role_id' => 81),
            array('name' => 'AM Supply Chain', 'department_id'=> 6, 'role_id' => 46),
            array('name' => 'Branch Manager', 'department_id'=> 6, 'role_id' => 10),
            array('name' => 'Courier Officer - Agent', 'department_id'=> 6, 'role_id' => 72),
            array('name' => 'Debriefing Officer', 'department_id'=> 6, 'role_id' => 18),
            array('name' => 'Debriefing Officer ', 'department_id'=> 6, 'role_id' => 18),
            array('name' => 'Debriefing Supervisor-South', 'department_id'=> 6, 'role_id' => 19),
            array('name' => 'Delivery Man', 'department_id'=> 6, 'role_id' => 72),
            array('name' => 'Driver', 'department_id'=> 6, 'role_id' => 72),
            array('name' => 'ESO', 'department_id'=> 6, 'role_id' => 72),
            array('name' => 'ESO ', 'department_id'=> 6, 'role_id' => 72),
            array('name' => 'ESO-Carrefour', 'department_id'=> 6, 'role_id' => 72),
            array('name' => 'Forwarding Assistant', 'department_id'=> 6, 'role_id' => 11),
            array('name' => 'Forwarding Incharge', 'department_id'=> 6, 'role_id' => 55),
            array('name' => 'Ground Courier', 'department_id'=> 6, 'role_id' => 72),
            array('name' => 'Head of Operations', 'department_id'=> 6, 'role_id' => 3),
            array('name' => 'Heavy Courier', 'department_id'=> 6, 'role_id' => 72),
            array('name' => 'International Operation Coordinator', 'department_id'=> 6, 'role_id' => 76),
            array('name' => 'International Support Staff', 'department_id'=> 6, 'role_id' => 76),
            array('name' => 'Loader', 'department_id'=> 6, 'role_id' => 78),
            array('name' => 'Manager Forwarding', 'department_id'=> 6, 'role_id' => 55),
            array('name' => 'Manager Supply Chain', 'department_id'=> 6, 'role_id' => 46),
            array('name' => 'National Manager Debriefing', 'department_id'=> 6, 'role_id' => 19),
            array('name' => 'National Manager MMS', 'department_id'=> 6, 'role_id' => 46),
            array('name' => 'Office Boy', 'department_id'=> 6, 'role_id' => 72),
            array('name' => 'Operation Assistant', 'department_id'=> 6, 'role_id' => 11),
            array('name' => 'Operation Assistant ', 'department_id'=> 6, 'role_id' => 11),
            array('name' => 'Operation Manager', 'department_id'=> 6, 'role_id' => 10),
            array('name' => 'Operation Officer', 'department_id'=> 6, 'role_id' => 11),
            array('name' => 'Operations Officer', 'department_id'=> 6, 'role_id' => 11),
            array('name' => 'Pickup Coordinator', 'department_id'=> 6, 'role_id' => 11),
            array('name' => 'Pickup Courier', 'department_id'=> 6, 'role_id' => 72),
            array('name' => 'Pickup incharge', 'department_id'=> 6, 'role_id' => 55),
            array('name' => 'Project Assistant', 'department_id'=> 6, 'role_id' => 33),
            array('name' => 'Regional Manager', 'department_id'=> 6, 'role_id' => 8),
            array('name' => 'Regional Manager Sales E-commerce & Operations (South)', 'department_id'=> 6, 'role_id' => 8),
            array('name' => 'Rikshaw Driver', 'department_id'=> 6, 'role_id' => 72),
            array('name' => 'Runner Attendant', 'department_id'=> 6, 'role_id' => 72),
            array('name' => 'Shift Incharge', 'department_id'=> 6, 'role_id' => 55),
            array('name' => 'Station Manager', 'department_id'=> 6, 'role_id' => 10),
            array('name' => 'Station Manager ', 'department_id'=> 6, 'role_id' => 10),
            array('name' => 'Supply Chain Executive', 'department_id'=> 6, 'role_id' => 23),
            array('name' => 'Team Leader', 'department_id'=> 6, 'role_id' => 33),
            array('name' => 'Vigilance Officer', 'department_id'=> 6, 'role_id' => 72),
            array('name' => 'Warehouse Officer', 'department_id'=> 6, 'role_id' => 36),
            array('name' => 'Warehouse Supervisor', 'department_id'=> 6, 'role_id' => 35),
            array('name' => 'Zonal Manager', 'department_id'=> 6, 'role_id' => 9),
            array('name' => 'Zonal Manager ', 'department_id'=> 6, 'role_id' => 9),
            array('name' => 'Key Accounts Executive', 'department_id'=> 7, 'role_id' => 43),
            array('name' => 'Team Lead-Key Accounts Executive', 'department_id'=> 7, 'role_id' => 75),
            array('name' => 'Senior Key Accounts Executive', 'department_id'=> 7, 'role_id' => 57),
            array('name' => 'Territory Sales Manager', 'department_id'=> 7, 'role_id' => 12),
            array('name' => 'Business Development Executive', 'department_id'=> 7, 'role_id' => 12),
            array('name' => 'Business Development Manager', 'department_id'=> 7, 'role_id' => 12),
            array('name' => 'Key Accounts Manager-Nationwide', 'department_id'=> 7, 'role_id' => 75),
            array('name' => 'Sales Coordinator', 'department_id'=> 7, 'role_id' => 27),
            array('name' => 'Head of Sales Punjab South', 'department_id'=> 7, 'role_id' => 44),
            array('name' => 'Regional Manager Logistics (South)', 'department_id'=> 7, 'role_id' => 12),
            array('name' => 'Territory Manager', 'department_id'=> 7, 'role_id' => 12),
            array('name' => 'Business Development Manager Corporate', 'department_id'=> 7, 'role_id' => 12),
            array('name' => 'Telesales Executive', 'department_id'=> 7, 'role_id' => 12),
            array('name' => 'Regional Manager Sales E-commerce & Operations (South)', 'department_id'=> 7, 'role_id' => 12),
            array('name' => 'Tele Sales Executive', 'department_id'=> 7, 'role_id' => 12),
            array('name' => 'Sales Support Executive', 'department_id'=> 7, 'role_id' => 27),
            array('name' => 'National Sales Manager', 'department_id'=> 7, 'role_id' => 4),
            array('name' => 'Key Accounts Support', 'department_id'=> 7, 'role_id' => 43),
            array('name' => 'Key Account Executive', 'department_id'=> 7, 'role_id' => 43),
            array('name' => 'Area Sales Manager', 'department_id'=> 7, 'role_id' => 12),
            array('name' => 'Assistant Manager International Operations', 'department_id'=> 8, 'role_id' => 59),
            array('name' => 'Network Manager Commercial', 'department_id'=> 8, 'role_id' => 59),
            array('name' => 'International Business Coordinator', 'department_id'=> 8, 'role_id' => 59),
            array('name' => 'Retail Sales Executive', 'department_id'=> 8, 'role_id' => 39),
            array('name' => 'Head of Commercial and International Business', 'department_id'=> 8, 'role_id' => 52),
            array('name' => 'Coordinator', 'department_id'=> 8, 'role_id' => 59),
            array('name' => 'Assistant Manager-Marketing', 'department_id'=> 8, 'role_id' => 73),
            array('name' => 'International Business Manager', 'department_id'=> 8, 'role_id' => 77),
            array('name' => 'Business Process Re-engineering', 'department_id'=> 9, 'role_id' => 56),
            array('name' => 'Project Supervisor', 'department_id'=> 9, 'role_id' => 71),
            array('name' => 'Project Coordinator', 'department_id'=> 9, 'role_id' => 56),
            array('name' => 'Head of Special Projects', 'department_id'=> 9, 'role_id' => 58),
            array('name' => 'Assistant Manager', 'department_id'=> 9, 'role_id' => 56),
            array('name' => 'Jr. Business Analyst', 'department_id'=> 9, 'role_id' => 56),
            array('name' => 'Business Analyst', 'department_id'=> 9, 'role_id' => 56),
            array('name' => 'Manager Special Projects', 'department_id'=> 9, 'role_id' => 61),
            array('name' => 'Project Cooridnator', 'department_id'=> 9, 'role_id' => 56),
            array('name' => 'Senior HR Executive', 'department_id'=> 10, 'role_id' => 63),
            array('name' => 'HR Executive', 'department_id'=> 10, 'role_id' => 63),
            array('name' => 'HR Associate', 'department_id'=> 10, 'role_id' => 63),
            array('name' => 'Assistant Manager-HR', 'department_id'=> 10, 'role_id' => 63),
            array('name' => 'Assistant Manager-Internal Audit', 'department_id'=> 10, 'role_id' => 69),
            array('name' => 'Manager HR & Internal Audit', 'department_id'=> 10, 'role_id' => 70),
            array('name' => 'Executive', 'department_id'=> 10, 'role_id' => 63),
            array('name' => 'Warehouse Officer', 'department_id'=> 11, 'role_id' => 36),
            array('name' => 'Warehouse Incharge', 'department_id'=> 11, 'role_id' => 36),
            array('name' => 'National Warehousing Manager', 'department_id'=> 11, 'role_id' => 35),
            array('name' => 'Inventory Incharge', 'department_id'=> 11, 'role_id' => 36),
            array('name' => 'Loader', 'department_id'=> 11, 'role_id' => 82),
            array('name' => 'Business Development Manager', 'department_id'=> 11, 'role_id' => 36),
            array('name' => 'AM Warehouse', 'department_id'=> 11, 'role_id' => 36),
        );

        foreach ($designations as $designation)
        {
            $new_designation = new EmployeeDesignation();
            $new_designation->name = $designation['name'];
            $new_designation->department_id = $designation['department_id'];
            $new_designation->role_id = $designation['role_id'];
            $new_designation->save();

            $new_designation->code = 'Des'. str_pad($new_designation->id, 3, '0', STR_PAD_LEFT);
            $new_designation->save();
        }
    }
}
