<?php

use Illuminate\Database\Seeder;
use App\Http\Models\HR\EmployeeDesignation;

class EmployeeDirectory3710Seeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        if(DB::table('module_permissions')->where('id',591)->doesntExist()) {
            DB::table('module_permissions')->insert(array(
                array('id' => 591, 'name' => 'Staff Management - Enable/Disable', 'module_id' => 12),
            ));
        }

        DB::table('employee_designations')->truncate();

        $designations = array(
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
            array('name' => '', 'department_id'=> , 'role_id' => ),
        );

        foreach ($designations as $designation)
        {
            $new_designation = new EmployeeDesignation();
            $new_designation->name = $designation['name'];
            $new_designation->department_id = $designation['department_id'];
            $new_designation->role_id = $designation['role_id'];
            $new_designation->save();

            $new_designation->code = 'Des'. str_pad($new_designation->id, 3, '0', STR_PAD_LEFT);
            $new_designation->save();
        }
    }
}
