<?php

use Illuminate\Database\Seeder;

class EvaluationActivitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('evaluation_activities')->insert(array(
            array('id' => 1, 'evaluation_handling_id' => 1, 'activity' => 'Did not greeted as per standard script', 'weightage' => 4),
            array('id' => 2, 'evaluation_handling_id' => 1, 'activity' => 'Did not greeted within time', 'weightage' => 3),
            array('id' => 3, 'evaluation_handling_id' => 1, 'activity' => 'Did not mention his/her name in script', 'weightage' => 2),
            array('id' => 4, 'evaluation_handling_id' => 1, 'activity' => 'Did not confirm the shipper/consignees Name', 'weightage' => 3),
            array('id' => 5, 'evaluation_handling_id' => 2, 'activity' => 'Did not understand the query properly.', 'weightage' => 6),
            array('id' => 6, 'evaluation_handling_id' => 2, 'activity' => 'Did not respond relevantly/specifically to caller', 'weightage' => 5),
            array('id' => 7, 'evaluation_handling_id' => 2, 'activity' => 'Did not use appropriate pace and volume, words were not clear', 'weightage' => 5),
            array('id' => 8, 'evaluation_handling_id' => 2, 'activity' => 'Did not established the rapport nor demonstrate empathy', 'weightage' => 4),
            array('id' => 9, 'evaluation_handling_id' => 2, 'activity' => 'Did not interrupt the caller', 'weightage' => 5),
            array('id' => 10, 'evaluation_handling_id' => 2, 'activity' => 'Not attentive on call', 'weightage' => 5),
            array('id' => 11, 'evaluation_handling_id' => 2, 'activity' => 'Did not pass the jargons', 'weightage' => 4 ),
            array('id' => 12, 'evaluation_handling_id' => 2, 'activity' => 'Did not pronounce properly', 'weightage' => 2),
            array('id' => 13, 'evaluation_handling_id' => 2, 'activity' => 'Discourteous during call at any level', 'weightage' => 5),
            array('id' => 14, 'evaluation_handling_id' => 2, 'activity' => 'Non verbal gestures used', 'weightage' => 3),
            array('id' => 15, 'evaluation_handling_id' => 2, 'activity' => 'Did not repeat Caller\'s name on call.', 'weightage' => 2),
            array('id' => 16, 'evaluation_handling_id' => 2, 'activity' => 'Long gap of silence', 'weightage' => 3),
            array('id' => 17, 'evaluation_handling_id' => 3, 'activity' => 'Did not ensure the usage of system properly (CRM, Portal, Software\'s and hardware\'s)', 'weightage' => 7),
            array('id' => 18, 'evaluation_handling_id' => 3, 'activity' => 'Did not take the permission from caller before putting on hold', 'weightage' => 3),
            array('id' => 19, 'evaluation_handling_id' => 3, 'activity' => 'Did not ask  for tracking details etc.', 'weightage' => 3),
            array('id' => 20, 'evaluation_handling_id' => 3, 'activity' => 'Did not log service request/complain', 'weightage' => 2),
            array('id' => 21, 'evaluation_handling_id' => 3, 'activity' => 'Log invalid complain/Service request', 'weightage' => 2),
            array('id' => 22, 'evaluation_handling_id' => 3, 'activity' => 'Wrong work code selected by agent', 'weightage' => 2),
            array('id' => 23, 'evaluation_handling_id' => 3, 'activity' => 'Did not ensure the follow-ups and coordination', 'weightage' => 2),
            array('id' => 24, 'evaluation_handling_id' => 3, 'activity' => 'Less product\'s knowledge', 'weightage' => 5),
            array('id' => 25, 'evaluation_handling_id' => 3, 'activity' => 'Did not provide correct information', 'weightage' => 3),
            array('id' => 26, 'evaluation_handling_id' => 4, 'activity' => 'Process Breach', 'weightage' => 0),
            array('id' => 27, 'evaluation_handling_id' => 4, 'activity' => 'Wrong commitments/Miss commitments', 'weightage' => 0),
            array('id' => 28, 'evaluation_handling_id' => 4, 'activity' => 'Misbehave', 'weightage' => 0),
            array('id' => 29, 'evaluation_handling_id' => 4, 'activity' => 'Harsh/Unprofessional tone of voice', 'weightage' => 0),
            array('id' => 30, 'evaluation_handling_id' => 4, 'activity' => 'Hang-up the call', 'weightage' => 0),
            array('id' => 31, 'evaluation_handling_id' => 4, 'activity' => 'Violate SOP at any Level', 'weightage' => 0),
            array('id' => 32, 'evaluation_handling_id' => 4, 'activity' => 'Incorrect Charges.', 'weightage' => 0),
            array('id' => 33, 'evaluation_handling_id' => 4, 'activity' => 'Poor vigilance', 'weightage' => 0),
            array('id' => 34, 'evaluation_handling_id' => 5, 'activity' => 'Did not provide the resolution', 'weightage' => 4),
            array('id' => 35, 'evaluation_handling_id' => 5, 'activity' => 'Did not ask "Anything else"', 'weightage' => 2),
            array('id' => 36, 'evaluation_handling_id' => 5, 'activity' => 'Did not end the call as per SOP', 'weightage' => 4),
            array('id' => 37, 'evaluation_handling_id' => 6, 'activity' => 'Complain valid but marked as invalid', 'weightage' => 4),
            array('id' => 38, 'evaluation_handling_id' => 6, 'activity' => 'Complain invalid but marked as valid', 'weightage' => 4),
            array('id' => 39, 'evaluation_handling_id' => 6, 'activity' => 'Shipper was acknowledged with valid and invalid remarks', 'weightage' => 3),
            array('id' => 40, 'evaluation_handling_id' => 7, 'activity' => 'Did not mark the follow-up comment on daily basis', 'weightage' => 2),
            array('id' => 41, 'evaluation_handling_id' => 7, 'activity' => 'Did not take follow-up from concerns', 'weightage' => 3),
            array('id' => 42, 'evaluation_handling_id' => 7, 'activity' => 'Internal Comments Missing', 'weightage' => 2),
            array('id' => 43, 'evaluation_handling_id' => 7, 'activity' => 'Did not ensure the right tagging where required', 'weightage' => 3),
            array('id' => 44, 'evaluation_handling_id' => 7, 'activity' => 'Did not ensure the tagging as it was required', 'weightage' => 3),
            array('id' => 45, 'evaluation_handling_id' => 7, 'activity' => 'Empathy missing where required', 'weightage' => 4),
            array('id' => 46, 'evaluation_handling_id' => 7, 'activity' => 'Did not use the CRM and system tools effectively', 'weightage' => 8),
            array('id' => 47, 'evaluation_handling_id' => 8, 'activity' => 'Did not ensure the usage of system properly (CRM, Portal, Software\'s and hardware\'s)', 'weightage' => 7),
            array('id' => 48, 'evaluation_handling_id' => 8, 'activity' => 'Did not take the permission from caller before putting on hold', 'weightage' => 3),
            array('id' => 49, 'evaluation_handling_id' => 8, 'activity' => 'Did not ensure the follow-ups and coordination', 'weightage' => 2),
            array('id' => 50, 'evaluation_handling_id' => 8, 'activity' => 'Less product\'s knowledge', 'weightage' => 3),
            array('id' => 51, 'evaluation_handling_id' => 8, 'activity' => 'Did not provide correct information', 'weightage' => 3),
            array('id' => 52, 'evaluation_handling_id' => 8, 'activity' => 'Call records not available where required', 'weightage' => 3),
            array('id' => 53, 'evaluation_handling_id' => 8, 'activity' => 'Call was done but discussion was not accordingly', 'weightage' => 3),
            array('id' => 54, 'evaluation_handling_id' => 8, 'activity' => 'Did not greeted as per standard script', 'weightage' => 3),
            array('id' => 55, 'evaluation_handling_id' => 8, 'activity' => 'Conversation on call was not highlighted on CRM', 'weightage' => 3),
            array('id' => 56, 'evaluation_handling_id' => 8, 'activity' => 'Not attentive on call', 'weightage' => 2),
            array('id' => 57, 'evaluation_handling_id' => 9, 'activity' => 'Salutations were not as per standard', 'weightage' => 2),
            array('id' => 58, 'evaluation_handling_id' => 9, 'activity' => 'Discourteous during chat/email', 'weightage' => 2),
            array('id' => 59, 'evaluation_handling_id' => 9, 'activity' => 'Did not used complete sentence', 'weightage' => 2),
            array('id' => 60, 'evaluation_handling_id' => 9, 'activity' => 'Idioms used in chat/email', 'weightage' => 2),
            array('id' => 61, 'evaluation_handling_id' => 9, 'activity' => 'Did not use Improper commas', 'weightage' => 2),
            array('id' => 62, 'evaluation_handling_id' => 9, 'activity' => 'Did not use Improper exclamation', 'weightage' => 2),
            array('id' => 63, 'evaluation_handling_id' => 9, 'activity' => 'Did not use Improper capitalization', 'weightage' => 2),
            array('id' => 64, 'evaluation_handling_id' => 9, 'activity' => 'Too short, choppy sentences and paragraph', 'weightage' => 3),
            array('id' => 65, 'evaluation_handling_id' => 9, 'activity' => 'Did not provide correct information', 'weightage' => 2),
            array('id' => 66, 'evaluation_handling_id' => 9, 'activity' => 'Signature issue', 'weightage' => 2),
            array('id' => 67, 'evaluation_handling_id' => 10, 'activity' => 'Process Breach', 'weightage' => 0),
            array('id' => 68, 'evaluation_handling_id' => 10, 'activity' => 'Miss commitment', 'weightage' => 0),
            array('id' => 69, 'evaluation_handling_id' => 10, 'activity' => 'Misbehave', 'weightage' => 0),
            array('id' => 70, 'evaluation_handling_id' => 10, 'activity' => 'Unprofessional/Harsh', 'weightage' => 0),
            array('id' => 71, 'evaluation_handling_id' => 10, 'activity' => 'Violate SOP at any Level', 'weightage' => 0),
            array('id' => 72, 'evaluation_handling_id' => 10, 'activity' => 'Incorrect Charges guided', 'weightage' => 0),
            array('id' => 73, 'evaluation_handling_id' => 10, 'activity' => 'Poor vigilance', 'weightage' => 0),
            array('id' => 74, 'evaluation_handling_id' => 11, 'activity' => 'Did not ensure the appropriate resolution', 'weightage' => 4),
            array('id' => 75, 'evaluation_handling_id' => 11, 'activity' => 'Closing remarks missing', 'weightage' => 3),
            array('id' => 76, 'evaluation_handling_id' => 11, 'activity' => 'Close without resolution', 'weightage' => 4),
            array('id' => 77, 'evaluation_handling_id' => 12, 'activity' => 'Salutations were not as per standard', 'weightage' => 3),
            array('id' => 78, 'evaluation_handling_id' => 12, 'activity' => 'Did not identify the recipient by name', 'weightage' => 2),
            array('id' => 79, 'evaluation_handling_id' => 12, 'activity' => 'Did not understand the subject properly', 'weightage' => 2),
            array('id' => 80, 'evaluation_handling_id' => 13, 'activity' => 'Chat Content is not focused to recipient\'s need', 'weightage' => 3),
            array('id' => 81, 'evaluation_handling_id' => 13, 'activity' => 'Agent sent an inappropriate subjected mail/chat', 'weightage' => 3),
            array('id' => 82, 'evaluation_handling_id' => 13, 'activity' => 'Descriptions are too subjective', 'weightage' => 3),
            array('id' => 83, 'evaluation_handling_id' => 13, 'activity' => 'Descriptions are too lengthy', 'weightage' => 2),
            array('id' => 84, 'evaluation_handling_id' => 13, 'activity' => 'Discourteous during chat/email', 'weightage' => 3),
            array('id' => 85, 'evaluation_handling_id' => 13, 'activity' => 'Long time gap between chat/emails', 'weightage' => 3),
            array('id' => 86, 'evaluation_handling_id' => 13, 'activity' => 'Did not used complete sentence', 'weightage' => 4),
            array('id' => 87, 'evaluation_handling_id' => 13, 'activity' => 'Idioms used in chat/email', 'weightage' => 3),
            array('id' => 88, 'evaluation_handling_id' => 13, 'activity' => 'Did not use Improper commas', 'weightage' => 3),
            array('id' => 89, 'evaluation_handling_id' => 13, 'activity' => 'Did not use Improper exclamation', 'weightage' => 2),
            array('id' => 90, 'evaluation_handling_id' => 13, 'activity' => 'Did not use Improper capitalization', 'weightage' => 2),
            array('id' => 91, 'evaluation_handling_id' => 14, 'activity' => 'Inappropriate color used to', 'weightage' => 2),
            array('id' => 92, 'evaluation_handling_id' => 14, 'activity' => 'Font style was not as per standard', 'weightage' => 3),
            array('id' => 93, 'evaluation_handling_id' => 14, 'activity' => 'Font size was not as per standard', 'weightage' => 3),
            array('id' => 94, 'evaluation_handling_id' => 14, 'activity' => 'Too short, choppy sentences and paragraph', 'weightage' => 3),
            array('id' => 95, 'evaluation_handling_id' => 14, 'activity' => 'Reflects lack of effort', 'weightage' => 4),
            array('id' => 96, 'evaluation_handling_id' => 14, 'activity' => 'Thanking before resolution', 'weightage' => 3),
            array('id' => 97, 'evaluation_handling_id' => 15, 'activity' => 'Did not ensure the usage of system properly (CRM, Portal, Software\'s and hardware\'s)', 'weightage' => 7),
            array('id' => 98, 'evaluation_handling_id' => 15, 'activity' => 'Did not take the permission from caller before putting on hold', 'weightage' => 3),
            array('id' => 99, 'evaluation_handling_id' => 15, 'activity' => 'Did not ensure the follow-ups and coordination', 'weightage' => 2),
            array('id' => 100, 'evaluation_handling_id' => 15, 'activity' => 'Less product\'s knowledge', 'weightage' => 5),
            array('id' => 101, 'evaluation_handling_id' => 15, 'activity' => 'Did not provide correct information', 'weightage' => 3),
            array('id' => 102, 'evaluation_handling_id' => 15, 'activity' => 'Call records not available where required', 'weightage' => 3),
            array('id' => 103, 'evaluation_handling_id' => 15, 'activity' => 'Call was done but discussion was not accordingly', 'weightage' => 5),
            array('id' => 104, 'evaluation_handling_id' => 15, 'activity' => 'Did not greeted as per standard script', 'weightage' => 4),
            array('id' => 105, 'evaluation_handling_id' => 15, 'activity' => 'Conversation on call was not highlighted on CRM', 'weightage' => 4),
            array('id' => 106, 'evaluation_handling_id' => 15, 'activity' => 'Not attentive on call', 'weightage' => 2),
            array('id' => 107, 'evaluation_handling_id' => 16, 'activity' => 'Signature element missing', 'weightage' => 3),
            array('id' => 108, 'evaluation_handling_id' => 17, 'activity' => 'Process Breach', 'weightage' => 0),
            array('id' => 109, 'evaluation_handling_id' => 17, 'activity' => 'Miss commitment', 'weightage' => 0),
            array('id' => 110, 'evaluation_handling_id' => 17, 'activity' => 'Misbehave', 'weightage' => 0),
            array('id' => 111, 'evaluation_handling_id' => 17, 'activity' => 'Unprofessional/Harsh', 'weightage' => 0),
            array('id' => 112, 'evaluation_handling_id' => 17, 'activity' => 'Violate SOP at any Level', 'weightage' => 0),
            array('id' => 113, 'evaluation_handling_id' => 17, 'activity' => 'Incorrect Charges guided', 'weightage' => 0),
            array('id' => 114, 'evaluation_handling_id' => 17, 'activity' => 'Poor vigilance', 'weightage' => 0),
            array('id' => 115, 'evaluation_handling_id' => 18, 'activity' => 'Did not close the email/chat/complain appropriately', 'weightage' => 3),
            array('id' => 116, 'evaluation_handling_id' => 18, 'activity' => 'Not giving the right direction for resolution', 'weightage' => 3),
        ));
    }
}
