<?php

use Illuminate\Database\Seeder;

class GulAhmedCitiesMappingTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $cities = [
            ["name" => "ABBOTABAD", "id" => "101"],
            ["name" => "ABDUL HAKIM", "id" => "102"],
            ["name" => "AHMED PUR EAST", "id" => "103"],
            ["name" => "ALIPUR", "id" => "104"],
            ["name" => "ALI PUR CHATTA", "id" => "105"],
            ["name" => "ARIF WALA", "id" => "106"],
            ["name" => "ATTOCK", "id" => "107"],
            ["name" => "BADIN", "id" => "108"],
            ["name" => "BAHAWALNAGAR", "id" => "109"],
            ["name" => "BAHAWALPUR", "id" => "110"],
            ["name" => "BANNU", "id" => "111"],
            ["name" => "BASIR PUR", "id" => "112"],
            ["name" => "BHERA", "id" => "114"],
            ["name" => "BHAKKAR", "id" => "116"],
            ["name" => "BHALWAL", "id" => "117"],
            ["name" => "BHIRIA CITY", "id" => "118"],
            ["name" => "BHIRIA ROAD", "id" => "118"],
            ["name" => "BUREWALA", "id" => "119"],
            ["name" => "CHAK JHUMRA", "id" => "121"],
            ["name" => "CHAKWAL", "id" => "122"],
            ["name" => "CHAMAN", "id" => "123"],
            ["name" => "CHENAB NAGAR", "id" => "124"],
            ["name" => "CHARSADDA", "id" => "125"],
            ["name" => "CHASHMA", "id" => "126"],
            ["name" => "CHAWINDA", "id" => "127"],
            ["name" => "CHICHAWATNI", "id" => "128"],
            ["name" => "CHINIOT", "id" => "129"],
            ["name" => "CHISHTIAN", "id" => "130"],
            ["name" => "DADU", "id" => "131"],
            ["name" => "DAHRANWALA", "id" => "132"],
            ["name" => "DEPAL PUR", "id" => "133"],
            ["name" => "DERA GHAZI KHAN", "id" => "134"],
            ["name" => "DERA ISMAIL KHAN", "id" => "135"],
            ["name" => "DAHARKI", "id" => "136"],
            ["name" => "DIJKOT", "id" => "137"],
            ["name" => "DINA", "id" => "138"],
            ["name" => "DINGA", "id" => "139"],
            ["name" => "DUNYA PUR", "id" => "141"],
            ["name" => "DOUR", "id" => "142"],
            ["name" => "ISSA KHEL", "id" => "143"],
            ["name" => "FAISALABAD", "id" => "144"],
            ["name" => "FEROZA", "id" => "148"],
            ["name" => "FORTE ABBAS", "id" => "149"],
            ["name" => "GAGGO MANDI", "id" => "150"],
            ["name" => "GAMBAT", "id" => "151"],
            ["name" => "GHOTKI", "id" => "152"],
            ["name" => "GOJRA", "id" => "154"],
            ["name" => "GUDDU", "id" => "156"],
            ["name" => "GUJARKHAN", "id" => "157"],
            ["name" => "GUJRANWALA", "id" => "158"],
            ["name" => "GUJRAT", "id" => "159"],
            ["name" => "HAFIZABAD", "id" => "161"],
            ["name" => "HALA", "id" => "162"],
            ["name" => "HANGU", "id" => "163"],
            ["name" => "HARIPUR", "id" => "165"],
            ["name" => "HARNAI", "id" => "166"],
            ["name" => "HAROONABAD", "id" => "167"],
            ["name" => "HASSAN ABDAL", "id" => "168"],
            ["name" => "HASILPUR", "id" => "169"],
            ["name" => "HUJRA SHAMUQEEM", "id" => "171"],
            ["name" => "HYDERABAD", "id" => "172"],
            ["name" => "ISKANDARABAD", "id" => "173"],
            ["name" => "ISLAMABAD", "id" => "174"],
            ["name" => "JACOBABAD", "id" => "175"],
            ["name" => "JHANGIRA", "id" => "176"],
            ["name" => "JHANIAN", "id" => "177"],
            ["name" => "JALALPUR JATTAN", "id" => "179"],
            ["name" => "JALALPURPIRWALA", "id" => "180"],
            ["name" => "JAMPUR", "id" => "181"],
            ["name" => "JAMSHORO", "id" => "182"],
            ["name" => "JARANWALA", "id" => "183"],
            ["name" => "JATOI", "id" => "184"],
            ["name" => "JOUHARABAD", "id" => "185"],
            ["name" => "JHELUM", "id" => "186"],
            ["name" => "JHANG", "id" => "188"],
            ["name" => "KABIR WALA", "id" => "190"],
            ["name" => "KAROR PAKKA", "id" => "191"],
            ["name" => "KAHOTA", "id" => "192"],
            ["name" => "KALA BAGH", "id" => "193"],
            ["name" => "KALAR KAHAR", "id" => "194"],
            ["name" => "KAMALIA", "id" => "195"],
            ["name" => "KAMER MOSHANI", "id" => "196"],
            ["name" => "KAMOKE", "id" => "198"],
            ["name" => "KANDH KOT", "id" => "200"],
            ["name" => "KANDYARO", "id" => "201"],
            ["name" => "KARACHI", "id" => "202"],
            ["name" => "KASHMORE", "id" => "203"],
            ["name" => "KASUR", "id" => "204"],
            ["name" => "KHAN BELA", "id" => "207"],
            ["name" => "KHANPUR", "id" => "208"],
            ["name" => "KHANEWAL", "id" => "209"],
            ["name" => "KHARIAN", "id" => "210"],
            ["name" => "KHUSHAB", "id" => "214"],
            ["name" => "KOHAT", "id" => "215"],
            ["name" => "KOT ADDU", "id" => "216"],
            ["name" => "KOT SAMABAH", "id" => "220"],
            ["name" => "LAHORE", "id" => "223"],
            ["name" => "LALAMUSA", "id" => "224"],
            ["name" => "LALIAN", "id" => "225"],
            ["name" => "LARKANA", "id" => "226"],
            ["name" => "LAYYAH", "id" => "227"],
            ["name" => "LIAQUATPUR", "id" => "228"],
            ["name" => "LODHRAN", "id" => "229"],
            ["name" => "LORA LAI", "id" => "230"],
            ["name" => "MAILSI", "id" => "233"],
            ["name" => "MAMUN KANJAN", "id" => "235"],
            ["name" => "MANSHERA", "id" => "237"],
            ["name" => "MARDAN", "id" => "238"],
            ["name" => "MIAN CHANOO", "id" => "240"],
            ["name" => "MIANWALI", "id" => "241"],
            ["name" => "MINCHANABAD", "id" => "242"],
            ["name" => "MINCHANABAD", "id" => "242"],
            ["name" => "MIRPUR KHAS", "id" => "243"],
            ["name" => "MIRPUR A.K.", "id" => "244"],
            ["name" => "MIRPUR MATHELO", "id" => "245"],
            ["name" => "MITHI", "id" => "246"],
            ["name" => "MATIARI", "id" => "247"],
            ["name" => "MITYARI", "id" => "248"],
            ["name" => "MORO", "id" => "250"],
            ["name" => "MULTAN", "id" => "251"],
            ["name" => "MUSLIM BAGH", "id" => "253"],
            ["name" => "MUZAFFARGARH", "id" => "254"],
            ["name" => "MUZAFFARABAD AK", "id" => "255"],
            ["name" => "NANKANA SAHIB", "id" => "256"],
            ["name" => "NAWABSHAH", "id" => "257"],
            ["name" => "NURPUR THAL", "id" => "259"],
            ["name" => "NOSHKI", "id" => "262"],
            ["name" => "NAUDERO", "id" => "263"],
            ["name" => "NOWSHERA", "id" => "264"],
            ["name" => "NOWSHERA VIRKA", "id" => "265"],
            ["name" => "NOSHERO FEROZ", "id" => "266"],
            ["name" => "OKARA", "id" => "267"],
            ["name" => "OKARA CANTT", "id" => "268"],
            ["name" => "PAK PATTAN SHARIF", "id" => "269"],
            ["name" => "PANNU AKIL", "id" => "270"],
            ["name" => "PESHAWAR", "id" => "271"],
            ["name" => "PINDI BHATIAN", "id" => "272"],
            ["name" => "SRAI ALAMGEER", "id" => "273"],
            ["name" => "PIPLAN", "id" => "274"],
            ["name" => "PIR MAHAL", "id" => "275"],
            ["name" => "PISHIN", "id" => "276"],
            ["name" => "QAZI AHMED", "id" => "278"],
            ["name" => "QILA DEDAR SING", "id" => "280"],
            ["name" => "QUAIDABAD", "id" => "282"],
            ["name" => "QUETTA", "id" => "283"],
            ["name" => "RAHIMYARKHAN", "id" => "284"],
            ["name" => "RAJANPUR", "id" => "285"],
            ["name" => "RANIPUR", "id" => "286"],
            ["name" => "RATTO DERO", "id" => "287"],
            ["name" => "RAWALPINDI", "id" => "288"],
            ["name" => "RENALA KHURD", "id" => "289"],
            ["name" => "RISALPUR", "id" => "290"],
            ["name" => "ROHRI", "id" => "291"],
            ["name" => "SADIQABAD", "id" => "292"],
            ["name" => "SAHIWAL", "id" => "293"],
            ["name" => "SUJAWAL", "id" => "295"],
            ["name" => "SAKRAND", "id" => "297"],
            ["name" => "SAMANDRI", "id" => "298"],
            ["name" => "SANGHAR", "id" => "299"],
            ["name" => "SANGLA HILL", "id" => "300"],
            ["name" => "SARGODAH", "id" => "302"],
            ["name" => "SWABI", "id" => "304"],
            ["name" => "SEHWAN", "id" => "305"],
            ["name" => "SHAHDARA", "id" => "307"],
            ["name" => "SHAHKOT", "id" => "308"],
            ["name" => "SHAHDADPUR", "id" => "310"],
            ["name" => "SHEIKHUPURA", "id" => "311"],
            ["name" => "SHIKARPUR", "id" => "312"],
            ["name" => "SHUJAABAD", "id" => "314"],
            ["name" => "SIALKOT", "id" => "315"],
            ["name" => "SIBI", "id" => "316"],
            ["name" => "SILANWALI ", "id" => "317"],
            ["name" => "SUKKUR", "id" => "318"],
            ["name" => "SWAT", "id" => "319"],
            ["name" => "TALAGANG", "id" => "320"],
            ["name" => "TANDLIANWALA", "id" => "321"],
            ["name" => "TANDO ADAM", "id" => "322"],
            ["name" => "TANDO ALLAYAR", "id" => "323"],
            ["name" => "TANDO JAM", "id" => "324"],
            ["name" => "TANDO MOHD KHAN", "id" => "325"],
            ["name" => "TARBELA", "id" => "329"],
            ["name" => "TAUNSA SHARIF", "id" => "331"],
            ["name" => "TAXILA", "id" => "332"],
            ["name" => "THATTA", "id" => "333"],
            ["name" => "TEMARGARAH", "id" => "335"],
            ["name" => "TOBATEK-SINGH", "id" => "336"],
            ["name" => "TOPI", "id" => "337"],
            ["name" => "UCH SHARIF", "id" => "338"],
            ["name" => "VEHARI", "id" => "339"],
            ["name" => "WAH", "id" => "340"],
            ["name" => "WAZIRABAD", "id" => "342"],
            ["name" => "ZAHIRPEER", "id" => "344"],
            ["name" => "ZHOB", "id" => "345"],
            ["name" => "DARY KHAN", "id" => "348"],
            ["name" => "KOT CHUTTA", "id" => "349"],
            ["name" => "FAZIL PUR", "id" => "350"],
            ["name" => "HAZRO", "id" => "352"],
            ["name" => "UMERKOT", "id" => "356"],
            ["name" => "KUNRI", "id" => "357"],
            ["name" => "MIRWAH GORCHANI", "id" => "358"],
            ["name" => "KOT GHULAM MUHD", "id" => "360"],
            ["name" => "ISLAMKOT", "id" => "361"],
            ["name" => "HAVELLIAN", "id" => "366"],
            ["name" => "HATTER", "id" => "367"],
            ["name" => "PASROOR", "id" => "381"],
            ["name" => "SAMBRIAL", "id" => "382"],
            ["name" => "DASKA", "id" => "383"],
            ["name" => "NAROWAL", "id" => "384"],
            ["name" => "SHAKAR GARH", "id" => "385"],
            ["name" => "ZAFARWAL", "id" => "387"],
            ["name" => "QADIRPUR RAWAN", "id" => "392"],
            ["name" => "PAHAR PUR", "id" => "393"],
            ["name" => "MEHMOODKOT", "id" => "394"],
            ["name" => "KACHA KHO", "id" => "395"],
            ["name" => "FATEHPUR", "id" => "396"],
            ["name" => "CHOWK AZAM", "id" => "397"],
            ["name" => "SHORKOT", "id" => "402"],
            ["name" => "BATKHELA", "id" => "404"],
            ["name" => "BHAI PHARU", "id" => "405"],
            ["name" => "DERAMURAD JAMAL", "id" => "407"],
            ["name" => "DERA ALLAHYAR", "id" => "408"],
            ["name" => "UPPER DIR", "id" => "409"],
            ["name" => "Lower DIR", "id" => "410"],
            ["name" => "MANDI BAHAUDDIN", "id" => "414"],
            ["name" => "MANDI BAHAUDDIN", "id" => "414"],
            ["name" => "MINGORA (SWAT)", "id" => "415"],
            ["name" => "PIND DADAN KHAN", "id" => "418"],
            ["name" => "CHOA SYDEN SHAH", "id" => "420"],
            ["name" => "DADYAL (A.K)", "id" => "421"],
            ["name" => "JAND", "id" => "426"],
            ["name" => "MANGLA", "id" => "434"],
            ["name" => "MURREE", "id" => "436"],
            ["name" => "PETARO", "id" => "437"],
            ["name" => "PATOKI", "id" => "443"],
            ["name" => "BAGH", "id" => "444"],
            ["name" => "RAWALAKOT", "id" => "445"],
            ["name" => "QABOOLA", "id" => "448"],
            ["name" => "KASOWAL", "id" => "449"],
            ["name" => "IQBAL NAGAR", "id" => "450"],
            ["name" => "SHABQADAR", "id" => "453"],
            ["name" => "TAKHAT BAI ", "id" => "454"],
            ["name" => "KATLANG", "id" => "455"],
            ["name" => "Shawa Adda", "id" => "459"],
            ["name" => "SAIDU SHARIF", "id" => "462"],
            ["name" => "SHAHDAD KOT", "id" => "463"],
            ["name" => "SANAWAN", "id" => "464"],
            ["name" => "RAWAT", "id" => "466"],
            ["name" => "MALAK WAL", "id" => "467"],
            ["name" => "KALA SHAH KAKU", "id" => "469"],
            ["name" => "KOTRI", "id" => "470"],
            ["name" => "SAHIWAL - FSD", "id" => "483"],
            ["name" => "KAROR LALESAN", "id" => "488"],
            ["name" => "BUDHLA SANT", "id" => "499"],
            ["name" => "KHAIRPUR", "id" => "502"],
            ["name" => "MURIDKEY", "id" => "503"],
            ["name" => "RAIWAND", "id" => "505"],
            ["name" => "RAIWAND", "id" => "505"],
            ["name" => "CHUNIAN", "id" => "507"],
            ["name" => "KOT RADHA KISHA", "id" => "510"],
            ["name" => "MANGA MANDI", "id" => "512"],
            ["name" => "MANGOWAL", "id" => "519"],
            ["name" => "DULLE WALA", "id" => "526"],
            ["name" => "MANKERA", "id" => "530"],
            ["name" => "MANKERA", "id" => "530"],
            ["name" => "KALOOR KOT", "id" => "531"],
            ["name" => "LAKI MARWAT", "id" => "532"],
            ["name" => "SERAI NAURANG", "id" => "536"],
            ["name" => "TANK", "id" => "538"],
            ["name" => "HARNOULI", "id" => "539"],
            ["name" => "KUNDIAN", "id" => "541"],
            ["name" => "GHAKAR ", "id" => "543"]
        ];
        \App\Http\Models\GulAhmedCities::truncate();
        foreach ($cities as $city){
            $gul_ahmed_cities = new \App\Http\Models\GulAhmedCities();
            $gul_ahmed_cities->city_id = $city['id'];
            $gul_ahmed_cities->city_name = $city['name'];
            $gul_ahmed_cities->save();
        }

        $user_id = 7828;

        \App\Http\Models\GulAhmedPickupAddress::truncate();
        \App\Http\Models\Shipper\UserShippingInfo::where('user_id', $user_id)->where('default_address', 0)->delete();
        $email = 'nabeel.iqbal@ideas.com.pk';
        $pickup_addresses = [
            ["warehouse_id" => "FBS001", "name" => "Hyderabad # 8", "city_id" => "172", "poc" => "Hammad", "phone" => "0310-1415393", "address" => "Plot # 495 C-1, Hyderabad"],
            ["warehouse_id" => "FBS007", "name" => "Kharrian", "city_id" => "210", "poc" => "Saqib Mehmood  ", "phone" => "0335-1553482 ", "address" => "Shop No.04 in SA & Seo Commercial Complex (Phase-I) on GT. Road, Kharian City"],
            ["warehouse_id" => "FBS014", "name" => "Mansehra", "city_id" => "237", "poc" => "Adnan Sami", "phone" => "0315-9195288", "address" => "Shop Constructed on Khasra No.529, 530 & 531, situated at Abbotabad Road, Mansehra."],
            ["warehouse_id" => "FBS016", "name" => "Kasur", "city_id" => "204", "poc" => "M.Nouman", "phone" => "0307-4173974", "address" => "Shop constructed on Plot No.BIV-9R-168A, Railway Road, Kasur, "],
            ["warehouse_id" => "FBS019", "name" => "Tilak Chari", "city_id" => "172", "poc" => "Amanullah", "phone" => "0344-8329865", "address" => "Shop # Fair Price Shop, Tilak Incline, Hyderabad"],
            ["warehouse_id" => "FBS020", "name" => "Okara", "city_id" => "267", "poc" => "Muhammad Omar", "phone" => "0322-6920069", "address" => "Saddar Bazar, Okara"],
            ["warehouse_id" => "FBS030", "name" => "FS Wazirabad", "city_id" => "342", "poc" => "Nauman Ghazanfar", "phone" => "0331-9659121", "address" => "Ground Floor Khasra No.735, Kehwat No.226, Khatooni No.281, Sialkot Road, Wazirabad"],
            ["warehouse_id" => "IDS011", "name" => "Hyderabad New", "city_id" => "172", "poc" => "zohaib", "phone" => "0312-5909918", "address" => "Plot # 7, B-15, Railways Employers Housing Society, Auto Bhan Road, Latifabad No.3,  Besides Telenor Service & Center, Hyderabad"],
            ["warehouse_id" => "IDS015", "name" => "Sailkot", "city_id" => "315", "poc" => "M Mubashar Ali", "phone" => "0305-4538709", "address" => "Eastern Portion Building,  V-Mall, Sialkot Cantt, Sialkot"],
            ["warehouse_id" => "IDS016", "name" => "Ideas Pindi", "city_id" => "288", "poc" => "Yasir Niazi", "phone" => "0333-5556812", "address" => "Plot # 3, Survey No.367/3  Banglow # 60, Bank Road,  Rawalpindi Cantt.  Rawalpindi"],
            ["warehouse_id" => "IDS034", "name" => "ISL F10", "city_id" => "174", "poc" => "Aftab Afzal", "phone" => "0312-7283361", "address" => "Building No.7-G, Lords Plaza F-10/Markaz, Islamabad   "],
            ["warehouse_id" => "IDS035", "name" => "ISL F7", "city_id" => "174", "poc" => "atif kiyani", "phone" => "0308-5222423", "address" => "Plot 13 # A, Main Double Road  F-7 Markaz, Islamabad"],
            ["warehouse_id" => "IDS036", "name" => "GA HYD", "city_id" => "172", "poc" => "Shahzaib Azhar", "phone" => "0344-3530813", "address" => "Shop # 56 & 57, Cantonment Shopping Center, Salah ud din Road, Hyderabad"],
            ["warehouse_id" => "IDS041", "name" => "Multan", "city_id" => "251", "poc" => "Rana Farhan", "phone" => "0333-7644005", "address" => "77, Abdali Tower, Near Ramada Hotel, Abdali Road, Multan.   "],
            ["warehouse_id" => "IDS042", "name" => "Peshawar", "city_id" => "271", "poc" => "Muhammad Aqeel", "phone" => "0311-8881188", "address" => "Near Mobilink Office, University Road, Peshawar "],
            ["warehouse_id" => "IDS044", "name" => "Bhawalpur", "city_id" => "110", "poc" => "Tanveer Abbas ", "phone" => "0302-7392003", "address" => "Near DC Office Chowk in, Haqi Center, Bahawalpur"],
            ["warehouse_id" => "IDS045", "name" => "Centaurus", "city_id" => "174", "poc" => "Raja Muhammad Yasir Khan", "phone" => "0301-8833358", "address" => "Shop # 201 A, Second Floor, Plot # 1, Blue Area, F/8, G/8, Jinnah Avenue, Centuarus Mall, Islamabad"],
            ["warehouse_id" => "IDS048", "name" => "EME Thokar Lhr", "city_id" => "223", "poc" => "Hafiz shahid Hanif", "phone" => "0332-4019832", "address" => "Shop # 4-10, Sraw Square, Near Muhaffiz Town Phase 1, Canal west Bank Road, Lahore"],
            ["warehouse_id" => "IDS052", "name" => "Jehlum", "city_id" => "186", "poc" => "Ahsan Hassan", "phone" => "03145454995", "address" => "Civil Lines , Jehlum"],
            ["warehouse_id" => "IDS054", "name" => "Peace n Peace Mul", "city_id" => "251", "poc" => "Harris Sultan", "phone" => "0300-7379449", "address" => "Ideas By Gul-Ahmed, Ideas Pace & Pace, Bosan road, Multan"],
            ["warehouse_id" => "IDS055", "name" => "PWD Rawalpindi", "city_id" => "288", "poc" => "Zakir Ullah Khan", "phone" => "0345-9586870", "address" => "Property # 25, Block D, Pak PWD Cooperative Housing Socity, Rawalpindi"],
            ["warehouse_id" => "IDS057", "name" => "Fortress Lhr", "city_id" => "223", "poc" => "Mazhar Sultan", "phone" => "0321-4177004", "address" => "Fortress Square Mall, Fortress Stadium, Lahore Cantt."],
            ["warehouse_id" => "IDS062", "name" => "Boulevard Mall Hyd", "city_id" => "172", "poc" => "Mohammad Hassan Shaikh", "phone" => "0346-6376541", "address" => "Shops bearing Nos. GF 6,7,8,9,10,ll,l2 of Boulevard Mall located at A-14, Auto Bhan Road, S.I.T.E Hyderabad"],
            ["warehouse_id" => "IDS063", "name" => "Bharia Town Pindi", "city_id" => "288", "poc" => "Syed Nehal Hussain", "phone" => "0315-7771457", "address" => "Sikandar Arcade Plot No 36 Spring North Express Way Bahria Town Rawalpindi"],
            ["warehouse_id" => "IDS067", "name" => "Ideas Gulghast Multan", "city_id" => "251", "poc" => "Mudassar Jamil", "phone" => "0343-2888791", "address" => "Plaza 'Mussa Centre, Gol Bagh Road Gulgasht Multan"],
            ["warehouse_id" => "IDS071", "name" => "Ideas Larkana", "city_id" => "226", "poc" => "Sami Ullah Peer Zada", "phone" => "0332-2334006", "address" => "House # 1454/2, Ward C, Nawa Tak, Mahalla, New Station Road, Near Sapna"],
            ["warehouse_id" => "IDS075", "name" => "Ideas WTC ISL", "city_id" => "174", "poc" => "Mudassar hussain", "phone" => "0312-2220212", "address" => "Shop # 01, First Floor World Trade Center Islamabad"],
            ["warehouse_id" => "IDS092", "name" => "Gujrat", "city_id" => "159", "poc" => "Ahtisham Gull", "phone" => "0306-7861111", "address" => "Ideas By Gul-ahmed, Building # 138-B, Near Normal School Ketchary Road, Gujrat."],
            ["warehouse_id" => "Ids089", "name" => "Ideas Gujranwala", "city_id" => "158", "poc" => "Waqas Zafar", "phone" => "0331-5195446", "address" => "Ideas By Gul-Ahmed, CB-2584, Near Fazal Center, GT Road, Rahwali Cantt, Gujranwala."],
            ["warehouse_id" => "FBS002", "name" => "Gold Mark II", "city_id" => "202", "poc" => "Mansha", "phone" => "0302-2555126", "address" => "Gold Mark Plot # 136, Shop # 58, National High Way, DHA Phase-1, Lower Ground, Karachi"],
            ["warehouse_id" => "FBS004", "name" => "Khanewal", "city_id" => "209", "poc" => "Sajid", "phone" => "03017421838", "address" => "Building situated at Sir Syed Road, adjacent to Diners Near Faysal Bank, Khanewal"],
            ["warehouse_id" => "FBS006", "name" => "Jhang", "city_id" => "188", "poc" => "Muhammad Zubair", "phone" => "03157020809", "address" => "Shop # 242-P, Situated at Shaheed Road, Opposite to Abidah Hospital, Jhang"],
            ["warehouse_id" => "FBS010", "name" => "Jaranwala", "city_id" => "183", "poc" => "Rana Aaqib", "phone" => "0345-7615686", "address" => "Shop constructed on Ahatha No.576/ 1, Kehwat No.417 & Khatooni No .421, Street No.03, Tanchi Bazar/Naya Bazar, Tehsil Jaranwala, "],
            ["warehouse_id" => "FBS011", "name" => "Attock", "city_id" => "107", "poc" => "Shadab Abbasi", "phone" => "0334-9900962", "address" => "Shop No. B-13 & 14 constructed on Sakin Bilalabad Jisyan Dak Khana Khaas Tahsil o Zila Attock, "],
            ["warehouse_id" => "FBS012", "name" => "Gulshan e Maymar", "city_id" => "202", "poc" => "Abdul Samad", "phone" => "0333-3275440", "address" => "Shop # 1, Gulshan e Maymar, Karachi"],
            ["warehouse_id" => "FBS021", "name" => "FS Haripur", "city_id" => "165", "poc" => "Arshad", "phone" => "0334-7213460", "address" => "GulAhmed fabric Store Near MCB Bank, Main Bazar, haripur."],
            ["warehouse_id" => "FBS022", "name" => "Muzaffarabad", "city_id" => "255", "poc" => "Imaam rabbani", "phone" => "0334-5587508", "address" => "Shop# 02 Unique College of sciences Neelum Road Lower Plate Muzaffarabad Azad Jamu Kashmir"],
            ["warehouse_id" => "FBS025", "name" => "Chakwal", "city_id" => "122", "poc" => "Muhammad Rizwan", "phone" => "0345-1520620", "address" => "Ground Floor Khasra No.730, Kehwat No. 470 & Khatooni No.1209, Talagang Road, Chakwal"],
            ["warehouse_id" => "FBS028", "name" => "Gulshan Ravi", "city_id" => "223", "poc" => "Haris Naseer", "phone" => "0336-4254467", "address" => "Plot Nc.148, A-Block, Main Boulevard, Gulshan-e-Ravi, Lahore"],
            ["warehouse_id" => "FBS029", "name" => "DI Khan", "city_id" => "135", "poc" => "Muhammad Ahmed", "phone" => "0333-9986727", "address" => "Circular road  near Toyota show room Di Khan. BM Name Shadab Abbasi "],
            ["warehouse_id" => "IDS010", "name" => "Makro Star Gate", "city_id" => "202", "poc" => "Daud", "phone" => "0306-2097105", "address" => "Makro Star Gate Makro Cash & Carry Store, Star Gate,  Shahrah-e-Faisal, Karachi"],
            ["warehouse_id" => "IDS012", "name" => "Makro LHR", "city_id" => "223", "poc" => "Khalid Khokar", "phone" => "0322-4395006", "address" => " MetroRavi Road Main Ravi Road, Lahore"],
            ["warehouse_id" => "IDS022", "name" => "Mir Pur AJK", "city_id" => "244", "poc" => "Badar Khan", "phone" => "0343-5833025", "address" => "Ground to Third Floor, Muhammad Ismail Plaza, Plot # 63-A,  Kotli Road, Mirpur Azad Kashmir."],
            ["warehouse_id" => "IDS029", "name" => "Emporium Mall Lhr", "city_id" => "223", "poc" => "Danish Ahmed", "phone" => "0312-5797041", "address" => "Shop # G 08, Emporium Mall Johar Town, Lahore"],
            ["warehouse_id" => "IDS030", "name" => "Pindi Setalite Town", "city_id" => "288", "poc" => "Asad Aziz", "phone" => "0346-9232650", "address" => "Building No B-1,  City Shopping Center,  Commercial Market, Satellite Town, Rawalpindi"],
            ["warehouse_id" => "IDS032", "name" => "Wapda Town", "city_id" => "223", "poc" => "Jawad", "phone" => "0332-4019832", "address" => "Plot # 189-F, PIA Housing Society, Wapda Town, Lahore"],
            ["warehouse_id" => "IDS050", "name" => "Mandi Bahuddin", "city_id" => "414", "poc" => "Fareed Khan", "phone" => "0300-5084965", "address" => "Hakim Mall, Jail Road, Mandi Bahuddin, "],
            ["warehouse_id" => "IDS056", "name" => "Kings Mall Guj", "city_id" => "158", "poc" => "Waqas", "phone" => "03338208236", "address" => "Ground Floor, King Mall, Bypass opposite Wapda Town, Gujrnawala."],
            ["warehouse_id" => "IDS059", "name" => "Expo Center", "city_id" => "202", "poc" => "Zohaib Ahmed", "phone" => "0306-2962830", "address" => "Ground Floor, Block 13-A, Gulshan e Iqbal. Karachi"],
            ["warehouse_id" => "IDS064", "name" => "Amanah Mall Lahore", "city_id" => "223", "poc" => "Farah Meraj", "phone" => "0322-4514994", "address" => "Shop # ff 108, Amanah Mall Lahore, Link Road"],
            ["warehouse_id" => "IDS065", "name" => "Lucky One Mall ", "city_id" => "202", "poc" => "Hassam", "phone" => "0333-3296626", "address" => "Shop # F-24, First Floor, LA-2/B, Block-21, F.B Area Rashid minhas Road, Karachi"],
            ["warehouse_id" => "IDS066", "name" => "Packages Mall", "city_id" => "223", "poc" => "Muhammad Mudassar", "phone" => "0310-4712525", "address" => "Shop # 1003-1004  First Floor, Packages Limited, Shahrah-e-Roomi, PO Amer Sidu Lahore, 54760."],
            ["warehouse_id" => "IDS068", "name" => "Ideas Nawabshah", "city_id" => "257", "poc" => "Fahad", "phone" => "0348-3899242", "address" => "Plot # 547 Ward- B Mohla Mohni Bazar, Opp NBP and near Dolphin Bakery, Nawabshah"],
            ["warehouse_id" => "IDS070", "name" => "New Ideas KDA", "city_id" => "202", "poc" => "Shakir Amjad", "phone" => "0333-2664240", "address" => "shop # 1 & 2 A-564 KDA Market Block-3, GUlshan-e-lqbal Karachi"],
            ["warehouse_id" => "FBS034", "name" => "Ideas CSD", "city_id" => "202", "poc" => "Abdul Sattar", "phone" => "03222355122", "address" => "CSD Kala Pull, Karachi"],
            ["warehouse_id" => "IDS073", "name" => "Ideas Shalimar Link Road Branch", "city_id" => "223", "poc" => "Mansoor", "phone" => "0323-4961052", "address" => "Shop situated at Plot No.9-A, Opposite Ladhi Gas Factory, Sahlimar Link Road, Lahore"],
            ["warehouse_id" => "IDS076", "name" => "Mall of Sailkot", "city_id" => "315", "poc" => "Naeem Younus", "phone" => "0348-4068129", "address" => "Plot No.100, First Floor, Shop No102 & 103,The Mall of Sialkot, Aziz Shaeed Road, Sialkot Cantt."],
            ["warehouse_id" => "IDS082", "name" => "Ideas Askari Star Mall", "city_id" => "202", "poc" => "Saqib Sindu", "phone" => "0346-3937179", "address" => "Shop # 1, 2, 3 & 4 Ground Floor Askari Star Mall-25, Karachi"],
            ["warehouse_id" => "FBS003", "name" => "Arif wala", "city_id" => "106", "poc" => "Hafiz ghulam sabir", "phone" => "0307-0431513", "address" => "Building No. 33-E, Situated at Resham Gali, Arifwala measuring 648 Sq.Ft Approximately, on the Ground Floor"],
            ["warehouse_id" => "FBS008", "name" => "Shadbagh Lhr", "city_id" => "223", "poc" => "Muhammad Usman", "phone" => "0302-4143903", "address" => "Building constructed on 674-SBNElll, Situated at Shadbagh Shceme, Lahore, "],
            ["warehouse_id" => "FBS015", "name" => "Narowal", "city_id" => "384", "poc" => "Imran Saeed", "phone" => "0334-6208219", "address" => "Zafar Wal By Pass, Near Gourment bakers, Circular Road Narowal."],
            ["warehouse_id" => "FBS017", "name" => "Mardan", "city_id" => "238", "poc" => "Hammad Khan", "phone" => "0314-5098604", "address" => "shop constructed on Divisional No.LP-910/MDX-Yard & HDE Plan No.398/LICND:L/2011/PCS, Situated at Mardan Nowshera Road, "],
            ["warehouse_id" => "FBS018", "name" => "Daska", "city_id" => "383", "poc" => "Hammad", "phone" => "0334-0045545  0345-6826447", "address" => " Building situated at College Road Near Jamia Masjid Noor - property no - B- IV - 90/B,"],
            ["warehouse_id" => "FBS023", "name" => "Talagang", "city_id" => "320", "poc" => "Ryan", "phone" => "0300-5501699", "address" => "Khasra No.718, Khatooni No.1320 & Khasra No.779, situated at Traffic Chowk, Chakwal Road, Talagang"],
            ["warehouse_id" => "FBS024", "name" => "Mian Wali", "city_id" => "241", "poc" => "Zaheer Hussain", "phone" => "0301-5419514", "address" => "Khasra No.04, Kehwat No.704, Government High School Road, Mianwali,"],
            ["warehouse_id" => "FBS035", "name" => "FS Burewala", "city_id" => "119", "poc" => "Saqib Rafi", "phone" => "0321-6924450", "address" => "Gul Ahmed Fabric Store Near UBL Multan Road Burewala"],
            ["warehouse_id" => "IDS001", "name" => "Ideas Clifton", "city_id" => "202", "poc" => "Ehtesham-Ul-Haq", "phone" => "0334-3822371", "address" => "Clifton Plot # BC 13, Block  9, Ground Floor  Razi tower, Clifton, Karachi"],
            ["warehouse_id" => "IDS002", "name" => "M.Mall", "city_id" => "202", "poc" => "Shakeel Ahmed   ", "phone" => "0321-2556911", "address" => "Millennium Millennium Mall  Plot No. 118, F-1,  Shop No.G1-17-19,  Rashid Minhas Road,  Karachi."],
            ["warehouse_id" => "IDS003", "name" => "B.Bad", "city_id" => "202", "poc" => "Shahmeer", "phone" => "0346-2703562", "address" => "Plot No.16, Shop No.5 & 6,  Central Commercial Area of  Karachi Cooperative Housing Societies  Union Limited Block-3,  Bahadurabad, Karachi."],
            ["warehouse_id" => "IDS005", "name" => "Dhoraji", "city_id" => "202", "poc" => "Furqan", "phone" => "0333-2374155", "address" => "Dhoraji Shop # 4, Ground Floor, Plot No.35-C/449,  Survey Sheet No.35-9/1, Situated Block 7&8,  C.P&Barar Co-operative Housing Society, Karachi"],
            ["warehouse_id" => "IDS006", "name" => "Ideas Attrium", "city_id" => "202", "poc" => "Faizan", "phone" => "03342106558", "address" => "Attrium Mall,249 Staff Lines,  Zaib-un-Nisa Street, Saddar, Karachi"],
            ["warehouse_id" => "IDS007", "name" => "Tariq Road", "city_id" => "202", "poc" => "Umer Butt", "phone" => "0315-2580858", "address" => "Tariq Road Shop No.2 &3, Ground Floor,  Plot No.41 & 42/c, P.E.C.H.S.,  Tariq Road, Karachi"],
            ["warehouse_id" => "IDS008", "name" => "Samama", "city_id" => "202", "poc" => "Shokat ", "phone" => "0346-3029809", "address" => "Samama Shop No.4, Ground Floor Al Khair Cloth Market,  University Road, Near Safari Park, Karachi"],
            ["warehouse_id" => "IDS018", "name" => "Lasbella", "city_id" => "202", "poc" => "kamran", "phone" => "0321-6852886", "address" => "Lasbela Bagh Sarah Appartment, Lawrence Road,  Garden West, Karachi"],
            ["warehouse_id" => "IDS025", "name" => "Mall Road", "city_id" => "223", "poc" => "shamsher Akhtar", "phone" => "0324-6111915", "address" => "Shop # S–19-59, Commercial Mall Road,  Lahore"],
            ["warehouse_id" => "IDS031", "name" => "Ideas Hyderi", "city_id" => "202", "poc" => "Zohaib Ahmed", "phone" => "0321-2868998", "address" => "D-4 Block H, North Nazimabad, Hyderi, Karachi "],
            ["warehouse_id" => "IDS040", "name" => "Dolmen City ", "city_id" => "202", "poc" => "Waqas", "phone" => "0312-3932495", "address" => "Plot # HC -3, Block 4, Scheme 5 G-4, Groupnd Floor, Dolmen City mall, Clifton Karachi"],
            ["warehouse_id" => "IDS043", "name" => "The Ocean Mall", "city_id" => "202", "poc" => "Aon Ali Jaffri", "phone" => "0321-8522756", "address" => "The Ocean Mall, Plot NO.G-3 Khyaban-e-iqbal, Block-9, Clifton, Karachi "],
            ["warehouse_id" => "IDS046", "name" => "FPS Korangi", "city_id" => "202", "poc" => "M. Siraj", "phone" => "0300-9221092", "address" => "Plot # 27 & 28., Korangi Industrial Area, Near Chamra Chowrangi, Near to KFC, Karachi"],
            ["warehouse_id" => "IDS049", "name" => "New Attrium outlet", "city_id" => "202", "poc" => "Salahuddin", "phone" => "0346-2946913", "address" => "Shop# 15,19,33,37,41&45, 1st Floor, Atrium Mall, Staff lines Saddar, Karachi."],
            ["warehouse_id" => "IDS051", "name" => "The Place", "city_id" => "202", "poc" => "Shazoor Alam", "phone" => "0342-2547178", "address" => "The Place, Karachi 214-A, Khayaban-e-Shaheen, Phase 8, Karachi."],
            ["warehouse_id" => "IDS060", "name" => "MM Alam", "city_id" => "223", "poc" => "Muhammad Syed", "phone" => "0334-9924428/0303-0006787", "address" => "13-C, Plaza MM Alam Gulberg Lahore"],
            ["warehouse_id" => "IDS072", "name" => "Ideas Sahiwal", "city_id" => "293", "poc" => "Hafiz Imran Ali        ", "phone" => "0322-7008601", "address" => "Plot # 16,17 B/1 Sir Syed Road Near Baradari Chowk"],
            ["warehouse_id" => "IDS077", "name" => "New Gujranwalla", "city_id" => "158", "poc" => "Shahzad", "phone" => "0331-9099496", "address" => "Building No. 495-B (Commercial) Satellite Town, Gujranwala,"],
            ["warehouse_id" => "IDS078", "name" => "FS Masomiyat", "city_id" => "202", "poc" => "Salman Saeed", "phone" => "0321-2320585", "address" => "Shop # 02, Nasir Manzil, Mosamiyat Karachi, Near Bank Alfalah & Bin Hashim"],
            ["warehouse_id" => "IDS087", "name" => "Faisalabad", "city_id" => "144", "poc" => "Ahsan Ghaffor DSM", "phone" => "0334-7756177", "address" => "Ali Tower, Near Al-Fateh Departmental Store, Jarranwalla Road, Faisalabad"],
            ["warehouse_id" => "IDS088", "name" => "New Iqbal Town", "city_id" => "223", "poc" => "Imran Anwar", "phone" => "0322-4719232", "address" => "14/A Pak block Allama iqbal Town Lahore."],
            ["warehouse_id" => "IDS093", "name" => "Dolmen Mall", "city_id" => "202", "poc" => "Imran Ali", "phone" => "0300-7000867", "address" => "Shop # TF-12, 3rd Floor, Dolmen Mall, Block # 3, Tariq Road, PECHS,  Karachi  "],
            ["warehouse_id" => "IDS090", "name" => "Ideas DHA Y Block", "city_id" => "223", "poc" => "Moeed Ur Rehman", "phone" => "0301-8480426", "address" => "Plot # 197-199, DHA Y Block, Commercial Area Lahore."],
            ["warehouse_id" => "IDS094", "name" => "Sharfabad", "city_id" => "202", "poc" => "Shameer", "phone" => "0346-2703562", "address" => "Shop # 9, 10 & 11 Plot # 44/3, Halima Tower, Alamgir Road, Maqbolabad CP Berar Society, Karachi."],
            ["warehouse_id" => "IDS037", "name" => "FPS 08", "city_id" => "202", "poc" => "Aamir", "phone" => "0315-2406445", "address" => "FPS GTM 08 Gul-Ahmed Textile Mills Limited HT/7, Landi Industrial Area, Karachi."],
            ["warehouse_id" => "IDS038", "name" => "FPS G", "city_id" => "202", "poc" => "Asif", "phone" => "0300-3609798", "address" => "Gulahmed FPS Store Plot # 368 & 369, Munzil Pump, Karachi"],
            ["warehouse_id" => "FR0001", "name" => "Queeta", "city_id" => "283", "poc" => "Najeeb", "phone" => "0311-2555274", "address" => "Shop # 2, M.Mall Adj to Police lane, Shahrah-e-Gulistan, Queeta"],
            ["warehouse_id" => "FR0002", "name" => "Bharia Lhr", "city_id" => "223", "poc" => "Haroon", "phone" => "0303-6143636", "address" => "Jasmine Mall, Sector -C , Talwar Chowk, Bahria Town, Lahore"],
            ["warehouse_id" => "FR0004", "name" => "Rahim Yar Khan", "city_id" => "284", "poc" => "Taimour", "phone" => "068-35879102", "address" => "Plot # 28, Town Hall, Opposite North Gate, City Park, Model Town, Rahimyar Khan"],
            ["warehouse_id" => "FR0005", "name" => "Sarghoda", "city_id" => "302", "poc" => "Haris", "phone" => "0300-5709900", "address" => "Modern Shoopping Mall  Main University Road Sargodha"],
            ["warehouse_id" => "FR0006", "name" => "Abotabad", "city_id" => "101", "poc" => "Adnan", "phone" => "0343-8902142", "address" => "Shop # 902, Main Mansehra Road, Abotabad "],
            ["warehouse_id" => "FR0007", "name" => "Sukkur ", "city_id" => "318", "poc" => "Ahmed", "phone" => "0345-3770001", "address" => "Shop # C-260/5, Camp Road, Near Muhammed Bin Qassim, Sukkur"],
            ["warehouse_id" => "E-Com", "name" => "Karachi", "city_id" => "202", "poc" => "Muhammad Hadi", "phone" => "0321-2117123", "address" => "Plot No.65/1, Sector 30, Korangi Industrial Area, Karachi"],
            ["warehouse_id" => "Mock Shop", "name" => "Karachi", "city_id" => "202", "poc" => "Khawar ", "phone" => "0321-1002426", "address" => "Plot # 12 , Sec 23 Korangi Industrial Area, Near Brooks Chowrangi, Next To Toyota & K.I.A Motors "],
            ["warehouse_id" => "MWH002", "name" => "Lahore", "city_id" => "223", "poc" => "Karachi", "phone" => "042-35971511", "address" => "Gul Ahmed Lahore Warehouse New Bakar Mandi , Slaughter House, 18 Km Shahpur Kanjran Multan Road"],
            ["warehouse_id" => "MWH003", "name" => "Islamabad", "city_id" => "174", "poc" => "Islamabad", "phone" => "0321-2440758", "address" => "Plot No. 331-332 Opposite Kashmir floor Mills limited Street No. 1 I-9/3 Industrial Area Islamabad"],

            // hotfix/TO-6468 - warehouse id's missing in Gul Ahmed Pickup Address 
            // #region new ticket work
            ["warehouse_id" => "IDS103", "name" => "Okara", "city_id" => "267", "poc" => "044-2510526", "phone" => "0322-6920069", "address" => "Ideas Outlet, M.A Jinnah Road, opposite to Diners, Okara"],
            ["warehouse_id" => "IDS122", "name" => "Karachi", "city_id" => "202", "poc" => "0213-3393216", "phone" => "0324-2031924", "address" => "Shop # 03 Plot # D-03, Block C, North Nazimabad, North Walk, Near KDA Chw, khi"],
            ["warehouse_id" => "IDS132", "name" => "Muzaffarabad", "city_id" => "255", "poc" => "(058224)42833", "phone" => "0321-5844542", "address" => "Ideas by Gul Ahmed Neelum Valley Road Lower Plate Muzaffarabad"],
            ["warehouse_id" => "IDS124", "name" => "Dera Ismail Khan", "city_id" => "135", "poc" => "0966-711193", "phone" => "0333-9986727", "address" => "Rasool Khan Plaza, North Circular Road, D.I.Khan"],
            ["warehouse_id" => "IDS115", "name" => "Rahim Yar Khan", "city_id" => "284", "poc" => "92-068 5877117-8", "phone" => "9203-4838992", "address" => "A 28,model town,oppositecity city park Main gate,Rahim yar Khan"],
            ["warehouse_id" => "IDS128", "name" => "Attock", "city_id" => "107", "poc" => "057-2700695", "phone" => "0334-9900962", "address" => "Ideas Attock, Near railway view park,Attock City. Tel: 057-2700695 Mob# 034-9900962"],
            ["warehouse_id" => "IDS126", "name" => "Bahawalnagar", "city_id" => "109", "poc" => "063-2273944 - 0632607944", "phone" => "0307-0109026", "address" => "ZM Mall Near Police Line Bahawalnagar"],
            ["warehouse_id" => "IDS121", "name" => "Karachi", "city_id" => "202", "poc" => "021-33393257", "phone" => "0345-7020441", "address" => "G16/17,Plot # D-10, Block-C, north Nazimabad Karachi"],
            // #endregion new ticket work

        ];

        foreach ($pickup_addresses as $pickup_address){

            $user_shipping_info = new \App\Http\Models\Shipper\UserShippingInfo();
            $user_shipping_info->user_id = $user_id;
            $user_shipping_info->pickup_address = $pickup_address['address'];
            $user_shipping_info->poc = $pickup_address['poc'];
            $user_shipping_info->phone = $pickup_address['phone'];
            $user_shipping_info->email = $email;
            $user_shipping_info->city_id = $pickup_address['city_id'];
            $user_shipping_info->save();
            $pickup_id = $user_shipping_info->id;

            $gul_ahmed_pickup = new \App\Http\Models\GulAhmedPickupAddress();
            $gul_ahmed_pickup->warehouse_id = $pickup_address['warehouse_id'];
            $gul_ahmed_pickup->name = $pickup_address['name'];
            $gul_ahmed_pickup->pickup_address_id = $pickup_id;
            $gul_ahmed_pickup->save();
        }


    }
}
