<?php

use Illuminate\Database\Seeder;

use Carbon\Carbon;

class NotificationTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $timestamp = Carbon::now()->format('Y-m-d H:i:s');

    	DB::table('notifications')->truncate();

        DB::table('notifications')->insert(array(
            array('id' => 1, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Activating Account for Shipper', 'type_id' => 1, 'subject' => 'Account Activated [account_id], [company_name]', 'body' => 'Dear [company_name],' . PHP_EOL . 'This is to notify you that your account has been activated in TRAX. You can now book your shipments by logging in to our portal using following credentials:' . PHP_EOL . 'Email: [email]' . PHP_EOL . 'Password: As you\'ve configured.*' . PHP_EOL . PHP_EOL . 'Thank You!' . PHP_EOL . PHP_EOL. '*For security reasons, we do not store your password in raw format.' . PHP_EOL . PHP_EOL . PHP_EOL . 'TRAX' . PHP_EOL . '0304-11-11-232', 'updated_by' => 3, 'status' => 0),
            array('id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Shipment Booked for Shipper', 'type_id' => 2, 'subject' => NULL, 'body' => 'Dear [company_name],' . PHP_EOL . 'Your shipment has been booked under [tracking_number]', 'updated_by' => 3, 'status' => 0),
                array('id' => 3, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Shipment Arrived at Origin Office for Consignee', 'type_id' => 2, 'subject' => NULL, 'body' => 'Dear [consignee_name],' . PHP_EOL . 'Your order from [company_name] is picked by TRAX under [tracking_number].' . PHP_EOL . PHP_EOL . PHP_EOL . 'Please call 0304-11-11-232 for further details.', 'updated_by' => 3, 'status' => 0),
            array('id' => 4, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Shipment Arrived at Origin Office for Shipper', 'type_id' => 1, 'subject' => 'Arrived at Origin', 'body' => 'Dear [company_name],' . PHP_EOL . 'Following of your shipments have been received by TRAX on [arrival_at]:' . PHP_EOL . '[tracking_number][order_id][consignee_name][consignee_city]' . PHP_EOL . PHP_EOL . PHP_EOL . 'Please contact at info@trax.pk or 0304-11-11-232 for further details.', 'updated_by' => 3, 'status' => 0),
            array('id' => 5, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Shipment In Transit for Shipper', 'type_id' => 1, 'subject' => '[tracking_number] - In Transit', 'body' => 'Dear [company_name],' . PHP_EOL . 'The status of your shipment [tracking_number] is updated to In Transit.' . PHP_EOL . PHP_EOL . PHP_EOL . 'Please contact at info@trax.pk or 0304-11-11-232 for further details.', 'updated_by' => 3, 'status' => 0),
            array('id' => 6, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Shipment In Transit for Shipper', 'type_id' => 2, 'subject' => NULL, 'body' => 'Dear [company_name],' . PHP_EOL . 'The status of your shipment [tracking_number] is updated to In Transit.' . PHP_EOL . PHP_EOL . PHP_EOL . 'Please contact at info@trax.pk or 0304-11-11-232 for further details.', 'updated_by' => 3, 'status' => 0),
            array('id' => 7, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Shipment Arrived at Destination Office for Shipper', 'type_id' => 1, 'subject' => '[tracking_number] - Arrived at Destination Office', 'body' => 'Dear [company_name],' . PHP_EOL . 'The status of your shipment [tracking_number] is updated to Arrived at Destination Office.' . PHP_EOL . PHP_EOL . PHP_EOL . 'Please contact at info@trax.pk or 0304-11-11-232 for further details.', 'updated_by' => 3, 'status' => 0),
            array('id' => 8, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Shipment Arrived at Destination Office for Shipper', 'type_id' => 2, 'subject' => NULL, 'body' => 'Dear [company_name],' . PHP_EOL . 'The status of your shipment [tracking_number] is updated to Arrived at Destination Office.' . PHP_EOL . PHP_EOL . PHP_EOL . 'Please contact at info@trax.pk or 0304-11-11-232 for further details.', 'updated_by' => 3, 'status' => 0),
            array('id' => 9, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Shipment(s) In Transit for Employees', 'type_id' => 1, 'subject' => 'In Transit', 'body' => 'The following shipments are In Transit against [cargo_number]:' . PHP_EOL . '[tracking_number]', 'updated_by' => 3, 'status' => 0),
            array('id' => 10, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Shipment Out for Delivery for Shipper', 'type_id' => 1, 'subject' => '[tracking_number] - Out for Delivery', 'body' => 'Dear [company_name],' . PHP_EOL . 'The status of your shipment [tracking_number] is updated to Out for Delivery.' . PHP_EOL . PHP_EOL . PHP_EOL . 'Please contact at info@trax.pk or 0304-11-11-232 for further details.', 'updated_by' => 3, 'status' => 0),
            array('id' => 11, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Shipment Out for Delivery for Shipper', 'type_id' => 2, 'subject' => NULL, 'body' => 'Dear [company_name],' . PHP_EOL . 'The status of your shipment [tracking_number] is updated to Out for Delivery.' . PHP_EOL . PHP_EOL . PHP_EOL . 'Please contact at info@trax.pk or 0304-11-11-232 for further details.', 'updated_by' => 3, 'status' => 0),
            array('id' => 12, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Shipment Out for Delivery for Consignee', 'type_id' => 2, 'subject' => NULL, 'body' => 'Dear [consignee_name],' . PHP_EOL . 'Your order from [company_name] is Out for Delivery under [tracking_number]. Please keep [amount] ready for collection.' . PHP_EOL . PHP_EOL . PHP_EOL . 'Please contact at info@trax.pk or 0304-11-11-232 for further details.', 'updated_by' => 3, 'status' => 0),
            array('id' => 13, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Shipment Delivery Status Update for Shipper', 'type_id' => 1, 'subject' => '[tracking_number] - [status]', 'body' => 'Dear [company_name],' . PHP_EOL . 'The status of your shipment [tracking_number] is updated to [status].' . PHP_EOL . PHP_EOL . PHP_EOL . 'Please contact at info@trax.pk or 0304-11-11-232 for further details.', 'updated_by' => 3, 'status' => 0),
            array('id' => 14, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Shipment Delivery Status Update for Shipper', 'type_id' => 2, 'subject' => NULL, 'body' => 'Dear [company_name],' . PHP_EOL . 'The status of your shipment [tracking_number] is updated to [status].' . PHP_EOL . PHP_EOL . PHP_EOL . 'Please contact at info@trax.pk or 0304-11-11-232 for further details.', 'updated_by' => 3, 'status' => 0),
            array('id' => 15, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Shipment Return Status Update for Shipper', 'type_id' => 1, 'subject' => '[tracking_number] - [status]', 'body' => 'Dear [company_name],' . PHP_EOL . 'The status of your shipment [tracking_number] is updated to [status].' . PHP_EOL . PHP_EOL . PHP_EOL . 'Please contact at info@trax.pk or 0304-11-11-232 for further details.', 'updated_by' => 3, 'status' => 0),
            array('id' => 16, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Shipment Return Status Update for Shipper', 'type_id' => 2, 'subject' => NULL, 'body' => 'Dear [company_name],' . PHP_EOL . 'The status of your shipment [tracking_number] is updated to [status].' . PHP_EOL . PHP_EOL . PHP_EOL . 'Please contact at info@trax.pk or 0304-11-11-232 for further details.', 'updated_by' => 3, 'status' => 0),
            array('id' => 17, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Shipment Rebooked for Shipper', 'type_id' => 1, 'subject' => '[tracking_number] - Rebooked', 'body' => 'Dear [company_name],' . PHP_EOL . 'The status of your shipment [tracking_number] is Rebooked.' . PHP_EOL . PHP_EOL . PHP_EOL . 'Please contact at info@trax.pk or 0304-11-11-232 for further details.', 'updated_by' => 3, 'status' => 0),
            array('id' => 18, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Shipment Rebooked for Shipper', 'type_id' => 2, 'subject' => NULL, 'body' => 'Dear [company_name],' . PHP_EOL . 'The status of your shipment [tracking_number] is Rebooked.' . PHP_EOL . PHP_EOL . PHP_EOL . 'Please contact at info@trax.pk or 0304-11-11-232 for further details.', 'updated_by' => 3, 'status' => 0),
            array('id' => 19, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Dispute for Everyone', 'type_id' => 1, 'subject' => 'Dispute [dispute_number] [city]', 'body' => 'Dear Concerns,' . PHP_EOL . 'A dispute has launched for [city] by [launched_by] as follows:' . PHP_EOL . '[dispute_type]' . PHP_EOL . '[dispute_description]', 'updated_by' => 3, 'status' => 0),
            array('id' => 20, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Payment Done for Shipper', 'type_id' => 1, 'subject' => 'Payment Done [payment_done_id]', 'body' => 'Dear [company_name],' . PHP_EOL . 'Following of your shipments have been paid by TRAX on [payment_done_at]:' . PHP_EOL . '[tracking_number][order_id][consignee_name][consignee_city][amount][estimated_weight][actual_weight][charges][gst][payable]' . PHP_EOL . PHP_EOL . '[total_amount], [total_charges], [total_gst], [total_payable]' . PHP_EOL . PHP_EOL . PHP_EOL . 'Please contact at info@trax.pk or 0304-11-11-232 for further details.', 'updated_by' => 3, 'status' => 0),
            array('id' => 21, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Payment Adjusted for Shipper', 'type_id' => 1, 'subject' => '[tracking_number] - Adjusted', 'body' => 'Dear [company_name],' . PHP_EOL . 'Your shipment [tracking_number] was paid mistakenly as delivered and is now Adjusted.' . PHP_EOL . PHP_EOL . PHP_EOL . 'Please contact at info@trax.pk or 0304-11-11-232 for further details.', 'updated_by' => 3, 'status' => 0),
            array('id' => 22, 'created_at' => $timestamp, 'updated_at' => $timestamp, 'name' => 'Pickup Note Dispatch for Rider', 'type_id' => 2, 'subject' => NULL, 'body' => 'Please pickup shipments from:' . PHP_EOL . '[person_of_contact][address]', 'updated_by' => 3, 'status' => 0)
        ));
    }
}
