<?php

use Illuminate\Database\Seeder;

class UpdateActivityTrailScreen extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('activity_trail_actions')->insert(array(
            array('id' => 273, 'screen_name' => 'Receiving Sheet History', 'action'=> 'View'),
            array('id' => 274, 'screen_name' => 'Receiving Sheet History', 'action'=> 'Excel Download'),
            array('id' => 275, 'screen_name' => 'Blocked Accounts List', 'action'=> 'View'),
            array('id' => 276, 'screen_name' => 'Blocked Accounts List', 'action'=> 'Excel Download'),
            array('id' => 277, 'screen_name' => 'Merged Accounts List', 'action'=> 'View'),
            array('id' => 278, 'screen_name' => 'Merged Accounts List', 'action'=> 'Excel Download'),
            array('id' => 279, 'screen_name' => 'Today Active Accounts List', 'action'=> 'View'),
            array('id' => 280, 'screen_name' => 'Today Active Accounts List', 'action'=> 'Excel Download'),
            array('id' => 281, 'screen_name' => 'Packaging Material Requests', 'action'=> 'View'),
            array('id' => 282, 'screen_name' => 'Packaging Material Requests', 'action'=> 'Excel Download'),
            array('id' => 283, 'screen_name' => 'Warehouse List', 'action'=> 'View'),
            array('id' => 284 ,'screen_name' => 'Warehouse List', 'action'=> 'Excel Download'),
            array('id' => 285, 'screen_name' => 'Sales Dashboard', 'action'=> 'View'),
            array('id' => 286 ,'screen_name' => 'Sales Dashboard', 'action'=> 'Excel Download'),
            array('id' => 287, 'screen_name' => 'POC and KAM Tagged Accounts', 'action'=> 'View'),
            array('id' => 288 ,'screen_name' => 'POC and KAM Tagged Accounts', 'action'=> 'Excel Download'),
            array('id' => 289, 'screen_name' => 'Walk-In Booking History', 'action'=> 'View'),
            array('id' => 290 ,'screen_name' => 'Walk-In Booking History', 'action'=> 'Excel Download'),
            array('id' => 291, 'screen_name' => 'Cancelled Shipments', 'action'=> 'View'),
            array('id' => 292 ,'screen_name' => 'Cancelled Shipments', 'action'=> 'Excel Download'),
            array('id' => 293, 'screen_name' => 'Consolidated Shipments', 'action'=> 'View'),
            array('id' => 294 ,'screen_name' => 'Consolidated Shipments', 'action'=> 'Excel Download'),
            array('id' => 295, 'screen_name' => 'Shipment Pieces Resolved', 'action'=> 'View'),
            array('id' => 296 ,'screen_name' => 'Shipment Pieces Resolved', 'action'=> 'Excel Download'),
            array('id' => 297, 'screen_name' => 'Pending Shipments for Bag', 'action'=> 'View'),
            array('id' => 298 ,'screen_name' => 'Pending Shipments for Bag', 'action'=> 'Excel Download'),
            array('id' => 299, 'screen_name' => 'Pending for Master Cargo', 'action'=> 'View'),
            array('id' => 300 ,'screen_name' => 'Pending for Master Cargo', 'action'=> 'Excel Download'),
            array('id' => 301, 'screen_name' => 'Remove Fake Status', 'action'=> 'View'),
            array('id' => 302 ,'screen_name' => 'Remove Fake Status', 'action'=> 'Excel Download'),
            array('id' => 303, 'screen_name' => 'Delivery Note History', 'action'=> 'View'),
            array('id' => 304 ,'screen_name' => 'Delivery Note History', 'action'=> 'Excel Download'),
            array('id' => 305, 'screen_name' => 'Delivery Consignee Signature', 'action'=> 'View'),
            array('id' => 306, 'screen_name' => 'Delivery Note History', 'action'=> 'View'),
            array('id' => 307 ,'screen_name' => 'Delivery Note History', 'action'=> 'Excel Download'),
            array('id' => 308, 'screen_name' => 'Receive Return Deliveries', 'action'=> 'View'),
            array('id' => 309 ,'screen_name' => 'Receive Return Deliveries', 'action'=> 'Excel Download'),
            array('id' => 310, 'screen_name' => 'Return For CX & Sales', 'action'=> 'View'),
            array('id' => 311 ,'screen_name' => 'Return For CX & Sales', 'action'=> 'Excel Download'),
            array('id' => 312, 'screen_name' => 'CRM - In-Process Requests', 'action'=> 'View'),
            array('id' => 313 ,'screen_name' => 'CRM - In-Process Requests', 'action'=> 'Excel Download'),
            array('id' => 314, 'screen_name' => 'CRM - Resolved Requests', 'action'=> 'View'),
            array('id' => 315 ,'screen_name' => 'CRM - Resolved Requests', 'action'=> 'Excel Download'),
            array('id' => 316, 'screen_name' => 'CRM - Closed Requests', 'action'=> 'View'),
            array('id' => 317 ,'screen_name' => 'CRM - Closed Requests', 'action'=> 'Excel Download'),
            array('id' => 318, 'screen_name' => 'Self Collection Shipments', 'action'=> 'View'),
            array('id' => 319 ,'screen_name' => 'Self Collection Shipments', 'action'=> 'Excel Download'),
            array('id' => 320, 'screen_name' => 'Disputes', 'action'=> 'View'),
            array('id' => 321 ,'screen_name' => 'Disputes', 'action'=> 'Excel Download'),
            array('id' => 322, 'screen_name' => 'Misrouted Shipments', 'action'=> 'View'),
            array('id' => 323 ,'screen_name' => 'Misrouted Shipments', 'action'=> 'Excel Download'),
            array('id' => 324, 'screen_name' => 'Intercept Requests', 'action'=> 'View'),
            array('id' => 325 ,'screen_name' => 'Intercept Requests', 'action'=> 'Excel Download'),
            array('id' => 326, 'screen_name' => 'Replacement Not Collected', 'action'=> 'View'),
            array('id' => 327 ,'screen_name' => 'Replacement Not Collected', 'action'=> 'Excel Download'),
            array('id' => 328, 'screen_name' => 'Replacement To Regular Log', 'action'=> 'View'),
            array('id' => 329 ,'screen_name' => 'Replacement To Regular Log', 'action'=> 'Excel Download'),
            array('id' => 330, 'screen_name' => 'Open Parcel History', 'action'=> 'View'),
            array('id' => 331 ,'screen_name' => 'Open Parcel History', 'action'=> 'Excel Download'),
            array('id' => 332, 'screen_name' => 'Activity Trail Log', 'action'=> 'View'),
            array('id' => 333 ,'screen_name' => 'Activity Trail Log', 'action'=> 'Excel Download'),
            array('id' => 334, 'screen_name' => 'In Transit Report Bag Wise', 'action'=> 'View'),
            array('id' => 335 ,'screen_name' => 'In Transit Report Bag Wise', 'action'=> 'Excel Download'),
            array('id' => 336, 'screen_name' => 'Master Cargo Short Received Shipments', 'action'=> 'View'),
            array('id' => 337 ,'screen_name' => 'Master Cargo Short Received Shipments', 'action'=> 'Excel Download'),
            array('id' => 338, 'screen_name' => 'Packaging Material Types', 'action'=> 'View'),
            array('id' => 339 ,'screen_name' => 'Packaging Material Types', 'action'=> 'Excel Download'),
            array('id' => 340, 'screen_name' => 'Business Projection Reasons', 'action'=> 'View'),
            array('id' => 341 ,'screen_name' => 'Business Projection Reasons', 'action'=> 'Excel Download'),
            array('id' => 342, 'screen_name' => 'Projected Shipments', 'action'=> 'View'),
            array('id' => 343 ,'screen_name' => 'Business Projection Reasons', 'action'=> 'Excel Download'),
            array('id' => 344, 'screen_name' => 'Mapping', 'action'=> 'View'),
            array('id' => 345 ,'screen_name' => 'Mapping', 'action'=> 'Excel Download'),
            array('id' => 346, 'screen_name' => 'Zonal Management', 'action'=> 'View'),
            array('id' => 347 ,'screen_name' => 'Zonal Management', 'action'=> 'Excel Download'),
            array('id' => 348, 'screen_name' => 'City Management', 'action'=> 'View'),
            array('id' => 349 ,'screen_name' => 'City Management', 'action'=> 'Excel Download'),
            array('id' => 350, 'screen_name' => 'Blacklisted Riders', 'action'=> 'View'),
            array('id' => 351 ,'screen_name' => 'Blacklisted Riders', 'action'=> 'Excel Download'),
            array('id' => 352, 'screen_name' => 'Territory List', 'action'=> 'View'),
            array('id' => 353 ,'screen_name' => 'Territory List', 'action'=> 'Excel Download'),
            array('id' => 354, 'screen_name' => 'Area List', 'action'=> 'View'),
            array('id' => 355 ,'screen_name' => 'Area List', 'action'=> 'Excel Download'),
            array('id' => 356, 'screen_name' => 'Return Parcels after Attempt', 'action'=> 'View'),
            array('id' => 357 ,'screen_name' => 'Return Parcels after Attempt', 'action'=> 'Excel Download'),
            array('id' => 358, 'screen_name' => 'Users', 'action'=> 'View'),
            array('id' => 359 ,'screen_name' => 'Users', 'action'=> 'Excel Download'),
            array('id' => 360, 'screen_name' => 'Multiple Sale Person Tagging', 'action'=> 'View'),
            array('id' => 361 ,'screen_name' => 'Multiple Sale Person Tagging', 'action'=> 'Excel Download'),
            array('id' => 362, 'screen_name' => 'User Request', 'action'=> 'View'),
            array('id' => 363 ,'screen_name' => 'User Request', 'action'=> 'Excel Download'),
            array('id' => 364, 'screen_name' => 'Fuel Management', 'action'=> 'View'),
            array('id' => 365 ,'screen_name' => 'Fuel Management', 'action'=> 'Excel Download'),
            array('id' => 366, 'screen_name' => 'Holidays', 'action'=> 'View'),
            array('id' => 367 ,'screen_name' => 'Holidays', 'action'=> 'Excel Download'),
            array('id' => 368, 'screen_name' => 'Overnight & Overland Cargo', 'action'=> 'View'),
            array('id' => 369 ,'screen_name' => 'Overnight & Overland Cargo', 'action'=> 'Excel Download'),
            array('id' => 370, 'screen_name' => 'Sales Tier', 'action'=> 'View'),
            array('id' => 371,'screen_name' => 'Sales Tier', 'action'=> 'Excel Download'),
            array('id' => 372, 'screen_name' => 'Retail Users', 'action'=> 'View'),
            array('id' => 373,'screen_name' => 'Retail Users', 'action'=> 'Excel Download'),
            array('id' => 374, 'screen_name' => 'Roles', 'action'=> 'View'),
            array('id' => 375, 'screen_name' => 'SMS History', 'action'=> 'View'),
            array('id' => 376,'screen_name' => 'SMS History', 'action'=> 'Excel Download'),
            array('id' => 377, 'screen_name' => 'Franchise', 'action'=> 'View'),
            array('id' => 378,'screen_name' => 'Franchise', 'action'=> 'Excel Download'),
            array('id' => 379, 'screen_name' => 'Trax Center', 'action'=> 'View'),
            array('id' => 380,'screen_name' => 'Trax Center', 'action'=> 'Excel Download'),
            array('id' => 381, 'screen_name' => 'International Rates Excel Upload', 'action'=> 'View'),
            array('id' => 382,'screen_name' => 'International Rates Excel Upload', 'action'=> 'Excel Download'),
            array('id' => 383, 'screen_name' => 'Handover List', 'action'=> 'View'),
            array('id' => 384,'screen_name' => 'Handover List', 'action'=> 'Excel Download'),
            array('id' => 385, 'screen_name' => 'Responsibles', 'action'=> 'View'),
            array('id' => 386,'screen_name' => 'Responsibles', 'action'=> 'Excel Download'),
            array('id' => 387, 'screen_name' => 'Download Documents', 'action'=> 'View'),
            array('id' => 388, 'screen_name' => 'Reporting Location', 'action'=> 'View'),
            array('id' => 389,'screen_name' => 'Reporting Location', 'action'=> 'Excel Download'),
            array('id' => 390, 'screen_name' => 'Designation', 'action'=> 'View'),
            array('id' => 391,'screen_name' => 'Designation', 'action'=> 'Excel Download'),
            array('id' => 392, 'screen_name' => 'Department', 'action'=> 'View'),
            array('id' => 393,'screen_name' => 'Department', 'action'=> 'Excel Download'),
            
        ));
    }
}
