image: atlassian/default-image:3

pipelines:
  branches:
    sprint_133:
      - step:
          name: 'Deploy to Sprint_132 VM'
          deployment: sprint_132
          script:
            - echo "Deploying to sprint_132 branch VM..."
            - ssh -o StrictHostKeyChecking=no $SPRINT_132_HOST "cd /var/www/html/sonic && ./deploy.sh"

    master:
      - step:
          name: 'Deploy to Production VM'
          deployment: Production
          script:
            - echo "Deploying to production server..."
            - ssh -o StrictHostKeyChecking=no $PRODUCTION_HOST "cd /var/www/html/sonic && ./deploy.sh"
